app/.gitignore, app/__tests__/App_test.re, app/__tests__/lib/Router_test.re, app/bsconfig.json, app/src/App.re, app/src/components/Navigation.re, app/src/lib/Router.re, app/src/lib/Router.rei, app/src/pages/Generic.re
This change adds routing primitives by means of a Router module which exposes the necessary building blocks to translate from urls to endpoint and build links to endpoints. At the core is the page variant which assumed along screens as coarse unit to route to. These pages can then be used to vary on them in the display logic of the main app. In turn the pages are used to construct working links to build up navigations and references throughout the app.
* implement Router module
* add Router type declarations
* use stop-gap Generic page
* build minimal navigation component
=> Add routing primitives

app/src/App.re, app/src/components/Navigation.re, app/src/index.html, app/src/lib/Router.re, app/src/lib/Router.rei, app/src/pages/Project.re
As an exercise and we have to support multiple functional contexts within a project this change explores how a sub navigation with associated routes can look like. It leaves the main composition to the App component and enabls differnt sub pages with a prop passed to a page. Along the way it entirely hides the internal use of ReasonReactRouter in the Router module by exposing `currentPage` and instead of returning a raw string, that can be used as a link, it returns a function that can be invoked when the new pushState should take effect.
* implement Project component
* use props to enable Project sub page routing
* show simple project navigation which shows active "tab"
* use `currentPage` as the main routing interface
* move from raw strings to `navigate` functions to be used by …
=> Implement project sub navigation

app/assets/global.css, app/assets/reset.css, app/src/App.re, app/src/Footer.re, app/src/Molecule.re, app/src/Topbar.re, app/src/atoms/Atom.re, app/src/atoms/AtomButton.re, app/src/atoms/AtomLayout.re, app/src/atoms/AtomLink.re, app/src/atoms/AtomText.re, app/src/index.html, app/src/pages/PageProjects.re, app/src/particles/ParticleColor.re, app/src/particles/ParticleFont.re
Start extracting repeated layout patterns into design system primitives. We'll use these to position and align components on a page as well as apply different sizing to containers.
=> Add layout primitives

.buildkite/Dockerfile, .buildkite/pipeline.yaml
Sets up minimal build pipeline utilising yarn to cache dependencies and run the bare test command. Ideally this could be extended to capture coverage.
* build custom docker image to our Reason codebase
* implement buildkite pipeline
=> Setup CI powered by buildkite

app/src/pages/PageProjects.re
List items in React are required to have a unique key assigned for the underlying diffing algorithm to work properly and compute which elements need redrawing. We also missed the `li` for the enclosing `ul`, just a small semantic fix on top.
* add key prop to project list items
* wrap list item in `li`
=> Fix project list items

.buildkite/pipeline.yaml
To please the ZFS gods we need to restrict our build agents to Docker.
=> Restrict build agent to Docker

app/src/Source.re
Until now a page refresh would lose our mock key and the "session" would be lost. This stores the key in localstorage so we can play around with the overall UX of the app until we figure out the real requirements for handling private keys.
=> Store mock key in browser's localstorage

app/package.json, app/src/main/Electron.re, proxy/src/main.rs, proxy/src/source.rs
As the deployment against a running oscoin-parity-etherum instance depends on the exact address of the deployed contract it is hard to bundle this deterministily with the app.
=> Make local source default for proxy

.buildkite/Dockerfile, .buildkite/integration-tests.sh, .buildkite/pipeline.yaml, app/.gitignore, app/LICENSE, app/README.md, app/cypress.json, app/cypress/integration/example.spec.js, app/cypress/plugins/index.js, app/cypress/support/commands.js, app/cypress/support/index.js, app/package.json, app/patches/cypress+3.5.0.patch, app/yarn.lock
For now we'll focus on testing the renderer part of the app.
Ideally we should do e2e tests for the app as a whole, but testing electron apps with cypress is still being worked on:
- https://github.com/cypress-io/cypress/issues/4964
- https://www.cypress.io/blog/2019/09/26/testing-electron-js-applications-using-cypress-alpha-release/
We should switch over to testing the whole electron app (main + renderer) when the cypress team has a more mature implementation (probably in the next few months).
=> Add cypress testing

proxy/src/env.rs, proxy/src/main.rs
I noticed the `set_var` calls were changing between versions, implying that folks are hardcoding values as needed. This PR adds a `set_if_unset` function which only sets an env var if it is unset, allowing you to set log levels and backtrace behavior as necessary while retaining useful defaults.
=> Add a convenience function to set ENV vars if not present

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/source.rs
We remove the explicit dependency on the registry runtime so that the API of only one package is used. (This does not improve the dependency footprint)
=> proxy: Remove explicit dependency on registry runtime

.buildkite/Dockerfile, .buildkite/pipeline.yaml, README.md, app/README.md
Radicle-link depends on `nettle` which in turn requires `autoconf` to be installed. This PR updates the docker container to include `autoconf`. Additionally:
- rename the docker image from `mvp` -> `radicle-upstream`
- move CI documentation to top-level `README.md`
=> Add missing autoconf dependency

.buildkite/run.sh, app/package.json
This was not working locally if the proxy hasn't been built in release
mode. It worked on CI, because we already build proxy in a separate
step via .buildkite/run.sh
=> Fix app distribution builds

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/coco.rs, proxy/src/error.rs, proxy/src/graphql/error.rs, proxy/src/graphql/schema.rs, proxy/src/registry.rs, proxy/tests/common/mod.rs, proxy/tests/graphql_mutation.rs
This avoids brittle chaining and is closer to the underlying git2 mechanisms.
Closes #139
=> Switch to new surf revparser

.buildkite/run.sh
We want to detect bad formatting and eslint errors on CI, since pre-commit hooks can be circumvented as pointed out in: https://github.com/radicle-dev/radicle-upstream/issues/131#issuecomment-586190148.
=> Run prettier and eslint checks on CI

app/src/Screens/RegisterProject.svelte, app/src/Screens/RegisterProject/TransactionSummaryStep.svelte, proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/error.rs, proxy/src/graphql/error.rs, proxy/src/graphql/schema.rs, proxy/src/registry.rs, proxy/tests/graphql_mutation.rs
It updates `register_project` and introduces `register_org` and `unregister_org`. In terms of api, it also flattens `ProjectId` to two separate params `project_name` and `org_id`, to follow the latest registry.
=> Migrate from project domain to org

app/.eslintrc.json, app/package.json, app/src/DesignSystem/Components/Avatar.svelte, app/src/DesignSystem/Components/NotificationFaucet.svelte, app/src/DesignSystem/Components/ProjectList.svelte, app/src/DesignSystem/Components/ProjectTopbar.svelte, app/src/DesignSystem/Components/ProjectTopbar/Menu.svelte, app/src/DesignSystem/Components/Sidebar/Avatar.svelte, app/src/DesignSystem/Components/SourceBrowser.svelte, app/src/DesignSystem/Components/SourceBrowser/FileList.svelte, app/src/DesignSystem/Components/SourceBrowser/FileSource.svelte, app/src/DesignSystem/Components/SourceBrowser/Folder.svelte, app/src/DesignSystem/Components/StepCounter.svelte, app/src/DesignSystem/Primitives/Button.svelte, app/src/DesignSystem/Primitives/Input/Directory.svelte, app/src/Screens/CreateProject.svelte, app/src/Screens/DesignSystemGuide.svelte, app/src/Screens/Feed.svelte, app/src/Screens/Project/Overview.svelte, app/src/Screens/RegisterProject.svelte, app/yarn.lock
So far the `.eslintrc.json` rules were only applied to `.js` files.
=> Eslint setup for svelte

proxy/Cargo.lock, proxy/Cargo.toml
Fixes #167 
Currently, we can not register a project due to the registry client used
here in the upstream not being compatible with the registry runtime used
in the devnet. Here we bump the registry-client dependency to use the
latest revision which effectively fixes the issue.
As part of the review, read [Thoma's follow up](https://github.com/radicle-dev/radicle-upstream/issues/167#issuecomment-588870068) on this issue: 
> To prevent this issue in the future we should update the runtime version whenever something changes and have the client check the runtime version. I would also suggest that the devnet should not be used for local development for now since it is highly unstable and we’re experimenting a lot.
=> Bump registry-client to fix project mutation

DEVELOPMENT.md
I added a small section on how to retrieve the GraphQL API schema from our proxy. It can be helpful when extending the schema with new endpoints.
=> Add a section about retrieving our GraphQL schema

proxy/src/avatar.rs, proxy/src/graphql/schema.rs, proxy/tests/graphql_query.rs
First follow up to #213 implementing the GraphQL query for getting an avatar given a handle as input.
=> Extend schema with avatar fallback

cypress/integration/user_registration.spec.js, cypress/support/commands.js, proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/graphql/schema.rs, proxy/src/registry.rs, ui/App.svelte, ui/Screen/UserRegistration.svelte, ui/Screen/UserRegistration/PickHandleStep.svelte
We replace the mock used so far for user registration with an actual integration with the Registry. Follow up to radicle-dev/radicle-registry#249.
Closes #185
=> feat(proxy): wire up Registry user registration

ui/DesignSystem/Primitive/Icon/TxState.svelte, ui/DesignSystem/Primitive/Icon/index.js, ui/Screen/DesignSystemGuide.svelte
This prepares showing the transaction states in the bottom right corner.
The component has the props:
- `state` pending (default), success, error
- `progress` a number between 0 and 6 with 0 being the default. This prop only has an effect in combination with state pending
The blink animation is currently set to 2 seconds and fades equally from 0.35 opacity to 1 and back.
=> Implement transaction state icon

cypress/integration/user_registration.spec.js, ui/Screen/Identity/IdentityCreationForm.svelte, ui/Screen/UserRegistration.svelte, ui/store/identity.js
Uses the identity store to fill in the handle, imageUrl and avatarFallback for the user registration and provided the stored id to the handle registration mutation.
This means that the identity creation flow has to be done before (separately) in order for the registration to succeed, as it is the only way currently to fill the identity store.
=> Use stored identity for handle registration

proxy/src/graphql/schema.rs, proxy/src/identity.rs, proxy/tests/graphql_mutation.rs, proxy/tests/graphql_query.rs
The Identity now carries a registered field which is an optional `UserId`, which is the id the user is registered with on the Registry.
Closes #255
=> feat(proxy): extend identity with registered field

proxy/src/graphql/schema.rs, proxy/src/registry.rs, proxy/tests/graphql_query.rs
Embedds the thresholds in the listTransactions query response for now. We serve two fields: `confirmation` and `settlement`.
Closes #254
=> feat(proxy): add thresholds to transaction list

proxy/src/graphql/schema.rs, proxy/tests/graphql_query.rs
In order to vary in the UI on the different messages in a transaction we introduce a kind enum exposed as a field on the messages.
Closes #253
=> feat(proxy): add kind to transaction messages

cypress/integration/project_creation.spec.js, cypress/support/commands.js, proxy/src/coco.rs, proxy/src/graphql/schema.rs, proxy/src/project.rs, proxy/tests/common/mod.rs, proxy/tests/graphql_mutation.rs, proxy/tests/graphql_query.rs, ui/DesignSystem/Component/ProjectList.svelte, ui/DesignSystem/Primitive/Input/Text.svelte, ui/Screen/CreateProject.svelte, ui/Screen/Project.svelte, ui/Screen/Project/Source.svelte
Following up on the discussions with the #product team, we decided to:
- remove project avatar images entirely
- publish projects by default (remove "publish" checkbox from existing project option)
- ~~rename button `Create project` -> `Publish project`~~
- fix validation message alignment (if the text exceeds the component width, it gets broken into two lines and centered)
=> Adjust project creation UX according to new designs

.buildkite/run.sh
I think this got downgraded in #267 by accident.
Also all builds stopped working with a bunch of weird errors.
Pointing npm to the right cache folder seems to fix this at least in this branch.
```
[4/4] Building fresh packages...
--
  | error /build/node_modules/cypress: Command failed.
  | Exit code: 1
  | Command: node index.js --exec install
  | Arguments:
  | Directory: /build/node_modules/cypress
  | Output:
  | Installing Cypress (version: 4.2.0)
  |  
  | [15:51:16]  Downloading Cypress     [started]
  | internal/streams/legacy.js:61
  | throw er; // Unhandled stream error in pipe.
  | ^
  |  
  | [Error: ENOSPC: no space left on device, write] {
  | errno: -28,
  | code: 'ENOSPC',
  | syscall: 'write'
  | }
  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation …
```
=> Revert to latest version of git-platinum

ui/Screen/UserRegistration.svelte, ui/Screen/UserRegistration/PickHandleStep.svelte, ui/Screen/UserRegistration/SubmitRegistrationStep.svelte
The avatar fallback is now dependant on the id (not the handle as before). Therefor the query can be removed from the user registration flow and the identity store can be used.
Note that the avatar query will be needed for the org registration. The implementation of the flow and querying will look very similar to the user registration flow.
=> Remove avatar fallback query from user registration

cypress/integration/routing.spec.js, ui/App.svelte
This fixes a regression introduced in #266. A browser reload won't land you on a different screen now.
=> fix(ui): fix browser refresh

package.json, ui/DesignSystem/Component/AdditionalActionsDropdown.svelte, ui/DesignSystem/Component/Topbar.svelte, yarn.lock
Because the dropdowns have `position:relative`, they create a new stacking context. By adding a `z-index` to the `Topbar`, we ensure its child dropdown stays on top:
Also, I removed the `svelte-click-outside` dependency so we'll have an easier time debugging and modifying the behavior of the `AdditionalActionsDropdown`.
Fixes part of #246
=> Fix stacking of dropdowns

ui/Screen/CreateProject.svelte, ui/src/project.ts
Fix regression in project creation introduced in #312. The create function returned a Readable store instead of a Promise.
=> fix(ui): project creation

ui/DesignSystem/Component/SourceBrowser/FileDiff.svelte
Just cleaning up some styling on the diff-expand-line
**old**
**new**
=> chore(ui): fix diff line styling

.gitignore, README.md, cypress/integration/routing.spec.js, package.json, ui/DesignSystem/Primitive/Avatar.svelte, ui/Screen/DesignSystemGuide.svelte, ui/Screen/DesignSystemGuide/Swatch.svelte, yarn.lock
I got tired of the emoji alignment issues.
The implementation is based on this discussion: https://github.com/radicle-dev/radicle-upstream/issues/231#issuecomment-604914935.
Closes #231, #290.
=> feat(ui): use Twitter svg emojis in Avatar component

proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/registry.rs
Endpoint to return all projects registered under an org.
(*) Open issue/dependency:
- when registering a project, currently `None` is always passed as the `maybe_project_id` in the proxy. In order to show any other info beside the name of the project, we need to pass the project id.
Solves part of #277
=> feat(proxy): org project list endpoint

cypress/integration/identity_creation.spec.js, ui/DesignSystem/Component/ModalLayout.svelte, ui/DesignSystem/Primitive/Avatar.svelte, ui/Screen/Identity/IdentityCreationForm.svelte, ui/Screen/Identity/IdentityCreationSuccess.svelte, ui/Screen/IdentityCreation.svelte, ui/Screen/Profile.svelte
Discovered a regression: when hitting `Cancel` or the modal close `x` button on the identity form screen there's an exception.
```
Uncaught TypeError: $store.set is not a function
at IdentityCreationForm.returnToWelcomeStep (IdentityCreation.svelte:16)
at index.mjs:620
at Array.forEach (<anonymous>)
at index.mjs:619
at click_handler (IdentityCreationForm.svelte:138)
at index.mjs:637
at Array.forEach (<anonymous>)
at bubble (index.mjs:637)
at HTMLButtonElement.click_handler (Button.svelte:12)
```
Fixed in: https://github.com/radicle-dev/radicle-upstream/pull/359/commits/ec651d0c91b3d454cc76e03b5f0e58e248449c67.
=> test(ui): improve identity creation test coverage

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/http/org.rs, proxy/src/http/user.rs, proxy/src/registry.rs
The `get_org` and `list_org` endpoints should return the list of members.
For this radicle-registry needs to based off of [the upstream branch](https://github.com/radicle-dev/radicle-registry/commit/1b044c0c408adafb4956760178c10d4779d087d4)
Part of #349
=> feat(proxy): Return the member list for an Org

DEVELOPMENT.md, package.json, proxy/src/http.rs, rollup.app.js
- make proxy logs less verbose to de-clutter local console and CI
- make `yarn test:debug` wait for proxy to start up before launching debug console
- prevent rollup from swallowing logs
=> feat: improve dev ergonomics

cypress/integration/identity_creation.spec.js, proxy/src/avatar.rs, proxy/src/http.rs, proxy/src/http/control.rs, proxy/src/http/identity.rs, proxy/src/http/org.rs, proxy/src/http/session.rs, proxy/src/http/user.rs, proxy/src/identity.rs, proxy/src/registry.rs, proxy/src/registry/transaction.rs, proxy/src/session.rs, ui/Screen/UserRegistration.svelte
Addresses the sub-optimal session handling, by actually serialising the
object itself into the store. This allows us to also keep the user
handle that was registered around and feed it to the org listing. That
means that all workflows that require local understanding of what
Registry entities are associated with the current session should work.
* serialise session object into store
* store registered user handle in session
* use user handle to query session org list
* improve internal registry API type coherence
* put a bunch of serialisations in the right place
Fixes #378
=> feat(proxy): improve session

proxy/src/http.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/session.rs, proxy/src/session.rs, ui/App.svelte, ui/src/session.ts, ui/src/settings.ts
In preparation of a range of user controlled parameters this change
extends the session with settings and the ability to update said
settings. Currently we only accept the entire settings struct to be
updated. In the future we'll likely allow more granular updates.
* add `Settings` to session
* add endpoint to update settings
Ref #128 
Ref #375
=> feat(proxy): extend session with settings

proxy/src/http/control.rs, proxy/src/http/identity.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/user.rs, proxy/src/project.rs, proxy/src/registry.rs, ui/Screen/Org.svelte, ui/Screen/Org/Projects.svelte, ui/Screen/Profile/Projects.svelte, ui/Screen/Project.svelte, ui/Screen/Project/Source.svelte, ui/src/org.ts, ui/src/project.ts
This adds the shareable entity identifiers to all endpoints.
Refs: #175, #270
- profile projects screen (for unregistered projects)
- project screen (for unregistered project)
- org screen
- org projects screen
=> feat: shareable entity identifiers

ui/Screen/OrgRegistration.svelte, ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
- Register Org
subject: `org-emoji` `org-name`
paid by: `identity-emoji` `identity-name`
- Register Project under User (with avatar URL)
subject: `identity-emoji` `identity-name` / `project-name`
paid by: `identity-emoji` `identity-name`
- Register Project under User (without avatar URL)
subject: `identity-emoji` `identity-name` / `project-name`
paid by: `identity-emoji` `identity-name`
- Register Project under Org
subject: `org-emoji` `org-name` / `project-name`
paid by: `identity-emoji` `identity-name`
=> fix(ui): show the correct avatars in summary pages

ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
=> style(ui): fix revision selector background

ui/Screen/Project/Issue.svelte, ui/Screen/Project/Issues.svelte
Updated the padding on issues & issue page:
=> fix(ui): issues padding

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/http/org.rs, proxy/src/registry.rs, proxy/src/registry/transaction.rs
This implements the api endpoint to register a user as a member under an org. In a followup PR, it will be integrated in the ui and the transaction views will be adjusted to support the new transaction type.
part of #349 
**Note** This can't fully be tested via the api playground, as we use the same `author`/key_pair for all transactions. This means we currently can't register a second user handle to then register it as a member.
=> Register member endpoint

.eslintrc.json, DEVELOPMENT.md, package.json, yarn.lock
Closes: #131
Husky:
```
work/radicle-upstream » git commit
husky > pre-commit (node v11.11.0)
✔ Preparing...
⚠ Running tasks...
✔ Running tasks for *.{js,css,json,html}
❯ Running tasks for *.js
✖ eslint --fix [FAILED]
↓ No staged files match *.svelte [SKIPPED]
↓ No staged files match *.ts [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...
✖ eslint --fix:
/Users/rudolfs/work/radicle-upstream/cypress/integration/identity_creation.spec.js
47:8  error  it.only not permitted  no-only-tests/no-only-tests
✖ 1 problem (1 error, 0 warnings)
```
If a skipped tests slips by husky, it'll error out on CI as part of the lint build step.
```
work/radicle-upstream » yarn lint
yarn run v1.22.4
$ eslint . --ignore-path .gitignore …
```
=> ci: prevent skipped tests from being committed

ui/Screen/Org/Members.svelte, ui/src/org.ts
We decided to remove the joined date from the member list, as we would either have to store the date on chain or retrieve it from the transactions.
=> Remove joined date from member list

.buildkite/run.sh, proxy/src/http/transaction.rs, proxy/src/registry/transaction.rs
As per workaround documented in: https://github.com/rust-lang/rust-clippy/issues/4612
This adds 11m to the build however : (
We should probably try to upgrade to the latest nightly version and try `-Zunstable-options`.
Closes #376.
=> fix: clippy CI

ui/Screen/Project.svelte, ui/Screen/Project/RevisionsMenu.svelte
Revision Icon was missing because of a rename in the icon-refresh-PR.
=> fix(ui): missing revision icon

DEVELOPMENT.md
Noticed that we don't have all the dependencies listed when I was trying to build Upstream from scratch on Linux.
=> docs: add Linux dev dependencies to docs

package.json, ui/index.ts, ui/src/__mocks__/api.ts, ui/src/api.ts, ui/src/avatar.ts, ui/src/commitMocks.ts, ui/src/event.ts, ui/src/identity.ts, ui/src/notification.ts, ui/src/onboard.ts, ui/src/org.test.ts, ui/src/org.ts, ui/src/path.ts, ui/src/project.ts, ui/src/remote.ts, ui/src/session.ts, ui/src/settings.ts, ui/src/source.ts, ui/src/transaction.ts, ui/src/user.ts, ui/src/validation.ts
We format everything with prettier, this PR makes sure that `*.ts` files also conform to prettier formatting:
- enforce prettier formatted `*.ts` files via CI
- automatically format `*.ts` files on commit via husky
- fix formatting in all existing `*.ts` files.
=> chore(ui): run prettier on *.ts files

cypress/integration/user_registration.spec.js, proxy/src/http/session.rs, proxy/src/session.rs, ui/Screen/Profile.svelte, ui/src/session.ts
Implements permissions for registering handle/org/project added to the session API endpoint. The use of `registerHandle` in the ui is implemented to block the user from registering a handle a second time. More details can be found in #371. 
The use cases of the other permissions will be implemented in follow up PRs.
=> feat: introduce session permissions

.buildkite/run.sh
Build binaries only on master, shaves off 15min of CI build times.
We're not using the binaries on feature branches yet. Checking the binary after a release should be enough for now.
=> chore(ci): Improve build times

cypress/integration/project_registration.spec.js, proxy/src/http/project.rs, proxy/src/http/transaction.rs, proxy/src/registry.rs, proxy/src/registry/transaction.rs, ui/src/transaction.ts
Closes #481 
The `ui > MessageType` and their corresponding `proxy > registry > Message` variants need to match in schema or else the UI will be missing out on information, which occurs now in the transaction details screen for a project registration, where `domain_id` is undefined.
More concretely, at the moment `Message::ProjectRegistration`, when serialized to the UI, includes `projectDomain { "User|Org": "id" }`, instead of `domainType` and `domainId`, as the UI counterpart expects, leading to the `undefined` we see.
=> fix(proxy): fix transaction subject for project registration

DEVELOPMENT.md, package.json, proxy/src/main.rs
Fixes #440. The proxy now accepts a node host for the `--registry`
option and can connect to an arbitrary registry node. We also provide
shortcuts for the ffnet and devnet.
=> feat(proxy): option to connect to registry nodes

cypress/integration/org_registration.spec.js
This test fails most of our CI runs now that the CI server is more loaded and slower.
We should fix the underlying issue https://github.com/radicle-dev/radicle-upstream/issues/492 before we un-skip this test.
=> chore(ui): skip flaky test

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/http/control.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/user.rs, proxy/src/registry.rs
Closes #470, expect the `Hash` type which is handled in #https://github.com/radicle-dev/radicle-upstream/pull/493
Drops the duplicated registry types by moving their trait implementations to the respective types in the registry.
=> chore(proxy): Drop duplicated registry types

ui/DesignSystem/Component/Sidebar.svelte
Follow-up to: https://github.com/radicle-dev/radicle-upstream/pull/489.
Gets rid of warning:
```
(!) Circular dependency
ui/DesignSystem/Component/index.js -> ui/DesignSystem/Component/Sidebar.svelte -> ui/DesignSystem/Component/index.js
```
=> chore(ui): fix circular dependency

cypress/integration/identity_creation.spec.js, cypress/integration/routing.spec.js, cypress/integration/settings_specs.js, cypress/integration/user_registration.spec.js, proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/coco.rs, proxy/src/error.rs, proxy/src/http.rs, proxy/src/http/error.rs, proxy/src/http/identity.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/session.rs, proxy/src/http/source.rs, proxy/src/identity.rs, proxy/src/project.rs, proxy/src/registry.rs, proxy/src/session.rs, ui/Screen/IdentityCreation.svelte
Depends on https://github.com/radicle-dev/radicle-link/pull/186
Fixes #478 
This solves the ability to create and get a user in the monorepo, as well as linking it up with the identity create and get API.
Also threw in changes for get project, since the change we rely on in `radicle-link` allows us to fix that.
=> feat(proxy): User Creation

proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/user.rs
The `transactionFee` was missing from the example inputs so that the registration requests in the playground failed.
=> fix(proxy): add transactionFee to example inputs

cypress/integration/org_registration.spec.js
Same as https://github.com/radicle-dev/radicle-upstream/pull/501.
This test fails most of our CI runs now that the CI server is more loaded and slower.
We should fix the underlying issue #492 before we un-skip this test.
https://buildkite.com/monadic/radicle-upstream/builds/2807
=> chore(ui): skip another flaky test

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/coco.rs
Allows us to list projects and users via the Peer and means that project and user retrieval is persistent across runs.
=> feat(proxy): List Entities

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/registry.rs
This updates the registry client to a newer version that requires passing the runtime version explicitly. The APIs for these are subject to change but this serves as a proof-of-concept for setting the runtime version on the proxy side.
=> Pass registry runtime version explicitly

ui/DesignSystem/Component/SourceBrowser/File.svelte, ui/DesignSystem/Component/SourceBrowser/Folder.svelte, ui/Screen/Project/Source.svelte, ui/src/config.ts, ui/src/path.ts, ui/src/source.ts
So far part of the source browsing state was in the router and another part in the global store. With this PR all the state will live in the Typescript/Svelte store.
We don't gain anything by having this state in the browser's window.location as it isn't presented to the user. And if we will want to present it to the user it's going to be easier to just grab it from the store.
This is in preparation of the UI changes for https://github.com/radicle-dev/radicle-upstream/issues/443.
=> refactor(ui): move all repository browsing state into store

cypress/integration/project_source_browsing.spec.js, package.json, proxy/src/http/source.rs, ui/Screen/Project/Commits.svelte, ui/Screen/Project/Source.svelte, ui/src/path.ts, ui/src/source.ts
* Fixes an issue with branch names that have a `/` in them not being able to be loaded.
* Fixes a reactivity bug with `svelte-spa-router`, that broke the commits link
=> Fix commits view

ui/Screen/Settings.svelte
Changed font color of the text descriptions in Settings from `foreground` to `foreground-level-6`.
Signed-off-by: Brandon Oxendine <brandon.oxendine@gmail.com>
=> fix(ui): color of description text in Settings

cypress/integration/project_source_browsing.spec.js, ui/DesignSystem/Component/HorizontalMenu/MenuItem.svelte, ui/DesignSystem/Component/SourceBrowser/File.svelte, ui/DesignSystem/Component/SourceBrowser/Folder.svelte, ui/Screen/Project.svelte, ui/Screen/Project/Source.svelte, ui/src/config.ts, ui/src/path.ts, ui/src/source.ts
https://github.com/radicle-dev/radicle-upstream/pull/564 was a flawed idea. We **do** want to have the state in the router after all. Otherwise we won't be able to use the router history to navigate back and forth in the repo browser.
Basically @xla was right about "deep-linking" in: https://github.com/radicle-dev/radicle-upstream/pull/564#pullrequestreview-436443237.
Fixes #406
Fixes #438.
=> fix(ui): fix various routing issues

proxy/src/http.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/user.rs, ui/src/project.ts
Closes #474 
Moves away from `POST projects/register/` with an intertwined payload to have `POST users/<handle>/projects/<name>` and `POST orgs/<id>/projects/<name>`. The payload, `RegisterProjectInput` and the HTTP handler `register_project` are shared and DRY for both endpoints.
1. When I introduced the new endpoints under `/users`, I ran into this issue where the result of the request was a `500`:
```
'res is Response { status: 500, version: HTTP/1.1, headers: {"content-type": "text/plain; charset=utf-8"}, body: b"Request body consumed multiple times" }', src/http/user.rs:560:9
```
Searching for `Request body consumed multiple times` led me to https://github.com/seanmonstar/warp/issues/291. So, the order in which the endpoint "filters" are combined either makes it or breaks it. That's …
=> refactor(proxy): improve api ergonomics around project registration

proxy/Cargo.lock, proxy/Cargo.toml
By removing the unused `warp` features, we go from 578 -> 549 transitive dependencies.
=> Reduce dependency footprint a little

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/coco.rs, proxy/src/coco/source.rs, proxy/src/error.rs, proxy/src/http/error.rs
We have begun to publish radicle-surf to crates.io again. In this change
we use this method for retrieving radicle-surf rather than through
librad. This is because librad will not re-export surf soon: https://github.com/radicle-dev/radicle-link/pull/224.
The major difference here is that we can't simply create a Browser from
the Storage/Repo anymore. Instead, we must use the Paths to get the
git_dir and setup the Browser that way -- also calculating the Namespace
for the Project's RadUrn.
=> chore(proxy): depend on radicle-surf directly

ui/Screen/Project/Commits.svelte, ui/Screen/Project/Source.svelte
This is a proof of concept that results in no flickering when navigating to commits view. Looking to make this approach as general as possible.
=> fix(ui): remove flicker in source view

ui/DesignSystem/Component/Error.svelte, ui/DesignSystem/Component/index.js, ui/Screen/Org/Projects.svelte, ui/Screen/Profile/Projects.svelte
Introduce `Error` component for displaying full-width error messages.
Before:
After:
=> fix(ui): fix error display

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/coco/control.rs, proxy/src/coco/peer.rs, proxy/src/coco/source.rs, proxy/src/http.rs, proxy/src/http/control.rs, proxy/src/http/identity.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/source.rs, proxy/src/http/user.rs, proxy/src/identity.rs, proxy/src/keystore.rs, proxy/src/main.rs
Before integrating the `rad/self` feature we need to deal with the fact we're not able to get a `SecretKey` anymore from the `PeerApi`. This PR achieves that by adding the `SecretKey` as a parameter where needed. Then to get hold of the key we use the `Keystorage` to access it.
We need to have `User` in the monorepo when we create a project. This is so we can add the owner as a certifier, which _must_ be resolvable to an entity in the monorepo. This means we get rid of `fake_owner` and instead use `init_user` + `verify_user` instead.
=> chore(proxy): update librad

proxy/src/http/control.rs, proxy/src/http/project.rs
While merging to our main branch, the code was clean but it caused an issue when the `peer` variable wasn't defined in scope to get the `stats` of the project. This PR fixes this by doing `let peer` again.
=> fix(proxy): merge fix

ui/DesignSystem/Component/Transaction/Center.svelte, ui/DesignSystem/Component/Transaction/Item.svelte, ui/DesignSystem/Component/Transaction/List.svelte, ui/DesignSystem/Component/Transaction/Summary.svelte
This will close #578 but there's still one more thing to do on it that I couldn't figure out:
---
The changes to the text are being taken care of in #572.
=> refactor(ui): transaction list visual updates

package.json, proxy/Cargo.toml, proxy/src/bin/nuke.rs, proxy/src/coco/control.rs, proxy/src/config.rs, proxy/src/lib.rs, proxy/src/main.rs, ui/Screen/Settings.svelte
Developers often are unable to start up the app because the state on disk is not compatible with code versions or it has been corrupted in other ways. To remedy that and provide a drastic tool to get uninitated unstuck without the knowledge of the on disk fs layout, this change-set introduces `yarn nuke`.
Closes #394
=> feat: implement nuke command

cypress/integration/project_source_browsing.spec.js, proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/coco.rs, proxy/src/coco/peer.rs, proxy/src/http.rs, proxy/src/http/control.rs, proxy/src/http/identity.rs, proxy/src/http/project.rs, proxy/src/identity.rs, proxy/src/main.rs, ui/Screen/IdentityCreation.svelte, ui/Screen/IdentityCreation/Form.svelte
Depends on https://github.com/radicle-dev/radicle-link/pull/229
Fixes #576 
Closes #548
This integrates the use of `rad/self` in the monorepo. This means when we create an identity, we set the default `rad/self` in the peer to that `User`.
We can now filter the projects by the `rad/self` of the `Project` is the same as the default `rad/self`. This is demonstrated in [test_list_projects](https://github.com/radicle-dev/radicle-upstream/compare/fintan/rad-self?expand=1#diff-8b447e0828f494b1a01fea3e55d2925eR497)
=> feat(proxy): integrate rad/self

cypress/integration/project_source_browsing.spec.js, ui/DesignSystem/Component/SourceBrowser/FileSource.svelte, ui/DesignSystem/Component/SourceBrowser/Folder.svelte, ui/Screen/Project/Source.svelte, ui/src/path.ts
Fixes regressions introduced in https://github.com/radicle-dev/radicle-upstream/pull/620:
- source tree file highlighting
- topbar `Source` menu item active state
- source tree expanded state persistance
Adds tests for all the regressions.
=> fix(ui): fix repository selector regressions

proxy/src/coco/source.rs, proxy/src/http/source.rs, ui/DesignSystem/Component/UserCard.svelte, ui/Screen/DesignSystemGuide.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/559.
Before:
After:
=> chore(ui): remove avatars from commit authors

native/main.js
Closes: https://github.com/radicle-dev/radicle-upstream/issues/428.
We still need to figure out how to handle relative links that get rendered by the `marked` plugin.
=> fix(ui): open external links in default OS browser

proxy/src/coco.rs, proxy/src/error.rs, proxy/src/http.rs, proxy/src/http/control.rs, proxy/src/http/identity.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/user.rs, proxy/src/identity.rs, proxy/src/main.rs, proxy/src/project.rs, proxy/src/registry.rs, proxy/src/registry/transaction.rs, proxy/src/session.rs
This removes the brittle handling of holding onto an owner, instead we read the necessary on per request basis.
=> chore(proxy): fetch owner on request

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/coco/peer.rs, proxy/src/coco/source.rs, proxy/src/http.rs, proxy/src/http/identity.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/source.rs, proxy/src/identity.rs, proxy/src/main.rs
With the advent of sync resolvers we can simplify some of our internal
APIs and don't have to pass down ARGH mutexes.
=> chore(proxy): bump coco deps

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/error.rs, proxy/src/http/transaction.rs, proxy/src/registry.rs, proxy/src/registry/transaction.rs
To go ahead with https://github.com/radicle-dev/radicle-upstream/issues/641, we need to adjust to the latest breaking changes presented by the radicle registry client.
@xla the biggest chunk here is moving to `Optional<BlockNumber>`. Could you have a detailed look at how I've done it? I didn't introduce those changes in the Registry and it's not 100% clear to me if I am doing the right thing in all affected lines of code.
=> chore(proxy): Bump registry client

cypress/integration/org_registration.spec.js, cypress/integration/user_registration.spec.js, proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/http.rs, proxy/src/http/id.rs, proxy/src/registry.rs, proxy/src/registry/transaction.rs, ui/src/id.ts, ui/src/org.test.ts
Closes #641 
It introduces a new endpoint `ids/<id>/status` that fetches the availability status of a given id in the registry, that is either `available | retired | taken`. In the UI, we now call this endpoint and validate the availability of an id based on its status being `available`. The error message is changed from "Sorry, this one is already taken" to "Sorry, this one is no longer available", which better represents the semantics behind an id not being available.
To make testing possible, I added support to unregister a user from the registry in the proxy only.
**Note**: In a follow up issue I would move the `avatars/<id>` endpoint under `ids`, as `ids/<id>/avatar`.
=> chore(ui): Adjust id validation

ui/DesignSystem/Component/RadioOption.svelte, ui/Screen/Discovery/Project.svelte
- Fixing hoverstates on `new project creation`
- fixes hoverstates on discovery
closes #674
=> style(ui): cleanup

proxy/src/registry.rs
We extract common logic into `Client::submit_transaction`. Closes #672
=> refactor(proxy): dry submit transactions

.buildkite/run.sh
This attempts to fix failing builds due to `Error: ENOSPC: no space left on device, write` during `yarn install`.
Initially I thought it might be some limit on CI that we're hitting, but after investigating a running image where this error happens I could rule out disk space issues. However, I noticed that re-running `yarn install` a second time, it worked just fine.
So as a workaround I added a re-try to `yarn install` in the CI build script.
Here's what a [successful retry](https://buildkite.com/monadic/radicle-upstream/builds/3573#bca39fdb-061d-4e2d-84b9-9533ab07aeb7) looks like:
```
> Installing yarn dependencies
yarn install v1.22.4
--
  | [1/4] Resolving packages...
  | [2/4] Fetching packages...
  | info fsevents@2.1.3: The platform "linux" is incompatible with this module.
  | …
```
=> fix(ci): fix flaky builds

.buildkite/env.sh, .buildkite/run.sh
There's was a 200Mb (now upped to 500Mb) limit on CI for /tmp. Yarn install sometimes uses more when it has to download, extract and build electron, cypress, etc.
=> fix(ci): for real now

package.json, proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/bin/git-remote-rad.rs
Pre-requisite for: https://github.com/radicle-dev/radicle-upstream/issues/601.
=> feat(proxy): build and package rad-remote-helper with Upstream

proxy/src/http.rs, proxy/src/http/avatar.rs, proxy/src/http/control.rs, proxy/src/http/doc.rs, proxy/src/http/id.rs, proxy/src/http/identity.rs, proxy/src/http/notification.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/session.rs, proxy/src/http/source.rs, proxy/src/http/transaction.rs, proxy/src/http/user.rs
In order to have the endpoint modules not be concerned/in the know of
where they are mounted in the public API we centralis these in the main
http module. This in turn reduces unnecessary compilation guards and the
overhead to think about when boostrapping another namespace.
=> refactor(proxy): move http mount points

.buildkite/run.sh, proxy/src/registry.rs
This was first fixed in:
https://github.com/radicle-dev/radicle-upstream/pull/430.
But then later broken in:
https://github.com/radicle-dev/radicle-upstream/pull/721.
=> fix(ci): make clippy work on CI again

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/coco/config.rs, proxy/src/coco/peer.rs
Quoting @FintanH 
> In the latest changes of librad, the method of signing was
parameterised. For now, we will fill in this parameter using the
SecretKey. In reality, it should be a parameter itself so we can choose
SecretKey for tests or a client for the main application.
=> chore(proxy): bump librad

ui/App.svelte, ui/DesignSystem/Primitive/Button.svelte, ui/Hotkeys.svelte, ui/Screen/Help.svelte, ui/Screen/Settings.svelte, ui/Screen/Shortcuts.svelte, ui/src/path.ts, ui/src/settings.ts
Adds keyboard shortcuts:
// To open help => OS modifier key + /
// To open settings => OS modifier key + ,
// To open search => OS modifier key + p
// To open design system => OS modifier key + d
// To create a new project => OS modifier key + n
Also uses `cmd` key on mac and `ctrl` on other OS's for all shortcuts.
closes #756
=> feat(ui): add keyboard shortcuts

proxy/src/coco/control.rs, proxy/src/coco/peer.rs, proxy/src/coco/source.rs, proxy/src/http/control.rs, proxy/src/http/identity.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/source.rs, proxy/src/http/user.rs, proxy/src/identity.rs, proxy/src/main.rs, proxy/tests/checkout.rs
We had a clippy warning to allow passing by value even though the
function was not consuming. This removes that pragma and fixes the
clippy and compiler errors.
=> chore(proxy): remove needless_pass_by_value check

.buildkite/run.sh, proxy/src/lib.rs
We remove `#[deny(warnings)]` since this is [considered an anti-pattern][1]. Instead we deny warnings during CI to ensure that we only commit warning-free code.
[1]: https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deny-warnings.md
=> chore(proxy): tests and binaries can be run with lint warnings

proxy/Cargo.lock, proxy/Cargo.toml
Catch up with radicle-dev/radicle-keystore#6 and
radicle-dev/radicle-link#281
=> chore(proxy): bump librad and keystore

ui/DesignSystem/Component/RemoteHelperHint.svelte, ui/Screen/Project/CheckoutButton.svelte
`~` never gets expanded in exports.
=> fix(ui): fix remote helper export

proxy/src/http.rs, proxy/src/http/error.rs
* Add a filter `with_qs_opt()` that handles optional query parameters. This will be used in #789
* Reject with routing error instead of panicking if query cannot be parsed. Fixes #788
=> refactor(proxy): Improve query string parsing

ui/Hotkeys.svelte, ui/Screen/Shortcuts.svelte
* Hotkeys dispatch uses `KeyboardEvent.key` instead of `KeyboardEvent.code` which does not respect the keyboard layout.
* Use Cmd/Ctrl+h for hotkey list instead of shift+/ which is hard to type on non-US layouts.
* Prevent fast toggling on repeat presses
=> fix(ui): Accessible hotkeys for other layouts

proxy/src/http.rs, proxy/src/http/project.rs, proxy/src/project.rs
We add the `user` query parameter to the `GET /projects` endpoint. If provided only projects that are tracked by the given user are returned.
Closes #741
=> feat(proxy): filter projects by user URN

public/global.css, ui/Screen/Project/Source.svelte, ui/Screen/ProjectCreation.svelte, ui/src/screen.ts
This locks the project creation modal and the project checkout flow while waiting for proxy to finish the request.
It's a stop-gap solution for: https://github.com/radicle-dev/radicle-upstream/issues/650 and https://github.com/radicle-dev/radicle-upstream/issues/512.
NB: the cursor looks broken only in the screengrab. It looks like this in reality:
Inspired by: https://github.com/radicle-dev/radicle-upstream/pull/566.
=> feat(ui): lock screen during long backend activity

ui/DesignSystem/Component/AdditionalActionsDropdown.svelte, ui/DesignSystem/Component/Header/Large.svelte, ui/DesignSystem/Component/Sidebar.svelte, ui/DesignSystem/Component/SidebarLayout.svelte, ui/Screen/Profile.svelte
Remove links to the following features
- wallet
- register handle button
- add org button / orgs sidebar entries
Fix dropdown style where the bottom border was visible when there was only one entry.
Before:
After:
=> chore(ui): remove links to registry features

cypress/integration/project_checkout.spec.js, proxy/api/src/http/error.rs
We disallow checking out a project to the same directory more than once.
This improves the error message.
Before:
After:
=> fix(ui): improve checkout error message

proxy/coco/src/source.rs, ui/Screen/ProjectCreation.svelte
It failed because the surf `Browser` has to be initialised with a revision. This revision was set to "master" by default.
The workaround for now is to fall back to the first branch of the repository, if it doesn't have a "master" branch.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/821.
=> fix(proxy): project creation from repo without master

proxy/api/src/context.rs, proxy/api/src/http.rs, proxy/api/src/http/control.rs, proxy/api/src/http/identity.rs, proxy/api/src/http/project.rs, proxy/api/src/http/session.rs, proxy/api/src/http/source.rs, proxy/api/src/lib.rs, proxy/api/src/main.rs
As more components will rely on access to common dependencies we need a safe way to share them, beyond just the http subs-system. By extracting the context machinery into a top-level module it is not part of the http domain anymore, which not just depends on an already constructed `Ctx` instead of constructing one on the spot.
Part of #602
=> refactor(proxy): extract context

proxy/coco/src/peer.rs
Closes #845 
Adding fetch to the set of methods on Api. This allows us to contact a
peer and fetch any changes. We test this by doing exactly that exchange,
where one peer commits and the other follows up with a fecth.
=> feat(proxy): fetch project updates

proxy/api/src/main.rs, proxy/coco/src/announcement.rs, proxy/coco/src/peer.rs
The function `with_protocol` in `coco` can just be a simple delegated
getter to the underlying coco peer api. No need to receive a function as an
argument and operate on BoxFuture.
Triggering context: https://github.com/radicle-dev/radicle-upstream/pull/875#discussion_r484342112
=> refactor(proxy): Simplify with_protocol

proxy/Cargo.lock
Just a ultra-quick chore, as I had noticed these last days that a few dependencies were outdated.
=> chore(proxy): Run cargo update

proxy/coco/src/announcement.rs, proxy/coco/src/peer.rs
Splits up the functionality of getting signed refs for a project, to
make mis-use hard we have two methods now. One to obtain the `Refs` for
the owner of the monorepo and one to get the them for a peer.
***
Backport from #881 and sparked by https://github.com/radicle-dev/radicle-upstream/pull/881#discussion_r487044797.
=> fix(proxy): signed refs retrieval for projects

DEVELOPMENT.md, cypress/integration/project_creation.spec.js, cypress/support/index.js, native/ipc.js, native/preload.js, package.json, ui/Hotkeys.svelte, ui/Modal/Shortcuts.svelte, ui/Screen/Org.svelte, ui/Screen/Org/Members.svelte, ui/Screen/Project.svelte, ui/Screen/Project/SourceMenu.svelte
Closes #888 
This is a feature flag that is consumed by the app as `isExperimental`,
signalling whether we are running the app with the experimental mode on,
which toggles experimental/under construction features. This flag is
only allowed in development mode.
A new yarn command is added, `yarn start:public`, which starts the app
in public mode, i.e, hiding all the experimental features. Such run
simulates a production preview while running in development mode.
=> feat(ui): introduce experimental flag

package.json
With the flags so far we used to build integration test suites during
release, this is unnecessary and takes time.
=> chore(proxy): avoid building non-release targets

QA.md, cypress/integration/onboarding.spec.js, ui/DesignSystem/Component/Header/Large.svelte, ui/Modal/ProjectCreation.svelte, ui/Screen/Onboarding/EnterName.svelte, ui/Screen/Onboarding/Success.svelte, ui/Screen/Settings.svelte, ui/src/onboarding.ts
- use `display name` instead of `handle` in validations, closes: https://github.com/radicle-dev/radicle-upstream/issues/919
- hide "Session management" section in settings behind `isDev` (based on discussion in Figma)
- update onboarding success screen copy
- fix wording in project creation tooltip ("the the" -> "the")
- respect singular/plural noun forms in project stats
=> chore(ui): fix ui consistency

cypress/integration/project_source_browsing.spec.js, proxy/api/src/http/source.rs, proxy/coco/src/source.rs, ui/DesignSystem/Component/HorizontalMenu.svelte, ui/DesignSystem/Component/HorizontalMenu/MenuItem.svelte, ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte, ui/Screen/Project.svelte, ui/Screen/Project/Commits.svelte, ui/Screen/Project/PeerSelector.svelte, ui/Screen/Project/Source.svelte, ui/src/source.ts
* extends the commit endpoint with stats
* shows the correct commit count of the selected peer and branch
* cleans up the variables project page components
Note: Changing the selected peer can't be tested right now.
Closes #924 
**TODO**
=> fix: show commit count on project page

proxy/Cargo.lock, proxy/api/src/main.rs, proxy/coco/Cargo.toml, proxy/coco/src/config.rs
Bumps to the link version that keeps connections alive sending keep
alive messages. Additionally introduces the ability to listen on all
network addresses to enable communication with remote hosts.
=> feat(proxy): keep CoCo alive

proxy/api/src/main.rs, proxy/coco/src/peer.rs, proxy/coco/src/peer/run_state.rs
During the great merges of 2020 we went back to the default of
RunConfig, which does not have sync on startup enabled. This behaviour
is desired for proxies running in "production".
=> fix(proxy): reintroduce sync on startup

QA.md, scripts/reset-state.sh
For those unverbesserliche, we also provide a bash script to remove state and config data.
=> docs(qa): advise to use temporary user accounts

proxy/coco/src/peer/sync.rs
Fixes a regression introduced in #944: while syncing, the other end may
not have the URLs we're interested in, or may go away in the middle of
us fetching. We should thus just ignore any errors.
=> fix(proxy): ignore fetch errors in when syncing

proxy/api/src/http/error.rs, proxy/api/src/http/identity.rs, proxy/coco/src/error.rs, proxy/coco/src/lib.rs, proxy/coco/src/state.rs
librad takes care of checking the existence before creation + setting
the rad/self references.
We remove the EntityExists variant from Error and expose the storage
Error upstream so that the consumer can handle cases for special
http rejection.
=> refactor(proxy): clean up init_* functions

ui/Screen/Onboarding/EnterPassphrase.svelte
Contributes to resolving #836 
Adds `Be sure to put this in a safe place!` to the description on the onboarding password screen
=> fix(ui): extend password text

proxy/api/src/error.rs, proxy/api/src/http/control.rs, proxy/api/src/http/error.rs, proxy/api/src/http/identity.rs, proxy/api/src/http/project.rs, proxy/api/src/http/source.rs, proxy/api/src/project.rs, proxy/coco/src/config.rs, proxy/coco/src/control.rs, proxy/coco/src/error.rs, proxy/coco/src/lib.rs, proxy/coco/src/peer.rs, proxy/coco/src/peer/announcement.rs, proxy/coco/src/peer/request.rs, proxy/coco/src/project/create.rs, proxy/coco/src/seed.rs, proxy/coco/src/source.rs, proxy/coco/src/state.rs, proxy/coco/src/state/error.rs, proxy/coco/src/user.rs
Fixes #850 
The aim of the game is to have `Error` enums located next to their module, splitting up the mega enum. Some advantages to this approach:
* This minimises the chance of cross-module interactions since we can't conflate errors of the same domain
* Where the error comes from is more specific, since we would get something like `State(Source(Git(...)))` vs `State(Git(...))`. We know the former is a git related error located in source browsing vs a git related error during state interactions.
=> refactor(proxy): module errors

proxy/api/src/main.rs, proxy/coco/src/peer.rs, proxy/coco/tests/gossip.rs, proxy/coco/tests/replication.rs
As a follow-up to #944, this implements the `Peer` task orchestration using hand-rolled futures, in order to ensure proper lifecycle management of spawned tasks.
=> chore(proxy): attempt 3 at proper async task management

proxy/coco/src/request.rs, proxy/coco/src/request/existential.rs, proxy/coco/src/request/waiting_room.rs
We can utilise serde's macro magic using the `with` and `bound` macros
to tell serde that we'll use the Milliseconds trait for serialisation.
Note that this enforces to use the time types defined in serde_millis
when we want serialise any of these types. Otherwise, we will have to
hand-roll implementations.
=> refactor(proxy): move De/Serialize

proxy/api/src/http/project.rs, proxy/coco/src/control.rs
Fixes #1006
Adds a `POST /track` endpoint that takes a `RadUrn` and `PeerId` as input and tracks the `PeerId` for the given project at `RadUrn`. 
What this PR doesn't do is attempt to add any calls to the front end for this. It's worth waiting for the design of this feature to do that /cc @juliendonck.
=> feat(proxy): track endpoint

proxy/api/src/context.rs, proxy/api/src/http.rs, proxy/api/src/http/control.rs, proxy/api/src/http/error.rs, proxy/api/src/http/identity.rs, proxy/api/src/http/project.rs, proxy/api/src/http/source.rs, proxy/api/src/main.rs
Closes #997 
Can currently only be tested when setting the signer to `None` in `rig()` of `main.rs`
**Open tasks/questions**
=> feat(proxy): Add unsealed guard

proxy/api/src/context.rs, proxy/api/src/http/project.rs
Regression from #992 where the future of the call was not awaited,
unfortunately our tests didn't break.
Refs #984
=> fix(proxy): await request urn

proxy/api/src/http/project.rs, ui/src/api.ts, ui/src/search.ts
Part of #984 
Instead of using POST this change converts the endpoint to PUT to
convey that the operation is idempotent. A new request for an already
requested URN should not lead to an error, instead just a noop and a
friendly message.
=> refactor: move request urn endpoint to PUT

tsconfig.json
Set ES2018 as the target for the typescript compiler. This works because
electron supports this standard and results in less compilation overhead
and smaller/better sourcemaps
=> TypeScript targets ES2018

cypress/integration/onboarding.spec.js, cypress/integration/project_checkout.spec.js, cypress/integration/project_creation.spec.js, cypress/integration/project_source_browsing.spec.js, cypress/integration/user_profile.spec.js
Wrap each spec file in its own context as recommended [here](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Run-all-specs) and [here](https://glebbahmutov.com/blog/run-all-specs/#solution).
Otherwise when clicking the `Run all specs` button the `before` and `beforeEach` blocks of each spec file would get executed in the beginning of the run.
=> fix: "run all specs" from cypress UI

proxy/api/src/main.rs, proxy/api/src/notification.rs, ui/DesignSystem/Component/Sidebar.svelte
When introducing long-running sse subscriptions for notifications the
server stopped responding to shutdown signals. This prevented a proper
reload of the stack, which cypress integration tests depend on. In order
to terminate handlers spinning on notification subscriptions the
shutdown forces a clear of all stored senders.
=> fix(proxy): clean up long-running notifications

proxy/coco/src/state.rs
Since checkout uses `clone` under the hood, it's necessary that we block
on this IO operation. Otherwise we will end up in flakey test hell.
=> fix(proxy): block on checkout

proxy/api/src/http/notification.rs, proxy/api/src/main.rs, proxy/api/src/notification.rs, proxy/coco/src/lib.rs, ui/src/localPeer.ts
Follow-up to #1035 #1046 to streamline the notification infrastructue
and translation of peer events. This is in preparation to surface more
events to give uesrs insight into the operations of their local peers.
=> refactor: improve local peer notifications

proxy/coco/src/request.rs, proxy/coco/src/request/waiting_room.rs
Fixes #1023 
We never persisted the TimedOut state when we encountered one, instead
returning it directly as an error.
This PR fixes that by first persisting the TimedOut state during a
transition and then returning it as an error. We can confirm the
persistence in the test cases for when we reach a timeout.
=> fix(proxy): persist TimedOut state

ui/DesignSystem/Component/TrackToggle.svelte, ui/Screen/Project.svelte, ui/Screen/Project/PeerSelector.svelte
Until we introduce explicit untracking of projects, whenever we show
a project page it is inherently tracked. Therefore the track toggle
should be in tracked state and the unfollow action disabled.
Closes #1045
***
=> fix(ui): always tracked toggle for projects

proxy/coco/src/state.rs, proxy/coco/tests/gossip.rs
We didn't end up using the providers approach. We should remove it as it
isn't needed and we don't want to encourage anyone to use it.
=> refactor(proxy): remove providers

scripts/reset-state.sh
Looks to be a copy-paste error where the same path was deleted twice.
=> fix: correct path in reset script

ui/src/config.ts
This change has the following implications:
- starting a new project without an existing repository will initialise the created repository with a default `main` branch:
- creating a project using an existing repository which doesn't have a `main` branch will fall back to the first branch in the list (`master` won't be selected):
- creating a project using an existing repository which has a `main` branch will pre-select `main` as the default branch:
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1058.
=> refactor(ui): start new projects with a "main" branch

ui/Screen/Profile/Projects.svelte, ui/Screen/UserProfile.svelte, ui/Screen/UserProfile/Projects.svelte, ui/src/__mocks__/api.ts, ui/src/identity.ts, ui/src/project.test.ts, ui/src/project.ts, ui/src/userProfile.ts
The underlying issue was an automatic preloading on store initialisation
which fetched the owners projects. It would override the list of fetched
projects for the accessed user profile. To avoid similar subtle bugs
when building up data to satisfy the screen, all stores for the
UserProfile screen and its fragments are isolated into their own ts file
with a streamlined public api.
Fixes #1100
=> fix(ui): show correct projects for users

proxy/coco/src/peer/run_state.rs
Fixes #1116 
We weren't marking a clone attempt as failed and that means it would
never go back to a Requested state. This change adds handling this case
and extracts out the TimedOut handling into a helper.
=> fix(proxy): handle case for RequestInput::Failed

cypress/integration/project/peer_management.spec.js, ui/DesignSystem/Component/AdditionalActionsDropdown.svelte, ui/DesignSystem/Component/Copyable.svelte, ui/DesignSystem/Component/StyledCopyable.svelte, ui/Modal/ManagePeers.svelte, ui/Modal/ManagePeers/Peer.svelte, ui/Modal/ManagePeers/PeerFollowRequest.svelte, ui/Screen/DesignSystemGuide.svelte
The "Manage remotes" modal now:
- mimics the peer selector for tracked peers exactly
- doesn't show the `Follow` button for our own peer
- truncates all `PeerId`s and makes them copyable
Also fixed a bug where it was not possible to unfollow a tracked peer which is neither a maintainer nor our own peer.
Closes: #1144.
=> fix(ui): make manage remotes modal consistent with peer selector

proxy/coco/src/peer/run_state.rs, proxy/coco/src/request/waiting_room.rs
Fixes #1154 
During gossip announcements of Has, we would always mark the RadUrn as
Found in the WaitingRoom, but the WaitingRoom might not necessarily have
been looking for this RadUrn. So we first check that the WaitingRoom
indeed `has` the RadUrn before continuing on.
=> fix(proxy): check waiting room has urn

cypress/integration/routing.spec.js, cypress/support/commands.js
We now enforce that the requests made in test helpers return with a success status code. Otherwise we throw an error and fail the tests.
This requires us to fix some of the routing tests.
=> refactor(tests): Enforce success responses from test helpers

.buildkite/pipeline.yaml
I’ve properly enabled shared master caches in our CI builds. (Although this option was enabled in `.buildkite/pipeline.yaml` it was not enabled in the buildkite project config). To prevent issues with concurrent master builds we need to restrict concurrency. See
https://github.com/radicle-dev/infra/tree/master/ci#shared-master-cache for details.
=> fix(ci): prevent concurrent builds on master branch

proxy/Cargo.lock, proxy/api/src/http/control.rs, proxy/coco/Cargo.toml, proxy/coco/src/control.rs, proxy/coco/src/lib.rs, proxy/coco/src/project.rs, proxy/coco/src/project/checkout.rs, proxy/coco/src/project/create.rs, proxy/coco/src/state.rs, proxy/coco/src/state/error.rs, proxy/coco/tests/common.rs
With these changes we get some fixes, specifically urn_context.
We also get the changes to have a sub-workspace that is re-exported
as git_ext, and also the very useful macro `reflike!`
=> chore(proxy): update librad deps

cypress/integration/lock.spec.js, ui/Screen/Lock.svelte
Additional change: Persists the passphrase in the unlock input on unsuccessful unlock.
=> refactor(ui): improve lock screen tests

proxy/api/src/http/error.rs, proxy/api/src/http/project.rs, proxy/coco/src/keystore.rs, proxy/coco/src/peer/run_state.rs, proxy/coco/src/project/create.rs, proxy/coco/src/project/create/validation.rs, proxy/coco/src/state.rs, proxy/coco/tests/common.rs
Fixes #1135
Fixes #822 
* Pushed all validation logic into `project::create::validation`
* A `Repo` must be now validated into a `validation::Repository` which has passed the checks
* Then a working copy can be safely set up (we check for the validations again, just to be sure)
=> fix(proxy): extensive validation

proxy/coco/src/git_helper.rs
Ensure we're always running the most recent git remote helper.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1198.
=> fix(proxy): always overwrite git helper with latest one

proxy/api/src/context.rs, proxy/api/src/http.rs, proxy/api/src/http/keystore.rs
We remove the logic that validates and generates auth tokens from the HTTP layer and consolidate it in `api::context`.
=> refactor(proxy): move auth token logic into context

.buildkite/pipeline.yaml
We run the master build on our new `preview` buildkite agent. This allows us to see if this project builds on the new agent. After some time we can then use the new agents to run all the builds and increase the number of parallel builds.
=> chore(ci): run master build on preview agent

proxy/api/src/process.rs, proxy/coco/src/spawn_abortable.rs
Closes #1191
Closes #1208
Only the initial event (set up in the `local_peer_event` endpoint) was sent to the event stream. All subsequent events were not broadcasted since the tasks in `run_rigging` (process.rs) were immediately dropped.
=> fix(proxy): do not drop event tasks

QA.md, cypress/integration/routing.spec.ts, cypress/support/ipc-stub.ts, native/main.ts, ui/Screen/Bsod.svelte, ui/src/error.ts, ui/src/ipc.ts, ui/src/session.ts
Closes #1095
When the proxy crashes or does not start we show `stderr` of the proxy
process.
Follow-up:
- Interlace `stderr` and `stdout` to show the full output.
=> feat(ui): show proxy logs when proxy crashes

ui/Screen/Onboarding.svelte, ui/src/api.ts, ui/src/session.ts
With #1153 the proxy restarts much quicker after the keystore is unsealed or created. This allows us to reduce the number of retries and fail earlier if the proxy does not start properly. (We now wait 5
seconds).
As part of this change we also adjust the signature of `withRetry`. Now the caller is able to control all timing related parameters.
=> feat(ui): reduce number of retries after proxy restart

package.json, yarn.lock
This also makes sure that the twemoji dependency is locked to a single
version, that is because we always need to update our twemoji-svg-assets
dependency in lock-step.
We get:
- https://github.com/twitter/twemoji/releases/tag/v13.0.0
- https://github.com/twitter/twemoji/releases/tag/v13.0.1
Remind everyone to run this after the PR is merged:
```
rm -rf public/twemoji/*.svg
rm -rf node_modules
yarn
```
=> chore(ui): bump twemoji dependency

ui/App.svelte, ui/DesignSystem/Component/Remote.svelte, ui/Screen/Onboarding.svelte, ui/Screen/Profile/Projects.svelte, ui/Screen/UserProfile/Projects.svelte, ui/src/error.ts, ui/src/profile.ts, ui/src/session.ts
This change introduce structured error logging and applies it in a couple of places. Part of #1187.
The design of the `Error` interface is very similar to Rust errors and arises from the following needs:
* A stable identifier for errors (`code`)
* A message we can display to the user (`message`)
* Structured details that provide more information about the error (`details`)
* A stack trace if available (`stack`)
* Layering of error chains (`source`)
~~I’ve decided not to make `code` an enum. Having a centralized place that lists all errors does not help us with debugging. When debugging we need to look at the place where the error originated which can easily be found be grepping for the error code. In addition such a centralized place would make it more cumbersome to add new errors since …
=> feat(ui): introduce structured error logging

ui/Screen/DesignSystemGuide.svelte, ui/Screen/Settings.svelte
Removes some props that were leftover from older iterations from the design system guide and settings page which were causing warnings.
=> fix(ui): remove unused props

ui/Screen/Project/PeerSelector.svelte
Because we can't resolve the profiles of contributors yet (only of the maintainer) from the peerselector, we've decided to move it to isExperimental for now.
Closes #1254
=> fix(ui): move `go to profile` to isExperimental

ui/DesignSystem/Component/Notification.svelte, ui/DesignSystem/Component/NotificationFaucet.svelte
Closes #1266
Adds a max-width to the notifications and truncates the message if it is too long. Applies to all kinds of notifications.
=> fix(ui): truncate notification messages to fit into view

proxy/Cargo.lock, proxy/coco/Cargo.toml
There was an issue in `radicle-surf` where some branches would not parse correctly, for example `xla/handle-disconnect`.
This is now fixed in `surf` and pushed to crates.io as v0.5.1. So I relaxed the versioning in upstream so it's easier to get hot fixes like this in v0.5.
=> fix(proxy): surf branches

ui/src/error.ts
We change the error code `UnexpectedProxyExit` to `BackendTerminated` as
discussed on the docs [1].
[1]: https://github.com/radicle-dev/radicle-docs/pull/21#discussion_r522785330
=> fix(ui): improve error code for backend termination

ui/Screen/Project/PeerSelector.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1289
| content narrower than header | content wider than header|
|---------------------------|-------------------------------|
| ![one](https://user-images.githubusercontent.com/158411/99766929-663af180-2b02-11eb-9aed-3568eacef715.gif) | ![two](https://user-images.githubusercontent.com/158411/99766942-6affa580-2b02-11eb-8a8c-dc7a197c2f23.gif) |
~~Optionally we could add~~ I added a fixed padding to avoid the dropdown from "jumping" when the content is narrower than the header:
| content narrower than header | content wider than header|
|---------------------------|-------------------------------|
| ![pad-one](https://user-images.githubusercontent.com/158411/99767195-ef522880-2b02-11eb-8e30-84eb0ac252b7.gif) | …
=> refactor(ui): remove expand icon from dropdown items

ui/DesignSystem/Component/Header/Large.svelte, ui/DesignSystem/Component/Stats.svelte
This is a workaround for #1223, until we figure out the underlying issue in surf.
- missing branches in project screen
- missing branches in "Following" tab
- all stats available in "Following" tab
- all stats available in project screen
=> fix(ui): don't show stats that equal zero

package.json
This renames the app binary from `radicle-upstream` to `Radicle Upstream`.
The package filename remains unchanged.
Refs: https://github.com/radicle-dev/radicle-docs/pull/26#discussion_r527079630.
=> build: rename binary to "Radicle Upstream"

proxy/coco/src/state.rs
Since #1080 constrainted the peer list correctly we had to fix the
incorrect role assigned. Can't think of a case where the remote peer can
be of type `Tracker` at this point.
Fixes #1297
=> fix(proxy): return tracking remotes as contributor

proxy/coco/src/peer/run_state.rs, proxy/coco/src/peer/run_state/input.rs, proxy/coco/src/peer/subroutines.rs
This is something I discovered while investigating #1279.
`input::Control::CreateRequest` now always holds a response sender instead of it being optional. The `None` case was only used in the tests and the variant is now aligned with the other `input::Control` variants.
This also allows us to simplify the tests. We remove any assertions on the command output being empty,
=> refactor(proxy): simplify `CreateRequest` control input

ui/Screen/Project.svelte, ui/Screen/Project/Source.svelte, ui/Screen/Project/Source/CheckoutButton.svelte, ui/src/project.ts
Make it depend on whether we are a contributor already or not (ie. whether we already have a fork).
Closes #1239 
Looks like this now, if you don't already have a fork (otherwise looks the same as before):
=> refactor(ui): change checkout button copy

.gitignore
We use the `sandbox` for local development artifacts in [`feat/funding`](#975), where it is git-ignored. At the moment, we place a `.local-ethereum-account` in there with the environment dev address in use for development/playing around. Calling it `sandbox` seemed both appropriate and generic enough to use for other needs.
It would be handy to have it already git-ignored on master to avoid having to move it in and out of the repository every time I switch branches.
=> chore: git-ignore ./sandbox

ui/Screen/Bsod.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1337.
For testing use this diff, clicking on any copyable link will open the BSOD:
```diff
diff --git a/native/main.ts b/native/main.ts
index 1b55c15c..4f5dde50 100644
--- a/native/main.ts
+++ b/native/main.ts
@@ -111,6 +111,16 @@ ipcMain.handle(RendererMessage.DIALOG_SHOWOPENDIALOG, async () => {
});
ipcMain.handle(RendererMessage.CLIPBOARD_WRITETEXT, async (_event, text) => {
+  console.log("PROXY_ERRRO sending");
+  windowManager.sendMessage({
+    kind: MainMessageKind.PROXY_ERROR,
+    data: {
+      status: 1,
+      signal: null,
+      stdout: "STDOUT",
+      stderr: "STDERR",
+    },
+  });
clipboard.writeText(text);
});
```
=> fix(ui) fix BSOD overflow scroll bug

proxy/api/src/http/control.rs, proxy/api/src/http/identity.rs, proxy/api/src/http/project.rs, proxy/api/src/http/project/request.rs, proxy/api/src/http/session.rs, proxy/api/src/http/source.rs
We apply the following rules to the order of HTTP routing filters:
1. Path matchers come first
2. Path matchers must be terminated with `path::end()` or `path::tail()`
3. Method matchers come after path matchers
4. State guards (like `with_unsealed_context`) come after method matchers.
This prevents the following issues:
* We always get a 404 when a path does not match. Without the proper ordering we could get a 405 (method not allowed) or a 403 (not authorized) which would mask the fact that the path was wrong.
* We run the expensive state guards at most once per request since the path-method combination is now uniquely matched. Before, if the state guard was at the beginning we would run it for every route that was combined with `or`.
* We enforce exact matches on paths so that we don’t …
=> refactor(proxy): Avoid confusing errors in http route matching

proxy/api/src/http/error.rs, proxy/coco/src/project/create/validation.rs
Fixes #1358 
To ensure that we can add a first commit when creating a project we must
make sure that the user has a git config set up. We check this before
creating a new project and give back an error if it isn't the case.
=> fix(proxy): validate default git config

ui/DesignSystem/Component/Stats.svelte, ui/src/localPeer.ts
We make the stats component reactive so that changes in the props are reflected in the rendered dom.
=> fix(ui): make stats component reactive

DEVELOPMENT.md
Reminds us to update the download links on the radicle.xyz website when a new release is made.
*note:* The link doesn't work right now cause the website hasn't been updated but it will work as soon as we merge.
=> chore: add links update to `DEVELOPMENT.md`

ui/DesignSystem/Component/ConnectionStatusIndicator.svelte, ui/DesignSystem/Component/Sidebar.svelte
This increases the clickable area of sidebar items to the size where the indicator shows up.  (closes #664 and #1296)
=> fix(ui): Increase hit area for sidebar buttons

.buildkite/run.sh
At the moment some of the tests in the proxy test suite may stall (#1378). To avoid the build only failing after 60 minutes we put a timeout on the proxy tests.
=> fix(ci): timeout for proxy tests

cypress/integration/routing.spec.ts, jest.config.js, native/ipc-types.ts, native/main.ts, native/proxy-process-manager.test.ts, native/proxy-process-manager.ts, package.json, ui/Screen/Bsod.svelte, yarn.lock
We change how the proxy process is spawned. Instead of saving all output of the process in a buffer we only save the 200 most recent lines. In addition we forward all of the proxy’s output to the main process output. This allows us to see the proxy logs when starting the app from the terminal.
To implement this we introduce the `ProxyProcessManager` which encapsulates this behavior. The logic for line buffering the output of the process suffers from duplication. I’ve experimented with some abstractions but they were all to complicated and did not add enough value.
Fixes #1359
=> fix(proxy): only save most recent logs from proxy

proxy/coco/src/config.rs
The double sanity check prevented the reconnect behaviour introduced in #1316.
=> fix(proxy): remove seeds guard to enable reconnect

proxy/api/src/process.rs
With the removal of the guard in the disco impl, the implementation
became sensitive to double emission at the start of the stream. As
a broadcast is used, there is an initial value at the start.
=> fix(proxy): avoid double seed emission

DEVELOPMENT.md, builder/entitlements.mac.plist, builder/notarize.js, package.json, scripts/reset-state.sh, yarn.lock
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1306
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1350
TODO:
=> build: automate macOS package notarization

.buildkite/pipeline.yaml, DEVELOPMENT.md, package.json
Don’t build snap images since they are broken. See #1419
=> chore(ci): don’t build snap images since they are broken

ui/Screen/Onboarding/EnterName.svelte, ui/Screen/Onboarding/EnterPassphrase.svelte
Closes #1416
Navigates or refocuses the inputs in the onboarding flow on `enter` on unfocused input. Navigates when all validations pass or focuses on the appropriate input when they fail.
=> feat(ui): extend effect of enter key in onboarding

ui/src/screen/project.ts
If the untracked peer/remote is the currently selected this change
reverts back to the default one, to avoid confusion.
Fixes #1210
=> fix(ui): revert to default after untrack

package.json, yarn.lock
This makes life easier for some downstream packaging tooling (e.g.  yarn2nix)
Signed-off-by: David Terry <me@xwvvvvwx.com>
=> package.json: mark git deps with a git+

.buildkite/run.sh
We’re using the `--ensure-time` option with `cargo test` to notify us when a test takes longer than the specified time. However, this does not abort the test suite and thus does not address #1378. To actually abort the test suite we are using the `timeout` command.
In addition we have the following changes
* We remove the `timeout` command from the lint step. This was committed by me accidently in #1379. We have never experienced issues with clippy timing out.
* We’re replacing the `--ensure-time` option with `--report-time`. We want to know how long tests take but not fail them since we have no expectations for the time they should take.
=> fix(ci): put timeout on proxy tests

ui/DesignSystem/Component/List.svelte
Fixes #1447
Border radius of lists now just handled by the parent with overflow, rather than having border radius on children too.
=> fix(ui): list border overflow (#1447)

DEVELOPMENT.md, QA.md
Trying to strike a balance here between testing everything that is not covered by our test suite and keeping the QA checklist short simple enough to be doable for every release.
This PR:
- adds a release checklist so we don't miss a step
- adds templates for community announcements
- shuffles the QA checklist around so it can be completed in one go without jumping around between sections
**Note:** I left out testing the peer selector and pulling changes from a new remote, because that would need extra coordination and would make the QA process even longer. Hope we can cover this case by tests soon.
Closes: #1345.
=> docs: tidy up release docs

package.json
CI now fails when the rollup build produces warnings.
The motivation for this was a [change][1] that imported a type into a Svelte file. This was accepted by `svelte-check` but made `rollup -c -w` fail. It [produced a warning][2] for `rollup -c`.
[1]: https://github.com/radicle-dev/radicle-upstream/pull/1501/commits/9d05a9c5226a77fc29b7b5907901f50ff4fd9817
[2]: https://buildkite.com/monadic/radicle-upstream/builds/7106#b58d91d2-5a95-4d61-90c6-811b4e88c037/298-325
=> fix(ci): fail after rollup warnings

ui/DesignSystem/Component/SegmentedControl.svelte, ui/Screen/Settings.svelte
We use TypeScript in the settings screen and the `SegmentedControl` component.
We also remove the use of `onMount`. It is not necessary to delay the call to `getVersion` until after the component has mounted.
=> refactor(ui): use TypeScript in settings screen

cypress/integration/onboarding.spec.ts, cypress/integration/project/checkout.spec.ts, package.json, yarn.lock
Update Cypress from v5 to v6. The only breaking change we needed to fix was that the `not.visible` assertion now throws if the element does not exist. We change the affected occurrences to use the `not.exists` assertion.
=> chore(ui): update cypress

ui/DesignSystem/Component/Copyable.svelte, ui/DesignSystem/Component/Notification.svelte, ui/DesignSystem/Component/NotificationFaucet.svelte, ui/Modal/NewProject.svelte, ui/Modal/Search.svelte, ui/Screen/Bsod.svelte, ui/Screen/DesignSystemGuide.svelte, ui/Screen/Project/Source.svelte, ui/src/error.ts, ui/src/localPeer.ts, ui/src/notification.ts
* Notifications can now have multiple actions
* The action divider in notifications now covers the whole notification height. Fixes #1270.
* The `notification.info` and `notification.error` functions now take parameter objects as a single argument instead of multiple arguments. This provides a cleaner API with respect to default values.
* We eliminate the event logic from notifications to simplify the code
=> refactor(ui): notifications with multiple actions

cypress/integration/project/checkout.spec.ts, cypress/integration/project/creation.spec.ts, cypress/support/commands.ts, cypress/tsconfig.json
The TypeScript project configuration for the cypress code now extends the main project configuration to achieve parity. This means that `strict` type-checking is now enabled, which requires some fixes.
=> refactor(tests): strict type-checking for cypress code

DEVELOPMENT.md
We update the documentation for publishing AppImage releases. This works now after adjusting the URL. We also improve the script slightly so that it can be just copy-pasted.
=> fix(ci): update release publishing documentation

cypress/integration/project/source_browsing.spec.ts
In some parts of the test we were missing proper assertions. We replace occurrences of `.pick(..).contains(..)` with `.pickWithContent(..).should('exist')`. This is preferable to `.pick(..).contains(..).should('exist')` since the latter does not respond to DOM updates as expected. (I can elaborate if necessary.)
=> fix(test): properly assert in tests

proxy/coco/src/project/create/validation.rs, ui/src/search.ts
Fixes https://github.com/radicle-dev/radicle-upstream/issues/1560
For the existing remote, I realised that the URL won't parse full-stop. So I decided to handle this case specifically by renaming the existing remote, thus preserving the reference data. Then we create a fresh `rad` remote. A user can then copy any of their references over from `temp_rad` and remove it when they're done.
~For the search box, I'm not sure how to detect if it was an old URN and give a specific message in that case. So what I did here was give a small prompt that it might be an old URN. Maybe we could try document the differences in the community post.~
=> fix(proxy): urn warnings for upgrade

ui/Screen/Profile/Funding.svelte
Currently, when on a reduced vertical viewport, the transaction center overlaps elements of the Support page:
We fix that by adding an appropriate `padding-bottom` that grants enough scrolling space at all times:
=> fix(ui): avoid tx center from overlapping support elements

cypress/integration/settings.spec.ts
We make the app version tests more robust to prevent flaky test failures.
The basic idea is to ensure that we dismiss the correct notifications instead of dismissing one notification twice. We also play around with the timing parameters.
=> fix(tests): fix flaky version tests

ui/src/session.test.ts, ui/src/session.ts
We allow all valid DNS names in the seed node address validation.
Note that the validation is in-fact too permissive since it allows `-`, `-.-`, `123` and other invalid names. Take all edge cases into account would increase the complexit of the regexp though.
Fixes #1618.
=> fix(ui): more permissive seed validation

cypress/support/nodeManager.ts
When running the `networking.spec.ts` tests locally, the test timeouts on executing `createCommit`. This fixes the problem.
Thanks to @geigerzaehler for the suggestion!
Signed-off-by: Merle Breitkreuz <merle@monadic.xyz>
=> fix: local networking test timeout

native/main.ts, package.json
A two changes that improve the path handling when the app starts
* `RADICLE_UPSTREAM_PROXY_PATH` is now relative to the working directory instead of the source file. Now the user can set this properly without knowing the location of the file.
* We create the electron storage directory recursively so that it works even if `RAD_HOME` does not exist yet.
=> refactor(ui): electron start path improvements

ui/src/session.test.ts, ui/src/session.ts
We fix an exception thrown by `waitUnsealed` if the session is already unsealed. Before, if `sessionStore` would hold an unsealed session, the callback to `subscribe` was called *synchronously* and calling `unsubscribe()` would throw because it was not yet assigned.
=> fix(ui): Fix waitUnsealed when session already unsealed

package.json
Before it was possible to run cypress tests before the bundle was build which resulted in the app not working.
=> fix(tests): cypress tests wait until bundle is build

cypress/integration/networking.spec.ts, cypress/integration/project/checkout.spec.ts, cypress/integration/project/creation.spec.ts, cypress/integration/settings.spec.ts, cypress/support/ipc-stub.ts, native/ipc-types.ts, native/main.ts, native/preload.d.ts, ui/src/ipc.ts
We make the IPC interface between the electron main process and the renderer generic and type-safe. This reduces boilerplate and increases robustness.
=> refactor(ui): make ipc interface generic and type-safe

cypress/integration/networking.spec.ts, cypress/plugins/nodeManager/plugin.ts, cypress/plugins/nodeManager/shared.ts, cypress/support/commands.ts, cypress/support/nodeManager.ts
Before, each node had its own temporary directory `cypress/workspace/<uuid>` where `uuid` was different for each node. This made debugging the node state (in particular their monorepos) difficult.
With this change node data is located in the per-test temporary directory created by `withTempDir`.
=> refactor(test): make node data directories discoverable

CODEOWNERS, scripts/release.ts, scripts/set-latest-release.ts, tsconfig.json, tsconfig.scripts.json
We remove the separate `tsconfig` file for scripts and add the configuration under the `ts-node` key to `tsconfig.json`.
=> refactor: remove tsconfig file for scripts

proxy/api/src/context.rs, proxy/api/src/http/identity.rs, proxy/api/src/http/project.rs, proxy/api/src/http/project/request.rs, proxy/api/src/http/session.rs, proxy/api/src/http/source.rs, proxy/api/src/process.rs, proxy/coco/src/config.rs, proxy/coco/src/lib.rs, proxy/coco/src/peer.rs, proxy/coco/src/peer/control.rs, proxy/coco/src/peer/run_state.rs, proxy/coco/src/peer/run_state/input.rs, proxy/coco/src/peer/subroutines.rs, proxy/coco/tests/common.rs, proxy/coco/tests/gossip.rs, proxy/coco/tests/replication.rs, proxy/coco/tests/source.rs
To not implode the entire networking machinery on an accept error, we
follow suit with the example of the link seed code and put the bind and
accept in a loop. Only when an error on bind is encountered it's
terminate.
=> chore: put the peer in a loop

package.json, scripts/install-twemoji-assets.sh, yarn.lock
Instead of using our own `twemoji-svg-assets` package we download the assets directly as part of the `postinstall` scripts.
This has two advantages: First, we don’t need to maintain a separate package. Second, this removes a blocker of the [upgrade to Yarn v2][yv2]. Our `twemoji-svg-asstest` package copied the assets as part of *its* [post-install script][pis]. This only works under certain assumptions about the directory layout which don’t hold for Yarn v2.
[pis]: https://github.com/radicle-dev/twemoji-svg-assets/blob/master/package.json#L10
[yv2]: https://github.com/radicle-dev/radicle-upstream/issues/1687
=> refactor(ui): download twemoji assets directly

.buildkite/Dockerfile, .buildkite/pipeline.yaml, package.json
Before `run-p --race` did not kill processes on CI and we had to to this manually. The reason for this behavior was that the `ps` binary was not installed. We fix that by installing the `procps` package. Having `ps` in the image is also useful for debugging.
We also take the opportunity to clean up the Dockerfile a bit.
* We move the `build-essential` package to the top and stop listing its dependencies (like gcc) explicitly.
* We install `yarn` via `npm` instead of a debian package
=> fix(ci): run-p --race kills process

cypress/support/nodeManager.ts
We provide better isolation for git commands run in tests. This fixes the tests for developers who have GPG configured. Backports #1631
=> fix(test): isolate git config in cypress tests

rollup.app.js, rollup.electron.js
Before, the `noEmitOnError` option for the rollup typescript plugin was inadvertently set to `true` in development mode. This lead to the watcher exiting when a type error was encountered and this tore down the whole app. We always fallback to the default `false` now.
=> fix(build): don't crash app on typescript error

.buildkite/run.sh
As a follow-up to #1707 we don’t clean the cache folder on the macos agent. The agent does not provide the GNU version of the `df` utility and does not support the `--output` option.
=> fix(ci): don’t clean free cache on mac agent

proxy/coco/src/peer.rs, proxy/coco/src/peer/subroutines.rs
We replace the custom `Future` implementation for `Subroutines` with a simple `run()` function that uses `futures::select`. One important consequence is that now `Subroutines::inputs` and `Subroutines::pending_tasks` are polled fairly. Before `Spending_tasks` was preferred and we tried to drain it which could lead to a delay in the handling of `inputs`. (This could be the cause for #1378.)
=> refactor(proxy): fair select on subroutines

builder/notarize.js
Fixes a regression introduced in https://github.com/radicle-dev/radicle-upstream/commit/4ab47ce13bde63c3d6fb7122936002a93d045253.
| Before | After |
|--------|------|
| <img width="661" alt="Screenshot 2021-03-30 at 10 59 12" src="https://user-images.githubusercontent.com/158411/112968137-49679800-914c-11eb-8c06-56c9ed31232f.png"> | <img width="619" alt="Screenshot 2021-03-30 at 10 59 17" src="https://user-images.githubusercontent.com/158411/112968140-4a98c500-914c-11eb-9f6a-9b1c410e52d5.png"> |
=> fix(build): fix macOS notarization bundle identifier

scripts/reset-state.sh
Before Upstream 0.2.0 radicle-link used a different location to store its data,
since all our documentation links to the `reset.sh` script on the `master`
branch of this repository, the script wouldn't reset all the state leading to
the following error:
```
{
"code": "create-identity-failed",
"message": "Could not create identity",
"details": {
"handle": "rudolfs"
},
"source": {
"code": "UnknownException",
"message": "A key already exists",
"details": {
"message": "A key already exists",
"variant": "KEY_EXISTS"
}
}
}
```
With this fix we allow users to reset any Upstream version.
=> fix: make reset script backwards compatible

proxy/coco/src/source.rs, ui/src/source.ts
We remove the `branch` field from the `Commit` object returned by the `source/commit` endpoint. This field was unused and led to panics when a commit was not part of a branch. This case was triggered by the merge request work.
=> refactor(proxy): remove `branch` from commit info

proxy/api/src/identifier.rs, proxy/api/src/identity.rs, proxy/api/src/lib.rs, proxy/coco/src/lib.rs
I found the identifier module lying around in coco. I don't think it
needs to be there so I'm moving to api for now.
Signed-off-by: Fintan Halpenny <fintan.halpenny@gmail.com>
=> move identifier

.buildkite/pipeline.yaml
Use the new ci script `ci/run.sh` also on the MacOS buildkite agent
=> fix(ci): use new ci script on mac os agent

ui/Screen/Funding/Pool/Outgoing/Support.svelte, ui/Screen/Project.svelte
Whenever we call `Store.subscribe` in a component we ensure that we unsubscribe when the component is destroyed. In `Screen/Project` this created particular issues where the current project page refreshed even if only a previously visited received an update.
=> fix(ui): don't leak store subscriptions

cypress/integration/networking.spec.ts, cypress/plugins/nodeManager/plugin.ts, cypress/support/nodeManager.ts, package.json, yarn.lock
We generalize the `nodeManager.createCommit` command to `nodeManager.exec` to support other commands in the merge request tests.
This change required us to persist the credential helper setting. We accomplish this by writing the setting to `.gitconfig` in the node’s home directory. We use the same mechanism to write user data got `.gitconfig` which eliminates the need to specify those explicitly every time.
=> feat(test): reusable `nodeManager.exec` command

.github/workflows/build.yaml
We fix a typo in the expression that checks whether we want to run Github CI.
=> fix(ci): only run github ci for external contributors

ui/Screen/Project/Source.svelte, ui/Screen/Project/Source/MergeRequest.svelte, ui/Screen/Project/Source/MergeRequestList.svelte, ui/Screen/Project/Source/MergeRequestLoaded.svelte, ui/src/path.ts, ui/src/project/mergeRequest.ts, ui/src/screen/project/source.ts
Explicitly load the merge request details instead of partially getting them from the query string and partially through `fetchMergeRequestCommits`.
=> Load merge request details

ci/run.sh
Replace the deprecated rustdoc lint `intra-doc-link-resolution-failure` with its new name.
=> fix(ci): replace deprecated rustdoc lint

proxy/api/src/http/identity.rs, proxy/api/src/identity.rs, proxy/api/src/session.rs, proxy/coco/src/state.rs
Part of https://github.com/radicle-dev/radicle-upstream/issues/965. Adds an API endpoint for updating the user payload. This allows updating the ethereum claims and as a byproduct also changing the user handle.
=> feat(proxy): add PUT identity metadata endpoint

cypress/support/commands.ts, package.json, ui/src/api.ts, ui/src/identity.ts, ui/src/proxy/control.ts, ui/src/proxy/fetcher.ts, ui/src/proxy/identity.ts, ui/src/proxy/index.ts, ui/src/proxy/settings.ts, ui/src/session.ts, ui/src/settings.ts, yarn.lock
We introduce the `ui/src/proxy` module that provides checked, reusable access to the proxy HTTP. It’s intended to supersede `ui/src/api` in the future.
We gain the following advantages
* We separate stateful code from the stateless proxy API code (e.g. in `ui/src/session`)
* Response payloads are validated against TypeScript types with `zod`.
* We can reuse the proxy client in the cypress test commands.
* Provide an foundation to extend the proxy client with more APIs.
=> refactor(ui): introduce proxy api client

ui/src/identity.ts, ui/src/proxy/identity.ts
We fix a conflict between #1756 and #1712 and add the `ethereum` field for identities to the UI types and parse it properly.
=> fix(ui): parse ethereum field of identity in ui

ui/src/session.ts
We eliminate the indirection created by events from `src/ui/session.ts` to streamline the code and make it more readable.
=> refactor(ui): eliminate event indirection from session.ts

cypress/support/commands.ts
We ensure that cypress waits for a test project to be created before it continues. Otherwise tests may fail.
=> fix(tests): wait for test project to be created

cypress/integration/project/follow.spec.ts, ui/Modal/Search.svelte
Pressing the "enter" key after pasting a Radicle ID into the search
input will, depending on whether the project is already followed or not,
either open the project screen or follow the project.
https://user-images.githubusercontent.com/158411/114216463-3bddb980-9967-11eb-9a9c-e586d6c5f447.mov
=> feat(ui): handle "enter" hotkey in search modal

Cargo.lock, proxy/api/Cargo.toml, proxy/coco/Cargo.toml
Update to latest radicle-link.
Fixes https://github.com/radicle-dev/radicle-upstream/issues/1763.
=> Bump radicle-link

cypress/integration/deep_linking.spec.ts, native/index.ts, native/ipc-types.ts, native/nativeCustomProtocolHandler.test.ts, native/nativeCustomProtocolHandler.ts, package.json, ui/App.svelte, ui/Modal/Search.svelte, ui/src/customProtocolHandler.ts, ui/src/error.ts, ui/src/ipc.ts, ui/src/modal.ts, ui/src/search.ts
This PR implements the simplest possible deep-linking support. It's based on this [community discussion](https://radicle.community/t/opening-upstream-via-links-on-the-web/1856). Implementing a parser/router for the [proposed URL scheme](https://github.com/radicle-dev/radicle-decisions/pull/10) is left as a follow-up for when we all agree on the scheme. For now the parser just looks for the first `Radicle ID` in the URI and shows the search screen with the input field pre-filled with that URI.
Refs https://github.com/radicle-dev/radicle-upstream/issues/1512
Refs https://github.com/radicle-dev/radicle-decisions/pull/10
Refs https://github.com/radicle-dev/radicle-docs/pull/126
Test this from a browser:
```html
<a href="radicle://link/v0/rad:git:hnrkjm5z3rwae9g3n6jhyo6kzh9eup5ku5odo">radicle:/ …
```
=> feat(ui): open upstream via a custom protocol

package.json, yarn.lock
Perform a major upgrade of Electron to v12. I’ve reviewed the
[changelog][1] and we have addressed the change to `contextIsolation`
in #1693. There are no other relevant changes.
[1]: https://www.electronjs.org/releases/stable#breaking-changes-1200
=> chore: major upgrade of electron to v12

package.json, ui/DesignSystem/Component/HorizontalMenu.svelte, ui/DesignSystem/Component/Sidebar.svelte, ui/Hotkeys.svelte, ui/Screen/Profile.svelte, ui/Screen/Project/Source.svelte, ui/src/menu.ts, ui/src/path.ts, ui/src/screen/project/source.ts, yarn.lock
We replace the incorrectly used `patch.active` function. Whenever this function was used it was called with a _rendered_ path like `/projects/rad:git:123` instead of a pattern. The implementation however interpreted that path as a pattern and passed it to `regexparam`.
This approach worked as long as no `?` was contained in the path passed to `path.active`. In my case I added a horizontal menu item where the `href` field looked like `/foo/bar?filter=true`. This `href` field is used as the `path` argument and the `?` is treated as a special character. This resulted in `path.active(href, href)` returning false.
The purpose of detecting whether a certain path is active can be more easily achieved by comparing the rendered path with `$location`. For the “loose” match mode supported by …
=> fix(ui): replace `path.active`

ui/DesignSystem/Component/Remote.svelte, ui/Modal/NewProject.svelte, ui/Screen/Onboarding.svelte, ui/Screen/Project/Source.svelte, ui/src/customProtocolHandler.ts, ui/src/error.test.ts, ui/src/error.ts, ui/src/profile.ts, ui/src/project.ts, ui/src/remote.ts, ui/src/screen/project.ts, ui/src/screen/project/source.ts, ui/src/search.ts, ui/src/session.ts, ui/src/transaction.ts, ui/src/userProfile.ts, ui/src/wallet.ts
* Make `Error` a class instead of an interface. This means that we get stack traces whenever an error is created. This allows us to trace the sources of errors more easily. Since `Error` is also a subclass of the built-in JS `Error` we can also `throw` instances of `Error` now.
* Introduce `error.fromUnknown` as a replacement for `fromException`. `fromException` was used `try/catch` blocks to turn a built-in JS Error into our error. It is not guaranteed though that the error from a catch block is an instance of the built-in Error so we also need to cover that case.
* We call `event.preventDefault()` on the global handlers to avoid reporting errors to the console twice.
* We log error details and source to the console along with the stack trace.
=> feat(ui): improve error handling

native/index.ts
Unfortunately [`app.getVersion()`](app.getVersion()
) only returns the app's version when it is bundled and run in production. In dev mode it returns Electron's version.
|before|after|
|------|-----|
| <img width="1552" alt="Screenshot 2021-04-14 at 17 39 13" src="https://user-images.githubusercontent.com/158411/114739147-ea5b7300-9d48-11eb-9f11-13b75cee6852.png"> | <img width="1552" alt="Screenshot 2021-04-14 at 17 39 39" src="https://user-images.githubusercontent.com/158411/114739185-f34c4480-9d48-11eb-84c6-42525803e089.png"> |
=> chore(ui): show version and latest commit sha in dev mode

ci/run.sh
This PR moves notarization credentials from `/usr/local/etc/buildkite-agent/hooks` to the macOS keychain.
Refs https://github.com/radicle-dev/radicle-upstream/issues/1530.
A successful test build: https://buildkite.com/monadic/radicle-upstream/builds/8581#c39e7bdd-0260-4fdc-bce2-8b45c4fb5c99.
=> ci: get notarization secrets from keychain

cypress/empty.html, cypress/support/commands.ts, package.json, yarn.lock
Since the crashes on Cypress v7 have been fixed (#1752) we can update it. I’ve revied the [changelog][1]. The only change affecting us is that uncaught exceptions will result in test failures. This caused issues when we reset the proxy at the start of a test while the app from the previous test was still loaded in the window. We fix this by unloading the app before we reset the proxy.
Fixes #1752
[1]: https://docs.cypress.io/guides/references/changelog#7-0-0
=> chore: update cypress to v7

ui/DesignSystem/Component/SourceBrowser/History.svelte, ui/src/screen/project/source.ts, ui/src/source.ts
In preparation for patches we move the grouping of commits out of `source.fetchCommits` and closer to the UI. This allows us to also obtain ungrouped commits from `fetchCommits` which is needed for patches.
=> refactor(ui): explicit grouping of commits

ui/App.svelte, ui/App/TransactionCenter.svelte, ui/DesignSystem/Component/ModalOverlay.svelte, ui/DesignSystem/Component/Sidebar.svelte, ui/Hotkeys.svelte, ui/Modal/NewProject.svelte, ui/Modal/Search.svelte, ui/Screen/Funding/LinkAddress.svelte, ui/Screen/Funding/Pool.svelte, ui/Screen/Funding/Pool/Outgoing/GetStarted.svelte, ui/Screen/Funding/Pool/Outgoing/Support.svelte, ui/Screen/Profile/Following.svelte, ui/Screen/Profile/Projects.svelte, ui/Screen/Profile/ProjectsMenu.svelte, ui/Screen/Project.svelte, ui/Screen/Settings.svelte, ui/src/customProtocolHandler.ts, ui/src/modal.ts, ui/src/path.ts, ui/src/wallet.ts
While working on the [orgs feature](https://github.com/radicle-dev/radicle-upstream/pull/1813) I bumped into the problem that I couldn't access the session context in a modal and there was no way to pass props to modals. This refactoring addresses that problem.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1629.
=> Improve modal architecture

ui/Screen/Onboarding/EnterPassphrase.svelte
Possibly a regression from: https://github.com/radicle-dev/radicle-upstream/commit/c1f79c62d0059e10d26cf835d5c9bdb97c7cd0b2.
Fixes this:
```
cached modules 7.13 MiB (javascript) 1.71 KiB (runtime) [cached] 1077 modules
./ui/Screen/Onboarding/EnterPassphrase.svelte 18.4 KiB [built]
WARNING in ./ui/Screen/Onboarding/EnterPassphrase.svelte 516:2-17
export 'ValidationState' (imported as 'ValidationState') was not found in '../../src/validation' (possible exports: ValidationStatus, createValidationStore, getValidationState)
@ ./ui/Screen/Onboarding.svelte 35:0-66 126:23-38 566:2-17
@ ./ui/App.svelte 49:0-52 370:17-27 413:2-12
@ ./ui/index.ts 1:0-31 2:16-19
```
=> chore(ui): fix typescript warning

ui/index.html
Removes the following warnings from the CI console output:
```
[4936:0422/071855.175313:INFO:CONSOLE(0)] "A preload for 'http://localhost:44433/public/fonts/Inter-Bold.otf' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.", source: http://localhost:44433/public/index.html (0)
```
=> chore(ci): get rid of warnings about fonts

public/global.css, public/typography.css, ui/DesignSystem/Component/SegmentedControl.svelte, ui/DesignSystem/Component/Wallet/Panel.svelte, ui/Screen/DesignSystemGuide.svelte
In most places we don't want to have contextual alternates enabled.
This way we can selectively enable them where necessary and avoid
missing some spots where they should have been disabled.
=> style(ui): disable contextual alternatives by default

package.json, tsconfig.json, ui/DesignSystem/Component/SourceBrowser/FileView/Blob.svelte, ui/DesignSystem/Component/SourceBrowser/FileView/Root.svelte, ui/DesignSystem/Component/SourceBrowser/RevisionSelector/Entry.svelte, ui/src/screen/project/source.ts, webpack.config.ts, yarn.lock
We use TypeScript path mapping to allow absolute imports of the `ui`
folder. I’ve converted some files to the new style to showcase this.
Fixes #734
=> refactor(ui): tsconfig path mapping for absolute imports

.buildkite/pipeline.yaml, .github/workflows/build.yaml, ci/run.sh, cypress/integration/networking.spec.ts, cypress/plugins/nodeManager/plugin.ts, cypress/support/commands.ts
We store the output of nodes in tests in files instead of printing it to stdout. This declutters the test output and makes it easier to inspect the logs, especially on CI. On CI we upload the logs as artifacts.
To make it easy to find the logs we adjust the function that creates temporary directories so that it uses the test name instead of a UUID.
You can see this in action on [buildkite](https://buildkite.com/monadic/radicle-upstream/builds/8607#d7f9ce8d-b212-4eca-ab09-d44a2860c705) and [Github Actions](https://github.com/radicle-dev/radicle-upstream/actions/runs/755714868).
**Open Question**: Should we also send the logs to stdout when developing locally with `yarn test:integration:debug`?
=> feat(test): store test node logs in file

cypress/integration/search.spec.ts, ui/Modal/Search.svelte
Hitting “enter” in the search dialog only triggers a follow if we know whether the project has been found or not. It doesn’t trigger when we’re still fetching the search result.
We also adapt the tests so that we wait for the search result to be present.
=> fix(ui): search enter key follow only when fetched

ui/DesignSystem/Component/ProjectList.svelte, ui/Modal/NewProject.svelte, ui/Screen/Profile/Following.svelte, ui/Screen/Project/Source.svelte, ui/src/profile.ts, ui/src/project.test.ts, ui/src/project.ts, ui/src/proxy/index.ts, ui/src/proxy/project.ts, ui/src/screen/project.ts, ui/src/userProfile.ts
We add an `Client` to interact with the project API of the proxy and use this throughout the codebase.
=> refactor(ui): add project proxy client

cypress/integration/project/checkout.spec.ts, cypress/integration/project/creation.spec.ts
We eliminate unnecessary calls to `cy.wait()`. In most places the call was just copied over from other tests and there was never a need for the wait. (The comment attached to `cy.wait()` makes this clear.)
In the only place where it really was required to run an assertion we replace `.then()` with `.should()`. This will rerun the assertion if it failed until it times out. This is more efficient than waiting.
=> fix(tests): eliminate unnecessary waits

proxy/coco/src/peer/announcement.rs
We need to qualify our announcements with the `refs/` prefix so that
they don't get mistintrepeted on the other side of the wire.
Signed-off-by: Fintan Halpenny <fintan.halpenny@gmail.com>
=> fix(proxy): qualify announcement

cypress/integration/project/source_browsing.spec.ts, proxy/coco/src/source.rs, ui/Screen/Project/Source/Commit.svelte, ui/src/source.ts
The API now provides the branch a commit belongs to. This partially reverts #1717.
The issue was not discovered because of disabled type checking due to #1798. We address this by not using the `Remote` component
The motivation for #1717 was to gracefully handle commits without branches and not panic. We accomplish this by returning the (possibly empty) list of all branches and only showing the first branch (if present) in the UI.
Fixes #1793
=> fix(ui): display branch a commit belongs to

ui/DesignSystem/Component/SidebarLayout.svelte, ui/Screen/Profile.svelte, ui/Screen/Profile/Following.svelte, ui/Screen/Profile/Projects.svelte, ui/Screen/Project.svelte, ui/Screen/Settings.svelte, ui/src/error.ts, ui/src/session.ts
We make acquiring the unsealed session from the context more robust. This was inspired by [comments on #1828][1].
* We stop hardcoding the `session` string into the context
* Instead of using type assertion which don’t fail at runtime we throw an error. If a session is not unsealed this will make it easier to locate the cause.
[1]: https://github.com/radicle-dev/radicle-upstream/pull/1828#discussion_r620346071
=> fix(ui): more robust session context

ui/src/error.ts, ui/src/localPeer.ts, ui/src/proxy/fetcher.ts
We improve the reporting of errors when parsing the proxy response fails.
* We make the `message` and `stack` properties of `Error` enumberable so that they are part of the error payload that is copied to the clipboard.
* We wrap `zod.Schema.parse` so that we can attach information about the requests to the error that is thrown.
=> feat(ui): improve error reporting for parse failures

ui/src/profile.ts, ui/src/proxy/project.ts
* Fix the schema required by the `projects/failed` endpoint.
* Don’t crash the whole app when fetching the list of failed projects fails.
=> fix(ui): properly handle failed project

scripts/set-latest-release.ts
We forbid caching the latest release document so that app users are informed immediately about new releases.
We also use `execa` instead of `child_process.spawnSync` to run commands. `execa` will throw if the command fails.
=> fix(dev): don’t cache latest release information

ci/run.sh
Some files in the cache may be write protected so we need to force the removal. Otherwise the build stalls.
=> fix(ci): force removal of cache directory on cleanup

package.json, ui/src/attestation/contract.ts, ui/src/funding/contract.ts, ui/src/funding/daiToken.ts, ui/src/funding/pool.ts, ui/src/wallet.ts, yarn.lock
- Switch from polling for the pool state to listening to the pool events
- The same for Dai token
- Stop querying for contract constants, instead have them hardcoded
- Fix unwatching of the attestation contract
=> Reduce number of requests to an Ethereum client

ui/DesignSystem/Component/ConnectionStatusIndicator.svelte, ui/src/localPeer.ts
We fix an issue where the remote status indicator vanished when the user navigated to the settings page.
The issue was caused by the `remote` store used to hold the status resetting it’s internal state when the sidebar was re-rendered.
Instead of relying on the remote store with this side-effect we use a simple writable svelte store.
=> fix: remote status indicator vanishing

ui/src/profile.ts, ui/src/remote.ts
* Remove unused `chain()`
* Eliminate `filter` argument from `fetch`. This can be more easily accomplished on the caller side.
=> refactor: clean up remote store APIs

ui/Screen/NetworkDiagnostics.svelte, ui/Screen/NetworkDiagnostics/ConnectedPeers.svelte, ui/Screen/NetworkDiagnostics/WaitingRoom.svelte
Just added some basic padding to the screen, still left it full width.
@rudolfs is there a way to not show the shortcut?
=> style(ui): add basic padding to network diagnostic screen

cypress/integration/project/patches.spec.ts, cypress/support/commands.ts, ui/DesignSystem/Component/SegmentedControl.svelte, ui/Screen/Project/Source.svelte, ui/Screen/Project/Source/PatchList.svelte, ui/src/screen/project/source.ts
We subscribe to the `ProjectUpdated` events to show new patches in the list view without reloading the page. The patches counter in the horizontal menu bar is also updated. Note that the event is currently only triggered for changes coming from other remotes, so updating the list when the user is pushing a patch themselves has to be done in a separate PR.
The following is an example of a `ProjectUpdated` event triggered by a remote pushing a new patch `feature-1`
```
{
provider: "hyys5xxamaizo7nxbhrxsjkpwh385mabea8uxy3zn1kzmks5jqemj4" 
type: "projectUpdated" 
urn: "rad:git:hnrkbpzranjs7kbn45zxfyborhibcugrbyeio/tags/radicle-patch/feature-1"
}
```
=> Reactive patches list

ui/Screen/Project.svelte, ui/src/screen/project.ts
Before, the functions `refresh` and `fetchPeers` used exactly the same code.
=> refactor: eliminate duplicate code in projects

cypress/integration/shortcuts.spec.ts, cypress/support/commands.ts, cypress/support/index.ts
We’re running into a [cypress issue][1] where the app from a previous tests still runs while a second test is started. When the cookies are cleared to prepare the second test the app from the first test may error because the authentication token is invalid.
To work around this problem we unload the app after a successful test run.
[1]: https://github.com/cypress-io/cypress/issues/15247
=> fix(tests): unload app when test is successful

ui/src/wallet.ts
Before this change we would never clear the interval that polls for account data. Since this interval is created whenever the ethereum environment is changed every change would register another interval. We would end up with one poll request for every environment change.
=> fix: don’t leak ethereum account polls

ui/src/wallet.ts
Before, on every page navigation all views would unsubscribe from the wallet store and then subscribe again when the new page was rendered. This resulted in the wallet reconnecting and loading all its data.
=> fix: don’t destroy wallet when all views unsubscribe

.buildkite/pipeline.yaml, DEVELOPMENT.md, ci/Dockerfile, package.json
* Remove references to unused build prerequisites (libnettle, libssl, clang)
* Simplify section in `DEVELOPMENT.md`. We only link to prerequisites and don’t provide detailed instructions for the different platforms. We can assume that the links provide enough documentation.
=> chore(build): fix build prerequisites

DEVELOPMENT.md, cypress/plugins/nodeManager/plugin.ts, native/index.ts, proxy/api/src/process.rs, scripts/env
* Running Uptream in development mode uses `sandbox/rad_home` from the repo as `RAD_HOME`.
* We don’t install `git-remote-rad` in development mode anymore
* We provide a script that makes `git-remote-rad` available in dev mode and sets `RAD_HOME`
=> dev: isolate development environment

ui/Screen/Onboarding/Success.svelte
Fixes a regression discovered during [0.2.6 QA](https://github.com/radicle-dev/radicle-upstream/issues/1950).
=> hotfix: show wallet only in dev mode when pressing the enter key

scripts/ethereum-dev-node.ts
We avoid `yarn run` in the ethereum dev node script so that `ganache-cli` is properly killed when an error occurs.
=> fix(dev): avoid yarn run to properly kill process

.eslintrc.js, ui/src/modal.ts, ui/src/notification.ts, ui/src/updateChecker.ts, ui/src/wallet.ts
We disable the lint that complains about empty functions.
This is achieved by removing the override for typescript files so that extending the override configuration with the rules from `@typescript-eslint/recommended` doesn’t override the top-level rules that already allow empty functions.
=> fix(dev): allow empty function lint

jest.config.js
We set the `moduleNameMapper` option for Jest to match the `paths` option from `tsconfig.json` so that we can use absolute imports also in modules required by Jest.
=> fix(dev): jest module name mapping for TS paths

FUNDING.md, ui/DesignSystem/Component/WalletStatusIndicator.svelte, ui/src/attestation/contract.ts, ui/src/error.ts, ui/src/ethereum.ts, ui/src/funding/contract.ts, ui/src/funding/daiToken.ts, ui/src/settings.ts, ui/src/wallet.ts
Backporting these changes from the [orgs](https://github.com/radicle-dev/radicle-upstream/pull/1813) PR to make it easier to review.
We'll need the Rinkeby testnet to test Orgs and Gnosis Safe functionality and Mainnet for our production builds.
=> feat(ui): add Rinkeby testnet and Mainnet

ui/Modal/NewProject.svelte, ui/Screen/Lock.svelte, ui/Screen/Onboarding.svelte, ui/Screen/Project/Source.svelte, ui/src/screen.ts
* We remove `screen.lock()` and `screen.unlock()` and replace it with `screen.withLock()`. This makes it impossible to forget to unlock.
* We fix a race condition when two actions are run with a lock. Before, the first action that would finish would unlock the screen. Now, we unlock only after all actions have finished.
=> fix: prevent lock race condition

ui/src/config.ts, ui/src/error.ts
We update the `config` and `error` modules so that they can be required (transitively) in tests run by Jest.
=> fix(dev): allow more modules to be required in jest tests

ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte, ui/src/project.ts, ui/src/screen/project.ts, ui/src/screen/project/source.ts
Two commits that extract presentational logic from screen modules so that they can be reused without relying on the screen modules.
See the commits for details.
=> Extract presentation logic from screen modules

ui/DesignSystem/Component/SourceBrowser/CommitTeaser.svelte
If the message in a commit teaser is too large we make it overflow. This prevents the author and date on the right from being pushed outside of the commit teaser container.
We also use auto margins instead of `justify-content: flex-end` to push the box to the right.
=> fix: commit teaser message overflow

ui/src/api.ts, ui/src/mutexExecutor.test.ts, ui/src/mutexExecutor.ts, ui/src/proxy/index.ts, ui/src/router/index.ts, ui/src/screen/project.ts, ui/src/sleep.ts
We introduce `MutexExecutor` that allows us to abstract over behavior were we need to abort previous requests issued by the user. We apply this abstraction in `ui/src/screen/project.ts` where it simplifies the code significantly.
The abstraction can also be used in other places like `ui/src/screen/project/source.ts` and the upcoming changes to the router.
=> refactor: mutex executor to manage concurrent fetches

ui/src/error.ts
We make the `code` property passed to errors optional. This makes it easier to add new errors (which happens frequently) because we don’t need to add it to a global error registry.
Error code’s are beneficial when the cause of the error cannot be deduced from the message or the stack which rarely is the case, or if we want to match on a certain type of error.
=> refactor: make error code optional

ui/src/org.ts, ui/src/session.ts, ui/src/svelteStore.test.ts, ui/src/svelteStore.ts
In the tasks that polls for org updates we wait until the wallet has been connected.  This ensures that we poll as soon as possible after connecting even if the poll interval is quite large.
To achieve this we introduce the `svelteStore.waitUntil` abstraction. This abstraction can also be used to implement `waitUnsealed` more succinctly.
=> Wait until wallet is connected before fetching orgs

ui/src/session.ts, ui/src/svelteStore.test.ts, ui/src/svelteStore.ts
We add `svelteStore.waitUntil` that provides some better abstraction over `session.waitUnsealed`. This function will also be reused in the org feature.
=> refactor: introduce svelteStore.waitUntil

ui/Screen/Project/Source.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2015.
=> fix(ui) use revision icon for patches

.eslintrc.js, ui/DesignSystem/Component/Copyable.svelte, ui/DesignSystem/Component/FollowToggle.svelte, ui/DesignSystem/Component/Funding/Pool/Receivers.svelte, ui/DesignSystem/Component/Funding/Pool/TopUp.svelte, ui/DesignSystem/Component/Overlay.svelte, ui/DesignSystem/Primitive/Input/Directory.svelte, ui/DesignSystem/Primitive/Input/Password.svelte, ui/DesignSystem/Primitive/Input/Text.svelte, ui/Hotkeys.svelte, ui/Modal/Funding/Onboarding/SetBudget.svelte, ui/Modal/Funding/Pool/Withdraw.svelte, ui/Screen/Project.svelte, ui/Screen/Wallet/Pool/Outgoing/Support.svelte, ui/src/funding/contract.ts, ui/src/funding/pool.ts, ui/src/session.ts, ui/src/validation.ts
We enforce curly braces in if/else statments. This makes the code more consistent and arguably [aides readability][1]. It also reduces the number of changes required when a statement is added to a branch.
[1]: https://nakedsecurity.sophos.com/2014/02/24/anatomy-of-a-goto-fail-apples-ssl-bug-explained-plus-an-unofficial-patch/
=> refactor: enforce curly braces for if/else statments

ui/DesignSystem/Component/PeerSelector.svelte
We'll need this for [orgs](https://github.com/radicle-dev/radicle-upstream/pull/1813), because we want to reuse the peer selector in a different context.
Additionally parametrise whether to show the "Go to profile" link.
Right now it is used in the project source view with a button on the right-hand side:
And we want to reuse it without the right-hand side button:
=> style(ui): parametrise PeerSelector border styling

ETHEREUM.md, ui/src/attestation/contract.ts, ui/src/ethereum.ts, ui/src/funding/contract.ts, ui/src/funding/daiToken.ts, ui/src/org.ts, ui/src/org/safe.ts, ui/src/org/theGraphApi.ts, ui/src/settings.ts, ui/src/transaction.ts, ui/src/wallet.ts
We're well served by `Rinkeby` and don't want to spend time unnecessarily on maintaining multiple test nets.
See individual commits for the doc changes.
=> chore(ui): drop the Ropsten testnet

.eslintrc.js, .license-compliancerc.js, ci/run.sh, package.json, yarn.lock
We ensure that the licenses of all NPM production dependencies are compatible with GPL-3.0-only. See #2024.
=> feat(dev): check license compliance for NPM packages

.buildkite/pipeline.yaml, .github/workflows/build.yaml, ci/Dockerfile, ci/run.sh, deny.toml
We add cargo deny to check our rust dependencies. The deny configuration is copied from `radicle-link`. The main difference is the explicit allow list for licenses.
=> feat(dev): add cargo-deny

ci/run.sh
We force linking the cargo deny advisory DB on CI. This is necessary because the home directory is persisted between runs on the macOS agent.
=> fix(ci): force link override for cargo deny on CI

ui/DesignSystem/EmptyState.svelte, ui/Screen/Org.svelte, ui/Screen/Org/Projects.svelte, ui/Screen/Org/ProjectsMenu.svelte
We are already disabling the action bar anchoring button on the right-hand-side when there are no projects to anchor. But we forgot to disable the button in the `EmptyState` component, this takes care of that.
There's a problem with the tooltip alignment, we should fix that in a follow-up.
=> fix: disable placeholder anchor button when there are no projects

ui/src/ethereum/debug.ts, ui/src/ethereum/environment.ts, ui/src/ethereum/index.ts, ui/src/ethereum/walletConnectSigner.ts, ui/src/wallet.ts
This change is one step towards moving all Ethereum infrastructure into the `ui/src/ethereum` folder.
* We extract `WalletConnectSigner` from `ui/src/wallet` and move it under `ui/src/ethereum`.
* We extract the environment types from `ui/src/ethereum` and move it into `ui/src/ethereum/environments`.
* We extract the debug object from `ui/src/wallet` and move it into `ui/src/ethereum/debug`.
No logic has been changed.
As a follow-up we will do the same for `ui/src/wallet` and `ui/src/transaction`
=> refactor: reorganize ethereum modules

ui/src/org.ts
- hide the "Waiting for you to confirm the anchor transaction in your connected wallet" message when the user rejects signing in their wallet
https://user-images.githubusercontent.com/158411/123279930-9fa86500-d508-11eb-8867-cf53e9d80882.mov
- make "View on Gnosis Safe" message sticky
=> chore: improve org notifications

ui/src/org.ts, ui/src/org/theGraphApi.ts
We retry for 20 seconds after a 502 until we issue an error for fetching graph data.
Fixes #2042
=> fix: don’t show intermittent 502 errors from Graph requests

ui/DesignSystem/Wallet/Transactions/TxListItem.svelte, ui/Modal/Transaction.svelte, ui/Screen/Wallet/Transactions.svelte, ui/index.ts, ui/src/transaction.ts
We use `dayjs` to format dates and times instead of our custom formatters. This reduces the amount of code we need to write and also eliminates some bugs already present in our code, like not including leading zeros in minutes and seconds (e.g. “17:3:5” instead of “17:03:05”).
=> refactor: use dayjs for time formatting

ui/src/org/theGraphApi.ts
We were improperly indexing Project anchors on the Graph. This PR adjusts how we deserialize the Project ID from the updated index.
=> fix: fix Org <-> Anchor relationship

ui/DesignSystem/Modal.svelte
Fixing a bug where a modal would show `undefined` under the title if you didn't add a description.
=> bug fix: Modal undefined description

Cargo.lock
We update all cargo dependencies to resolve https://rustsec.org/advisories/RUSTSEC-2021-0072
=> chore: update cargo dependencies to resolve advisory

ui/src/wallet.ts
We lift `newWalletConnect()` to the module-level so that it does not interact with internal `Wallet` state. Before, callbacks for the modal would set `stateStore` and internal state variables. This significantly simplifies the connection flow.
=> refactor: isolate WalletConnect instance creation

ui/Screen/Settings.svelte
Re-applies c2cc5319fe5557475f0eaa48ac129942bc41276f after it was overriden by #2087.
=> fix: reapply commit to truncate device ID in settings screen

ui/src/attestation/contract.ts, ui/src/attestation/status.ts, ui/src/mutexExecutor.test.ts, ui/src/mutexExecutor.ts
We ensure that the `onClaimed` callback is called in the same order as the events that arrive. Before it was possible for `onClaimed` to be called for an event Y that occured _after_ the most recent event X _before_ `onClaimed` was called for `X`. This left the application in a state where the claim from `X` was considered more recent. This behavior was triggered by writing tests against a local Ethereum node.
=> fix: race condition when watching claim updates

proxy/api/src/http/error.rs
Whenever we encounter an unmatched error we respond with a 500 instead of a 400 and also send the error message to better identify the underlying issue in user reports.
=> fix: improved error message from server

ui/DesignSystem/Sidebar/OrgList.svelte, ui/DesignSystem/Wallet/Panel.svelte, ui/Modal/Funding/LinkAddress.svelte, ui/Modal/Funding/Onboarding/TopUp.svelte, ui/Modal/Funding/Pool/TopUp.svelte, ui/Screen/Wallet.svelte, ui/Screen/Wallet/LinkAddress.svelte, ui/src/attestation/status.ts, ui/src/funding/daiToken.ts, ui/src/funding/pool.ts, ui/src/org.ts, ui/src/wallet.ts
We create a separate store for account balances instead of storing that information in the wallet state.
In addition to the decoupling yielding cleaner code it also fixes some bugs. Before, we retrieved the balances as part of `loadAccountData` which delayed updating the connection state. This lead to the UI only updating some time after we were connected. This also lead to some race conditions where a disconnect was overriden by a pending `loadAccountData` call.
In addition to this we also remove `formattedBalance` and inline it.
=> refactor: decouple account balance store

package.json, ui/src/attestation/contract.ts, ui/src/funding/daiToken.ts, yarn.lock
We correct the all the radicle-contracts code that failed to type-check after the types were properly included in https://github.com/radicle-dev/radicle-contracts/pull/150.
=> fix: correct radicle-contracts types

cypress/integration/lock.spec.ts, ui/DesignSystem/PasswordInput.svelte, ui/Screen/Lock.svelte, ui/Screen/Onboarding/EnterPassphrase.svelte, ui/src/error.ts, ui/src/proxy/fetcher.ts, ui/src/session.ts
When the user types in an invalid passphrase we clear the input and refocus it.
Fixes #1179
=> fix: on invalid passphrase clear and refocus input

.buildkite/pipeline.yaml
I shut down the preview agent because Monadic is not paying for it anymore. We can re-enable it once the team runs it again.
=> ci: don’t build on preview agent anymore

ui/Screen/Profile/ProfileHeader.svelte
Signed-off-by: Nishit Prasad <prasad.nishit0@gmail.com>
This PR fixes #2068 
The change (GIF):
=> improvement-ui: Setting PeerId on Profile not expandable on hover

package.json, ui/src/ethereum/walletConnect.ts, ui/src/ethereum/walletConnectSigner.ts, ui/src/wallet.ts, yarn.lock
We introduce a `WalletConnect` interface that replaces the WalletConnect `Connector` in `ui/src/wallet.ts`. This interface serves to purposes
1. We move all WalletConnect specific quirks behind its implementation.
2. We can implement this interface to simulate WalletConnect in tests.
=> refactor: wallet connect facade

cypress/plugins/nodeManager/plugin.ts
We forward the `stdout` of nodes started by the tests to the terminal that cypress runs on. This ensures that it is visible.
=> fix(tests): forward `stdout` of test node to console

ui/App.svelte, ui/DesignSystem/Sidebar/OrgList.svelte, ui/Screen/Org.svelte, ui/Screen/Org/route.ts, ui/Screen/SingleSigOrg.svelte, ui/src/org.ts, ui/src/org/contract.ts, ui/src/router/definition.ts
* Instead of having much of the code that loads the org route in the global routing definition we move it to `src/Screen/Org/route.ts`.
* We introduce the org `Owner` type and remove `OrgWithSafe` to better represent owner information and to distinguish between the safe and an externally owned account.
=> refactor: consolidate org route loading

ui/src/config.ts, ui/src/ipc.ts, ui/src/updateChecker.ts
We move detection of the cypress test environment to `ui/src/config` so it can be reused. We also update the name of the similar configuration to better reflect what it does.
=> refactor: consolidate cypress test config

Cargo.lock, native/proxy-process-manager.ts, package.json, proxy/api/Cargo.toml, proxy/api/src/bin/radicle-proxy.rs, proxy/api/src/context.rs, proxy/api/src/control.rs, proxy/api/src/git_helper.rs, proxy/api/src/http.rs, proxy/api/src/http/control.rs, proxy/api/src/http/error.rs, proxy/api/src/http/project.rs, proxy/api/src/identity.rs, proxy/api/src/process.rs, proxy/api/src/project.rs, yarn.lock
We use the `tracing` and `tracing-subscriber` to do logging. This gives us nicer output and structured logs.
Includes https://github.com/radicle-dev/radicle-link/pull/727
=> fix: use tracing for logs

ui/src/ethereum/walletConnect.ts, ui/src/ethereum/walletConnectSigner.ts, ui/src/wallet.ts
Instead of polling the wallet connect settings we use events emitted by
WalletConnect. This makes the network switch immediate and also
simplifies some code.
=> fix: event based wallet connection for immediate response

.github/workflows/build.yaml
We bump the version of the yarn cache on Github actions. The old cache was 1.3GiB in size because it held previous versions of Cypress.
=> ci: bump github actions cache

ui/src/org.ts, ui/src/org/theGraphApi.ts
We don’t show an error when the graph API returns a 503. This behavior mirrors that of the behavior on a 502.
Fixes #2183.
=> fix: retry graph requests on 503

Cargo.lock, proxy/api/Cargo.toml, proxy/api/src/context.rs, proxy/api/src/process.rs
Update radicle-link to include https://github.com/radicle-dev/radicle-link/pull/731 and https://github.com/radicle-dev/radicle-link/pull/736.
Fixes #2133
=> fix: update radicle-link to properly shutdown

deny.toml
The vulnerability is in the `tar` crate that is only used by `radicle-surf` as a build dependency.
=> fix: ignore security advisory that we’re unaffected by

ui/DesignSystem/TextInput.svelte, ui/Modal/Org/ConfigureEns/LinkOrgToName.svelte, ui/Modal/Org/ConfigureEns/PopulateMetadata.svelte
Remove the option to specify a label from TextInput. Instead, the label is created next to the input. This simplifies the TextInput component. Since it is not clear how re-usable the label part is (it is only used in two forms) we also avoid having to adjust the TextInput component over and over in the future.
=> refactor: text input without label

ui/DesignSystem/Avatar.svelte, ui/src/ethereum/walletConnect.ts, ui/src/ethereum/walletConnectSigner.ts, ui/src/modal.ts
A couple of commits that make prepartional changes for #2191
* fix: properly scale avatar images
We remove the `image` class that fixed the size. Instead the size is determined by the `size` class, just like for the avatar fallback.
* feat: add signTypedData to wallet connect
* refactor: improve modal prop interface
=> ens integration preparation

ui/Modal/Org/ConfigureEns/ConfirmRegistration.svelte, ui/Modal/Org/ConfigureEns/EnterEnsName.svelte, ui/src/org/ensRegistrar.ts
Before, some of the functions in `ensRegistrar` would use a style `Wallet` value because it was set at the module level. Now, we get the most recent wallet when the functions are called.
Since the functions are inherently stateful, we don’t require functions to pass down the `environment` parameter and get it from the wallet instead.
=> fix: don’t use stale wallet

ui/Modal/Org/ConfigureEns/LinkOrgToName.svelte, ui/src/ethereum/index.ts, ui/src/org.ts, ui/src/org/contract.ts
We rewrite `org.setNameMultisig` and `org.setSingleSigName` to better align with project anchoring. This means we make the code in `ui/src/org/contract` stateless, i.e. independent of the wallet. We consolidate the stateful code in `ui/src/org`. We also hardcode the ENS addresses since they might not always be available from the provider.
=> refactor: align use of setName for org contract

proxy/api/src/http/identity.rs, proxy/api/src/http/project.rs, proxy/api/src/identity.rs, proxy/api/src/project.rs, ui/src/__mocks__/api.ts, ui/src/identity.ts, ui/src/proxy/identity.ts, ui/src/proxy/project.ts
It was never used. On the first public release we opted for sharing project `URN`s and `DeviceId`s.
=> refactor: remove unused shareable_entity_identifier attribute

cypress/support/commands.ts, ui/src/config.ts
We use the IPv4 address the proxy is bound to instead of the `localhost` hostname. This fixes #2181 where `localhost` resolves to the IPv6 localhost address.
=> fix: use proxy IP instead of hostname

cypress/support/commands.ts, proxy/api/src/context.rs, proxy/api/src/http/notification.rs, proxy/api/src/process.rs, proxy/api/src/service.rs
We ensure that the tests wait until the proxy has been properly sealed before continuing.
To make this work we also need to ensure that the HTTP server shuts down properly by terminating any event streams.
=> fix: tests wait until keystore is sealed

ui/src/org.ts
We properly initialize the remaining tries when the graph is
unavailable.
=> fix: silent retries if graph is unavailable

ui/src/error.ts
When the code is executed by the cypress test runner (i.e. the code were tests are defined) we also don’t want to handle errors and show them to the user. Instead they should be unhandled errors that make the tests fail.
=> fix: don’t handle unhandled errors in cypress runner

ui/Screen/Onboarding.svelte, ui/src/api.ts, ui/src/proxy/index.ts, ui/src/retryOnError.test.ts, ui/src/retryOnError.ts, ui/src/session.ts
*Review commit-by-commit*
When unsealing the session we’ll wait until it is actually unsealed. This fixes a race condition where we fetch the session before the proxy has had time to restart.
This includes a separate commit that extracts the retry functionality in it’s own module and generalizes it.
=> fix: wait until session is unsealed

ui/src/ethereum/walletConnect.ts
Since WalletConnect 1.6.0 setting `bridge` to a custom value has no effect anymore. They're urging everyone to use their default infrastructure.
=> chore: use the default walletconnect bridge

ui/src/transaction.ts
We don’t call `error.fromJsError` so we also handle other types of errors. By passing `e` as the `source` parameter directly we leverage `error.fromUnknown` which is called internally.
=> fix: don’t swallow transaction error source

ui/Modal/Wallet/QRCode.svelte
=> style: fix QR code style in light mode

ui/src/session.ts
As reported in #2252, it may take more than five seconds to unseal the
keystore. We’re increasing the timeout to 20 seconds.
=> fix: increase timeout to unseal

ui/DesignSystem/Funding/Pool/TopUp.svelte, ui/DesignSystem/Modal.svelte, ui/DesignSystem/TxButton.svelte, ui/Modal/Funding/LinkAddress.svelte, ui/Modal/Funding/Onboarding.svelte, ui/Modal/Funding/Onboarding/AddReceivers.svelte, ui/Modal/Funding/Onboarding/Erc20Allowance.svelte, ui/Modal/Funding/Onboarding/Intro.svelte, ui/Modal/Funding/Onboarding/Review.svelte, ui/Modal/Funding/Onboarding/SetBudget.svelte, ui/Modal/Funding/Pool/Collect.svelte, ui/Modal/Funding/Pool/TopUp.svelte, ui/Modal/Funding/Pool/Withdraw.svelte, ui/Modal/ManagePeers.svelte, ui/Modal/NewProject.svelte, ui/Modal/Org/AnchorProject.svelte, ui/Modal/Org/Create.svelte
- use `<Modal>` component consistently in the funding feature
- introduce a `buttons` slot
- convert the `description` prop into a slot, this will allow us to add partial styling to the description, e.g. **bold** parts of the text
Required for https://github.com/radicle-dev/radicle-upstream/pull/2191.
For visual review, here's all of the modals after this change:
=> chore: use Modal component consistently

ui/src/ethereum/walletConnect.ts, ui/src/ethereum/walletConnectSigner.ts
We implement `signMessage` for the test wallet. This requires us to move the computation of the EIP-191 message hash from `WalletConnectSigner` to implementations of `WalletConnect`. We also use `ethers.utils.hashMessage` to compute the message.
=> feat: implement signMessage for test wallet

ui/App.svelte, ui/DesignSystem/Modal.svelte, ui/DesignSystem/ProjectAnchorPopover.svelte, ui/DesignSystem/Sidebar/OrgList.svelte, ui/Modal/Org/ConfigureEns.svelte, ui/Modal/Org/ConfigureEns/BlockTimer.svelte, ui/Modal/Org/ConfigureEns/ConfirmRegistration.svelte, ui/Modal/Org/ConfigureEns/Intro.svelte, ui/Modal/Org/ConfigureEns/LinkOrgToName.svelte, ui/Modal/Org/ConfigureEns/RegisterName.svelte, ui/Modal/Org/ConfigureEns/UpdateMetadata.svelte, ui/Modal/Transaction.svelte, ui/Screen/Org.svelte, ui/Screen/Org/OrgHeader.svelte, ui/Screen/Org/route.ts, ui/Screen/SingleSigOrg.svelte, ui/src/ethereum/index.ts, ui/src/ethereum/walletConnectSigner.ts, ui/src/org.ts, ui/src/org/configureEns.ts, ui/src/org/contract.ts, ui/src/org/ensRegistrar.ts, ui/src/org/ensResolver.ts, ui/src/org/theGraphApi.ts, ui/src/project.ts, ui/src/transaction.ts, ui/src/wallet.ts, ui/src/wallet/radToken.ts
Working on top of https://github.com/radicle-dev/radicle-upstream/pull/2180.
=> feat: integrate org ENS name registration

ui/DesignSystem/Wallet/Transactions/TxListItem.svelte, ui/Modal/Transaction.svelte, ui/src/transaction.ts
We remove presentational logic from `ui/src/transaction.ts` and move it into the components that use it. This eliminates circular dependencies involving the `transaction` module.
=> refactor: remove presentational logic from transaction module

package.json, ui/src/org.ts, ui/src/org/safe.ts, ui/src/org/theGraphApi.ts, yarn.lock
Instead of using two different the Graph indexes we use the API provided by gnosis to query gnosis related data.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2169.
=> chore: use the safe client api instead of the graph index

ui/DesignSystem/Wallet/Transactions/TxListItem.svelte
Gets rid of:
```
WARNING in ./ui/DesignSystem/Wallet/Transactions/TxListItem.svelte 230:47-49
export 'Tx' (imported as 'Tx') was not found in 'ui/src/transaction' (possible exports: TxKind, TxStatus, add, anchorProject, claimRadicleIdentity, collect, colorForStatus, commitEnsName, convertError, createOrg, erc20Allowance, initialize, linkEnsNameToOrg, ongoing, registerEnsName, store, supportOnboarding, topUp, updateEnsMetadata, updateSupport, withdraw)
@ ./ui/DesignSystem/Wallet/Transactions/TxList.svelte 32:0-45 54:18-28 248:2-12
@ ./ui/Screen/Wallet/Transactions.svelte 30:0-71 216:14-20 273:14-20 330:14-20 492:2-8
@ ./ui/Screen/Wallet.svelte 55:0-56 643:20-32 970:2-14
@ ./ui/App.svelte 55:0-45 285:16-22 1083:2-8
@ ./ui/index.ts 11:0-31 12:16-19
```
=> fix: get rid of typescript warning

ui/DesignSystem/Wallet/Transactions/TxList.svelte, ui/Modal/Transaction.svelte, ui/src/transaction.ts
* Pass transaction hash via modal props instead of store
* Throw error when selected transaction is not found instead of handling `undefined` and showing nothing.
=> refactor: simplify transaction modal

cypress/integration/project/creation.spec.ts, ui/Modal/NewProject.svelte, ui/Screen/Profile/Following.svelte, ui/src/config.ts, ui/src/notification.ts, ui/src/project.test.ts, ui/src/project.ts
We move some of the constants back to their respective modules, because they're not really configuration.
=> refactor: move constants out of config module

ui/src/org.ts, ui/src/org/configureEns.ts
Previously it only worked because the org list was refreshed frequently.
=> fix: update org ENS names in sidebar after registration

ui/App/CreateOrgModal.svelte, ui/App/DesignSystemGuideModal.svelte, ui/App/OrgScreen/Members.svelte, ui/App/OrgScreen/OrgHeader.svelte, ui/App/OrgScreen/ProjectAnchorPopover.svelte, ui/App/ProfileScreen.svelte, ui/App/ProfileScreen/ProfileHeader.svelte, ui/App/ProjectScreen/ManagePeers/Peer.svelte, ui/App/ProjectScreen/PeerSelector/Peer.svelte, ui/App/ProjectScreen/Source/PatchCard.svelte, ui/App/ProjectScreen/Source/PatchLoaded.svelte, ui/App/Sidebar.svelte, ui/App/Sidebar/OrgList.svelte, ui/App/UserProfileScreen.svelte, ui/App/UserProfileScreen/UserProfileHeader.svelte, ui/App/WalletScreen/LinkAddressModal.svelte, ui/App/WalletScreen/TransactionModal/Identity.svelte, ui/DesignSystem/Avatar.svelte
Improve the Avatar component interface and decouple it from Upstream code. To generate emojis, we use the `radicle-avatar` library. To cut down on the amount of variants this component has, we remove unused sizes.
Refs: https://github.com/radicle-dev/radicle-upstream/issues/1877.
=> refactor: improve Avatar component

Cargo.lock, proxy/api/Cargo.toml, proxy/api/src/http/identity.rs, proxy/api/src/identity.rs, ui/src/identity.ts, ui/src/proxy/identity.ts
As of https://github.com/radicle-dev/radicle-upstream/pull/2332 we do it all in the UI.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1927.
=> chore: remove radicle-avatar dependency from proxy

ui/App/SettingsScreen.svelte
=> style: fix update message alignment

ui/App/Hotkeys.svelte, ui/App/ShortcutsModal.svelte, ui/src/hotkeys.ts
- add a new shortcut for the Network screen <kbd>⌘</kbd> + <kbd>b</kbd>
- hide dev shortcuts from the shortcuts modal, because we decided that
development mode should visually look exactly the same as
production
- hide network diagnostics shortcut from the shortcuts modal, because
this is only used for debugging and the diagnostics screen itself
isn't designed properly yet
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2122.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1973.
I picked the network shortcut based on [this post](https://stackoverflow.com/a/59010351).
=> feat: improve keyboard shortcuts

ui/DesignSystem/DirectoryInput.svelte, ui/DesignSystem/TextInput.svelte
This is how it's done in other UIs and users expect to be able to click on the text input field.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1165.
https://user-images.githubusercontent.com/158411/132455855-2f17777c-9d00-4ec8-a40c-14b104adcf65.mov
=> fix: make DirectoryInput text field open the file dialog

public/typography.css, ui/App/ExternalLink.svelte, ui/App/NetworkScreen.svelte, ui/App/OrgScreen/ConfigureEns/Intro.svelte, ui/App/OrgScreen/Projects.svelte, ui/App/ProjectScreen/RemoteHelperHint.svelte, ui/App/SettingsScreen.svelte, ui/App/WalletScreen/QrCodeModal.svelte, ui/src/org.ts
This is only about links that open outside of Upstream.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1967.
=> style: format all external links consistently

cypress/integration/project/source_browsing.spec.ts, public/global.css, public/typography.css, ui/App/DesignSystemGuideModal.svelte, ui/App/OrgScreen.svelte, ui/App/OrgScreen/OrgHeader.svelte, ui/App/OrgScreen/ProjectAnchorPopover.svelte, ui/App/ProjectScreen/Source/Commit.svelte, ui/App/ProjectScreen/Source/SourceBrowser/CommitTeaser.svelte, ui/App/Sidebar/OrgList.svelte, ui/App/SingleSigOrgScreen.svelte, ui/App/TransactionHash.svelte, ui/App/WalletScreen/Pool/Outgoing/Support.svelte, ui/App/WalletScreen/Pool/Receiver.svelte, ui/App/WalletScreen/Pool/WithdrawModal.svelte, ui/App/WalletScreen/TransactionModal.svelte, ui/App/WalletScreen/TransactionModal/Identity.svelte, ui/DesignSystem/Identifier.svelte, ui/src/ethereum/index.ts, ui/src/format.ts, ui/src/org.ts
- style Ethereum address properly in transaction modal
- ban <a> tags
- format pool receiver button Ethereum addresse
- add component for displaying Ethereum transaction links to Etherscan
- make org address copyable
- truncate org address in sidebar
- replace copy owner address to clipboard with "View on Etherscan"
- restyle anchor popover
- show commit hashes consistently
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2231.
This is what the UI would look like _if_ a developer would use the `<a>` tag. It is an "UI error" and formatted like this on purpose.
=> refactor: format all hashes consistently

ui/App/OrgScreen/Projects.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2128.
Should the tab also be all lowercase i.e. `Anchored projects`?
=> chore: improve anchoring placeholder wording

ui/App/Sidebar/OrgList.svelte, ui/src/org.ts
- show org list loading indicator while waiting for ENS resolution if there are any orgs
- show `+` button even if the wallet isn't connected, go to wallet page when clicked
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2344
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2090
App loading when there are orgs:
https://user-images.githubusercontent.com/158411/133097146-83018e31-f554-4d97-a6b2-78fed3a73a96.mov
App loading when there are no orgs:
https://user-images.githubusercontent.com/158411/133097170-89712ae1-d3a2-41f8-b615-ea08d10add58.mov
=> feat: improve org sidebar ux

cypress/support/index.ts, docs/development.md, docs/ethereum.md, native/index.ts, ui/App/ProjectScreen/Source/SourceBrowser/RevisionSelector.svelte, ui/src/config.ts
This was introduced together with the funding feature which didn't get released and is not useful anymore.
=> chore: remove unused feature flagging code

package.json, ui/src/ethereum/walletConnect.ts, yarn.lock
There have been recent improvements to the infrastructure according to the walletConnect team, so we should try it again.
=> chore: upgrade walletConnect to 1.6.5

cypress/integration/project/source_browsing.spec.ts, public/typography.css, ui/DesignSystem/Markdown.svelte
Fixes a regression introduced with https://github.com/radicle-dev/radicle-upstream/pull/2352. Links in rendered markdown had a wrong styling due to the CSS warning that I added. Wasn't a good idea in hindsight.
We also apply a different style to relative links and prevent user interaction.
Closes https://github.com/radicle-dev/radicle-upstream/issues/1347.
Note: making relative links work properly would require a substantial change to the source browsing code.
Regression:
Fix:
Disabled relative links:
We don't apply the styling if the `<a>` tag contains images:
=> style: render external links in markdown with appropriate style

README.md, docs/development.md, native/index.ts, package.json, proxy/api/src/config.rs, proxy/api/src/git_helper.rs, proxy/api/src/process.rs, ui/src/profile.ts, yarn.lock
Finishing the work that @bltavares started in https://github.com/radicle-dev/radicle-upstream/pull/1623. I squashed all of the existing commits, rebased it on top of the current master, fixed merge conflicts and cleaned up any outstanding code review comments.
So far only tested that everything still works on macOS both in dev mode and release build.
I tried testing it on Windows, but my machine is too weak to build it in a VM.
@bltavares could you please try it on Windows and let us know whether it still works?
Note that we're planning two major changes to the architecture of Upstream this year: moving away from Electron and migrating to a stand-alone Radicle daemon. Both of these changes might require re-thinking Windows support again.
=> feat: add experimental windows support

proxy/api/src/notification.rs, proxy/api/src/process.rs
We eliminate the reference to `radicle_daemon::MaybeFrom` to reduce the reliance on `radicle_daemon` code.
=> refactor: eliminate use of radicle_daemon::MaybeFrom

cypress/integration/networking.spec.ts
We’re trying to fix flaky networking tests on CI by allowing retries and by adding sleeps to prevent race conditions between the P2P nodes.
See https://github.com/radicle-dev/radicle-upstream/issues/2232
=> fix: try to avoid CI race conditions in networking tests

cypress/support/commands.ts, ui/App/OnboardingModal.svelte, ui/src/identity.ts, ui/src/org.ts, ui/src/proxy/identity.ts, ui/src/proxy/index.ts, ui/src/userProfile.ts
* We follow the pattern outlined for other endpoints and move all the methods into a separate identity client class.
* We rename `remoteIdentityGet` to `personGet` as this is terminology used by the identities CLI.
* We eliminate some unused code and indirections.
=> refactor: cleanup identity endpoints

ui/src/browserStore.test.ts, ui/src/browserStore.ts, ui/src/ethereum/index.ts, ui/src/updateChecker.ts
We add a svelte store abstraction that uses the browser storage for
persistence and validates the values.
=> feat: add validated browser storage abstraction

ui/App/CreateProjectModal.svelte, ui/App/ProjectScreen/RemoteHelperHint.svelte, ui/App/ProjectScreen/Source/CheckoutButton.svelte, ui/src/session.ts
We store information on whether the remote helper hint has been shown in the browser.
This is part of #1849.
=> fix: store remote helper hint data locally

proxy/api/src/http/session.rs, proxy/api/src/lib.rs, proxy/api/src/session.rs, ui/App/NetworkScreen.svelte, ui/src/proxy/index.ts, ui/src/session.ts
We add a dedicated endpoint for getting and updating seed addresses for the proxy. This decouples the seeds from the session and will allow us to eliminate the settings in the future. See #1137
=> feat: add dedicated endpoint for network seeds

docs/contributing.md
Just adding some notes for how to contribute as a designer. Open to any suggestions to make this more clear or specific. We haven't actually accepted any open source design contributions yet so it's a totally new process.
=> add contribution notes for designers to `contributing.md`

ui/App/DesignSystemGuideModal.svelte
- rename tooltip "Font color" -> "Primary color"
- move primary color switcher next to theme switcher
=> style: move primary color switcher in design system guide

cypress/integration/networking.spec.ts, cypress/integration/project/patches.spec.ts, cypress/support/commands.ts, cypress/support/nodeManager.ts
We eliminate all custom HTTP API calls in the tests and replace them with calls to the proxy client.
=> refactor: eliminate custom proxy API calls in tests

proxy/api/src/http/identity.rs, proxy/api/src/identity.rs, ui/src/proxy/identity.ts
We remove the proxy endpoint for getting local identities since it was unused.
=> refactor: remove endpoint for getting local identities

proxy/api/src/error.rs, proxy/api/src/http/error.rs, proxy/api/src/http/identity.rs
* Eliminate `Error` struct which was only used as the payload and replace it with the `Response` struct which also includes the status code.
* Separate responsibilities for converting an error into an HTTP response and actually replying. The former is implemented via `From` traits.
* Remove globally defined SessionInUse error to demonstrate new design
=> refactor: introduce Response struct for easier error conversion

ui/App/NetworkScreen.svelte
Fixes #242 (the unnecessary scrolling on the networking page) and the misaligned seed input button.
=> fix: network page scroll and button alignment

ui/src/proxy/identity.ts
* We deduplicate the schema for `Metadata`
* We put type annotations on the schema to ensure that they are schemas for the given types.
=> refactor: deduplicate and annotate identity schemas

ui/App/DesignSystemGuideModal.svelte, ui/DesignSystem/Tooltip.svelte
We position tooltips relative to their container.
Using `position: fixed` (i.e. relative to the viewport) does not work when a containing element has the `transform` property set [1]. In that case the tooltip would be positioned relative to that element.
This example is from #2433.
[1]: https://developer.mozilla.org/en-US/docs/Web/CSS/position#values
=> fix: relative positioning for tooltips

ui/App/LoadingScreen.svelte, ui/App/ProjectScreen/Source/Anchors.svelte, ui/App/ProjectScreen/Source/Commit.svelte, ui/App/ProjectScreen/route.ts, ui/App/ScreenLayout/EmptyState.svelte, ui/src/screen/project/source.ts
Show a placeholder if the commit isn't replicated instead of an error message. This also fixes the anchor list not being properly ordered, now the latest anchor is at the top and the list is sorted by timestamp oldest at the bottom.
Closes https://github.com/radicle-dev/radicle-upstream/issues/2448.
=> fix: show commit not found screen instead of error

docs/infrastructure.md
* List resources and their IDs up front
* Mention org seed node in GCP project overview
* Add step that creates the network address
* Consolidate some of the steps to set up the VM
=> improve docs for org seed node

docs/infrastructure.md
We're running our own Org Seed Node so that the Upstream codebase is browsable via the [Radicle web interface](https://app.radicle.network/orgs/upstream.radicle.eth/projects/rad:git:hnrk8ueib11sen1g9n1xbt71qdns9n4gipw1o/3b6b4b3d198c0070c8ba57846ec5e154826207d4).
Closes https://github.com/radicle-dev/radicle-upstream/issues/2302.
=> docs: document org node setup

ui/App/OrgScreen/AnchorProjectModal.svelte, ui/src/proxy/source.ts, ui/src/source.ts
While working on integrating the new Radicle CLIs (#2432) to do source browsing I realized that it would be helpful get a better understanding of the HTTP API for source browsing. Making it more type-safe will also help detecting mistakes.
Please see the individual commits for details.
=> Move code to proxy client

ui/App/ProjectScreen/Source/Code.svelte, ui/App/ProjectScreen/Source/SourceBrowser/Changeset.svelte, ui/App/ProjectScreen/Source/SourceBrowser/FileDiff.svelte, ui/src/proxy/commit.ts, ui/src/proxy/source.ts, ui/src/screen/project/source.ts, ui/src/source.ts, ui/src/source/diff.ts
We add `commitGet` to the proxy client and use this function exclusively to get commit data.
This requires us to move the type definitions for commits and diffs to the proxy (`ui/src/proxy/commit`) and also implement schemas for these types.
We also eliminate some type definitions and inline them.
We also remove the `changeset` field from `Commit`. It is not used in the client and not provided by the proxy.
=> refactor: fetch single commits through proxy client

deny.toml
We ignore [RUSTSEC-2020-0071][1] because we’re likely unaffected and this probably isn’t going to be fixed any time soon.
[1]: https://rustsec.org/advisories/RUSTSEC-2020-0071
=> fix: ignore RUSTSEC-2020-0071

deny.toml
They're all coming from radicle-link and should be fixed there. Muting
the advisories until they get fixed upstream.
=> fix: ignore cargo-deny advisories

design-system/Showcase.svelte
Use an org avatar image with a background so that the shape is visible in the example.
=> style: use different org avatar image example

.lintstagedrc.yaml, docs/development.md, package.json, scripts/license-header.ts, yarn.lock
Use `git ls-files` to get paths to check for the license headers. This is simpler and does not require adjustments when directories are added or changed.
=> use `git ls-files` to get paths for license check

native/index.ts, proxy/api/src/cli.rs
The default seed for the proxy can now be configured via an environment variable. We remove the default seed in the dev environment. It is not working and prevents us from using the environment variable.
=> set default seed via env

proxy-client/index.ts, proxy/api/src/http/diagnostics.rs, ui/App/DiagnosticsScreen.svelte, ui/App/DiagnosticsScreen/Connections.svelte
Add mode debug info.
```
{
"listenAddresses": [
"127.0.0.1:62227",
"192.168.178.20:62227"
],
"protocolConfig": {
"membership": {
"maxActive": 5,
"maxPassive": 30,
"activeRandomWalkLength": 6,
"passiveRandomWalkLength": 3,
"shuffleSampleSize": 7,
"promoteInterval": {
"nanos": 0,
"secs": 30
},
"shuffleInterval": {
"nanos": 0,
"secs": 30
}
},
"network": "Main",
"replication": {
"fetchLimit": {
"peek": 5120000,
"data": 5368709120
}
},
"fetch": {
"fetchSlotWaitTimeout": {
"nanos": 0,
"secs": 20
}
}
},
"membership": {
"active": [
"hynkyndc6w3p8urucakobzna7sxwgcqny7xxtw88dtx3pkf7m3nrzc"
],
"passive": []
}
}
```
=> chore: expose more peer debugging info in diagnostics

proxy/api/src/http.rs, proxy/api/src/lib.rs, proxy/api/src/service.rs, upstream-seed/src/lib.rs, upstream-seed/src/peer.rs
* Align the lint settings between both crates.
* Remove clippy’s pedantic and nursery lints. They lead to a lot of false postivies that require manual tweaking.
* Don’t allow `clippy::or_fun_call` and fix all instances. This lint is sensible and we wan to limit the tweaking.
=> consistent Rust lint settings

ui/App/Hotkeys.svelte
This fix makes sure that <kbd>⌘</kbd> + <kbd>i</kbd> opens the diagnostics screen and <kbd>alt</kbd> + <kbd>⌘</kbd> + <kbd>i</kbd> only opens the chromium devtools without switching to the diagnostics screen.
Fixes a regression introduced in https://github.com/radicle-dev/radicle-upstream/pull/2566.
=> fix: don't show diagnostics on devtools hotkey

Cargo.lock, upstream-seed/Cargo.toml, upstream-seed/src/lib.rs
Add `TaskRunner` to provide an extensible platform for managing tasks and shutdown. The abstraction makes it easy to add additional long running tasks and ensure proper shutdown.
At the moment this improves the following
* If the tracking task panics `librad` is shut down properly
* The tracking project loop is not just cancelled when a shutdown is requested. Instead we finish one iteration.
The logic for `TaskRunner` is very similar to that of `ShutdownRunner` in the proxy. I opted to not consolidate this for now. We can’t share code between the two crates yet and there is enough of a difference between the two implementations.
=> seed: more robust shutdown with task runner

cypress.json, cypress/integration/networking.spec.ts, cypress/integration/project/patches.spec.ts
The Github CI instances are slower than the previous Buildkite instances and some tests now take longer and occasionally fail. We raise the global command timeout to 8 seconds for all tests and retry failing tests once.
=> fix: reduce spec flakiness

.github/workflows/build.yaml, .github/workflows/dist.yaml, ci/build.sh, ci/env.sh, package.json
Improvements and cleanup to CI regarding caching
50dd2a40 clean up CI build script
* Align the logs more closely with the command they run
* Remove `time` whenever the command prints the time itself.
* Add `cargo build` step. Before this was implicitly called by `yarn test:ingeration` and the output was hard to find.
* Group cargo steps together
https://github.com/radicle-dev/radicle-upstream/pull/2584/commits/533bd12bb58d7aa8d5c5c060f8cac471912303cb cache more efficiently on CI
* Be more selective about which directories to cache on CI to reduce the cache size from 1.5GB to 1.3GB.
* Avoid symlinks for target directory and use standard CARGO_HOME to for reduced complexity.
=> Better caching on CI

Cargo.lock, upstream-seed/Cargo.toml, upstream-seed/src/lib.rs, upstream-seed/src/peer.rs
The seed now logs information about the active and passive gossip membership and the list of connections whenever these change.
=> seed: log info about connections and gossip membership

.husky/pre-push
Add a Git pre-push hook that prevents pushing commits with messages that start with “fixup!”, “squash!” or “ammend!” to master.
How to test this:
1. Install the hooks with `yarn run husky install`.
2. Create a new branch `git checkout -b fixup-test` based on this commit.
3. Push the branch with `git push origin` or similar.
4. Replace the target ref in the pre-push hook with `sed -i 's/master/fixup-test/' .husky/pre-push`.
5. Commit this as a fixup commit with `git commit -a --fixup HEAD -m wip`.
6. Push the changes with `git push origin` or similar.
7. The push should fail.
=> prevent pushing fixup commits to master with git hook

Cargo.lock, upstream-seed/Cargo.toml, upstream-seed/README.md, upstream-seed/src/lib.rs, upstream-seed/src/peer.rs
Whenever a new peer is added to the active gossip set we broadcast a Have message for all projects and remotes that we replicate.
See #2564.
=> seed: announce projects whenever new peer connects.

ui/App/SharedComponents/UserIdentity.svelte
Fixes a bug where the user handle was "undefined" in the `UserIdentity` hovercard.
Before:
After:
=> fix: show handle from metadata if none is passed via props

proxy/api/src/cli.rs, proxy/api/src/context.rs, proxy/api/src/http.rs, proxy/api/src/process.rs, proxy/api/src/service.rs
We need this for our automated network tests.
To test this:
```sh
cargo run --all-features -- --insecure-http-api --key-passphrase 1111
curl -s -X GET http://127.0.0.1:17246/v1/projects/tracked |jq
[]
```
=> feat: add switch to disable HTTP API auth token check

Cargo.lock
Update cargo dependencies to address [RUSTSEC-2021-0124](https://rustsec.org/advisories/RUSTSEC-2021-0124).
=> update cargo dependencies to address RUSTSEC-2021-0124

ui/App/ProjectScreen/Source.svelte, ui/App/ProjectScreen/Source/Commit.svelte, ui/src/screen/project/source.ts
The `Source/Commit` now owns its state regarding loaded commits. We also add a loading screen and make prevent race conditions when loading data.
=> commit component owns its state

ui/App/ProjectScreen/ManagePeersModal.svelte, ui/src/screen/project.ts
This change has the following advantages
* We don’t use the deprecated `Remote` component
* The derived store is much simpler
* We keep data close to the component where it is used
=> move pending peers storage into `ManagePeersModal`

proxy/api/src/cli.rs, proxy/api/src/context.rs, proxy/api/src/http/session.rs, proxy/api/src/process.rs, proxy/api/src/session.rs
Consists of two commits, the first one is preparing the change.
proxy: improve seed handling for discovery
* Don’t pass the default seeds down to `session::seeds()`. Instead, return an `Option` that can later be combined with `unwrap_or_default()`.
* Use an empty list of seeds as the default if nothing is set. This alleviates the need to pass the default seeds to the discovery task. The configured default seeds will still be used when the session is initialized and the seed value set to the default seeds.
* Query the configured seeds more frequently (every 0.4s instead of every 5s). Querying is cheap and this results and updates being propagated more quickly.
* Update the discovery list even if the peer status is offline. Not sure why this was there but I seems wrong.
proxy: add option to …
=> proxy: add option to override seeds

proxy/api/src/bin/git-remote-rad.rs, proxy/api/src/cli.rs, proxy/api/src/keystore.rs, proxy/api/src/process.rs, proxy/api/src/service.rs
To make manual testing and debugging easier, we add a couple of CLI options and environment variables.
Add `--identity-key <identity-key>` option to `radicle-proxy`, which allows overriding the key file path that normally gets set by `RAD_HOME`.
Also add 2 new environment variables for the `git-remote-rad` helper:
- `IDENTITY_KEY` allows overriding the key file path (analogous to `--identity-key` option in proxy)
- `KEY_PASSPHRASE` allows passing in the passphrase via an env variable (analogous to the `--key-passphrase` option in proxy).
=> feat: allow to specify the librad key file path via CLI option

proxy/api/src/context.rs, proxy/api/src/http.rs
We check the authentication logic so that it allows unauthenticated access when both the `--insecure-http-api` option is specified and the `/keystore/unseal` endpoint was called.
=> allow unauthenticated access after unseal

ci/build.sh, ci/dist.sh
Yarn is trying to be clever and inserts its own log groups when run on Github actions, but the implementation seems buggy, because there are stray logs interleaved with the log groups making the output harder to read.
I tried removing the outer log group wrapper, but that didn't help either, in the end settled on disabling the fancy log output entirely.
If anyone's curious, here's the implementation:
https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/StreamReport.ts#L31
Before:
After:
=> fix: disable yarn log grouping on CI

upstream-seed/src/lib.rs, upstream-seed/src/peer.rs
* Reduce the logging noise coming from `librad` by default. We set the `librad` log level to `info` and silence some of the `info` logs.
* Log gossip put events so that we see what arrives over the wire.
=> seed: reduce logging noise and log gossip puts

docs/infrastructure.md
We remove the mention of the container registry from the infrastructure docs. The container registry is not used anymore and will be shut down.
=> docs: remove mention of container registry

upstream-seed/src/lib.rs
Don’t fetch projects concurrently. Calling `librad::git::tracking::track` may lead to races because we’re writing to the config file.
=> seed: don’t fetch projects concurrently

Cargo.lock, proxy/api/Cargo.toml, proxy/api/src/context.rs, proxy/api/src/http.rs, proxy/api/src/http/notification.rs, proxy/api/src/notification.rs, proxy/api/src/process.rs
* Eliminate the single variant enum `Notification`
* Use `tokio-stream` to wrap the peer events receiever
* Add `notifications` to context instead of passing it separately to `api`.
=> simplify proxy notifications

ui/App/UserProfileScreen/route.ts, ui/src/org.ts, ui/src/session.ts, ui/src/svelteStore.test.ts, ui/src/svelteStore.ts
We wait until the session is unsealed on app startup when loading the user profile route. Before, the code may have thrown an error if the route was loaded before the session was loaded.
To enable this we make `svelteStore.waitUntil()` more general an useful.
=> wait until session is unsealed when loading user profile route

.github/workflows/dist.yaml, ci/dist.sh, docs/development.md, scripts/release.ts
We perform macOS notarization manually from now on.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2556.
=> chore: update macOS notarization release steps

docs/development.md, scripts/release.ts
Noticed while doing the release, that we should mention the manual notarization step in the docs first.
=> docs: improve release notarization documentation

Cargo.lock, proxy/api/Cargo.toml, proxy/api/src/context.rs, proxy/api/src/http/notification.rs, proxy/api/src/process.rs
* We replace `tokio` broadcast channels with `async_broadcast` channels. The latter has `InactiveReceivers` that can be cloned. This allows contexts to contain a receiver instead of a sender.
* We can now separate the logging of events from the forwarding to another broadcast receiver.
* We move the conversion to `Notification` out of the `process` module since this is not part of its responsibility.
* We don’t need to use the shutdown runner because the tasks automatically finish when the peer shuts down.
=> proxy: improved peer events

proxy/api/src/process.rs
Make the log output from the proxy less noisy by raising the level of `librad` to `info` and filtering unnecessary info logs. Thew new configuration is roughly the same as the one for `upstream-seed`.
=> proxy: less noisy logging

p2p-tests/lib/p2p.ts, p2p-tests/lib/topology.sh, p2p-tests/mesh-topology.sh, p2p-tests/star-topology.sh
Work around an issue where the protocol shuts down when it tries to connect to a peer it does not have a route for in the tests. This causes occasional failures in the tests.
To address the problem, add a default route to the loopback interface when creating the peer networking stack. This makes all addresses routable, but the will not arrive unless we have a specific route.
We also refactor the code that setups up the network: We extract creation of the network stack for a peer into a `create_peer` function. We also use the `macvlan` virtual interface instead of `veth` so that we don’t need to deal with two ends.
=> tests: work around for failure with unroutable peers

ci/p2p-network-tests.sh, p2p-tests/contributor-fork-replication-1-test.ts, p2p-tests/contributor-fork-replication-2-test.ts
Implements the ["Contributor Fork Replication"](https://www.notion.so/Test-Scenarios-bc8474555d804f96aae3777db5829216#17a1f0c6ec264bdeb4e5c77ba0b7b0b6) test and a variant thereof.
This fails because of https://github.com/radicle-dev/radicle-upstream/issues/2665.
=> test: verify contributor updates propagate back to maintainer

.github/workflows/build.yaml, .github/workflows/dist.yaml, .github/workflows/p2p-network-tests.yaml, ci/build.sh, ci/dist.sh, ci/env.sh, ci/p2p-network-tests.sh
The new cache is 800MB instead of 1000MB which makes the builds faster and reduces the number of times our build cache gets cleared because we run out of space.
=> optimize build cache by removing large files

proxy/api/src/browser.rs, proxy/api/src/context.rs, proxy/api/src/control.rs, proxy/api/src/http.rs, proxy/api/src/http/control.rs, proxy/api/src/http/diagnostics.rs, proxy/api/src/http/identity.rs, proxy/api/src/http/notification.rs, proxy/api/src/http/project.rs, proxy/api/src/http/project/request.rs, proxy/api/src/http/source.rs, proxy/api/src/lib.rs, proxy/api/src/patch.rs, proxy/api/src/peer.rs, proxy/api/src/process.rs, proxy/api/src/project.rs, proxy/api/src/session.rs
We encapsulate peer related logic (from `librad` and `radicle_daemon`) into a `peer` module to enforce simpler boundaries.
This change tackles the following code issues
* `context::Unsealed` held three fields related to peers which didn’t provide proper encapsulation.
* Configuring a peer was done as part of the session setup in `process`.
* Callers of peer related functionality had to decide whether to access the `librad` peer or the `daemon` peer.
=> proxy: encapsulate peer

cypress/support/ipc-stub.ts, native/index.ts, native/ipc-types.ts, native/proxy-process-manager.ts, ui/App/DiagnosticsScreen.svelte, ui/App/DiagnosticsScreen/Connections.svelte, ui/App/DiagnosticsScreen/ProxyLogs.svelte, ui/App/DiagnosticsScreen/Storage.svelte, ui/src/ipc.ts, ui/src/router/definition.ts
Adding the proxy logs to the diagnostics info screen should help with debugging in case the app was not started from the terminal and we still want to get to the logs.
- show Upstream version in header and add it to copy-to-clipboard button
- don't show redundant peer information in storage tab
- align copy-to-clipboard data shape to what we see on the screen
- use a different icon for notification history tab
- add proxy logs tab and add it to copy-to-clipboard button
=> feat: improve diagnostics screen

ui/App/UserProfileScreen.svelte, ui/src/org.ts, ui/src/org/safe.ts, ui/src/org/theGraphApi.ts
This makes multi-sig org creation much faster than using the Gnosis Safe
transaction API.
Fixes https://github.com/radicle-dev/radicle-upstream/issues/2651.
=> fix: use the graph for Gnosis Safe queries

ui/App/WalletScreen.svelte, ui/App/WalletScreen/ConnectWallet.svelte, ui/App/WalletScreen/LinkAddress.svelte, ui/App/WalletScreen/Transactions.svelte
We move attestation out of the way, so it doesn't block the user from seeing their transactions.
Refs https://github.com/radicle-dev/radicle-upstream/issues/2583 and [user testing findings](https://www.notion.so/Summary-of-friction-along-onboarding-journey-fd32a1171b52449e8014468e8e46b899).
=> feat: move attestation widget beneath wallet balance

ui/src/org.ts, ui/src/org/contract.ts, ui/src/org/safe.ts
After creating an org we need to wait for the Gnosis API to pick it up before we can let the user navigate to the org. 
Otherwise we get an error when querying for anchors:
```
{
"stack": "Error: Not Found\n    at Object.sendRequest (webpack-internal:///./node_modules/@gnosis.pm/safe-service-client/dist/src/utils/httpRequests.js:27:23)\n    at async SafeServiceClient.getPendingTransactions (webpack-internal:///./node_modules/@gnosis.pm/safe-service-client/dist/src/SafeServiceClient.js:281:52)\n    at async Module.getPendingTransactions (webpack-internal:///./ui/src/org/safe.ts:28:22)\n    at async fetchPendingAnchors (webpack-internal:///./ui/src/org.ts:359:17)\n    at async Module.resolveProjectAnchors (webpack-internal:///./ui/src/org.ts:395:26)\n    at async Module.load …
```
=> fix: show newly created org only after Gnosis API picks it up

ui/App/OrgScreen/route.ts
Show anchor buttons in multi-sig orgs if we're the owner of the org.
Fixes a regression introduced in #2450.
=> fix: fix multisig org anchor buttons

design-system/Avatar.svelte
Fixes https://github.com/radicle-dev/radicle-upstream/issues/2629.
=> fix: add default bg color for image avatars with transparency

deny.toml
Temporarily ignore advisory for `lru` crate until it’s fixed in the next `radicle-link` release.
=> temporarily ignore advisory for `lru` crate

.github/workflows/build.yaml, .github/workflows/dist.yaml, .github/workflows/p2p-network-tests.yaml, ci/build.sh, ci/p2p-network-tests.sh
Run builds on Ubuntu 18.04 instead of 20.04. The former has an earlier GLIBC version (v2.27) which makes the built binaries compatible with more systems.
Fixes #2732 and #2731.
=> build on Ubuntu 18.04 for improved GLIBC compatibility

package.json, tsconfig.json, yarn.lock
We set the `skipLibCheck` to `true` in `tsconfig`. Now extending our `tsconfig` with `@tsconfig/svelte` has no effect since we overwrite all options that set by `@tsconfig/svelte`.
=> remove redundant @tsconfig/svelte

native/index.js, package.json
When running the app from the command line during development with `yarn run electron ./native/index.js` we ensure that the NODE_ENV environment variable which configures the app is set to "development".
The NODE_ENV variable was properly set when running the app with `yarn start` but not when running the devnet instantces.
We also enable the `transpileOnly` flag for `ts-node`. This makes the app start quicker.
=> run app in dev mode during development

.github/workflows/dist.yaml, README.md, ci/dist.sh, package.json, scripts/release.ts
Also add documentation on how to find latest development builds. To make this independent of the version we remove the version from the artifact file template.
See [this successful build](https://github.com/radicle-dev/radicle-upstream/runs/5094128807?check_suite_focus=true).
=> build and publish macOS app on main branch builds

docs/development.md, package.json, scripts/devnet.ts
We add a command to the devnet script that allows us to use the radicle tools in the context of a devnet peer when run as `eval $(yarn run devnet shell 1)`. We also at an alias for the devnet script to `package.json` so that we can call it from any directory inside the repository.
=> Add devnet shell command to act as devnet peer

cypress/plugins/nodeManager/plugin.ts, cypress/plugins/nodeManager/shared.ts, cypress/support/nodeManager.ts
Issue the request to connect two nodes in the tests on the client instead of the cypress plugin. This allows us to remove a lot of code.
=> cypress: connect nodes client side

cypress/plugins/nodeManager/plugin.ts, cypress/plugins/nodeManager/shared.ts, cypress/support/nodeManager.ts
Eliminate the Node class and the different associated states. Instead we start and onboard a node in one function that returns the node session and does not hold any state.
=> cypress: eliminate `Node` class

ci/p2p-network-tests.sh, p2p-tests/multiple-project-replication-test.ts
Reproduces replication failure from https://github.com/radicle-dev/radicle-upstream/issues/2703.
The contributor node doesn't replicate the maintainer's default branch:
```
contributor  |   2022-01-06T14:10:37.364875Z ERROR api::http::error: internal server error, we could not find a default branch for 'project2@rad:git:hnrkgr1yb8wkfhmd3sucz9zj77ji6ubospd9y', variant: INTERNAL_SERVER_ERROR, err: Rejection(State(NoDefaultBranch { name: "project2", urn: Urn { id: Oid(6248013d145e2c79b4d97fdd3dea6be9861668fe), path: None } }))
contributor  |     at proxy/api/src/http/error.rs:101
```
Contributor's monorepo tree of the first project:
```
vagrant@ubuntu-focal:/vagrant/p2p-tests/workspace/multiple-project-replication-test/contributor-rad-home/f0b33c27-0053-4e89-9de4-c84b223100ec/git/refs/namespa …
```
=> test: multiple project replication
