app/src/Source.re, app/src/Source.rei, app/src/pages/PageProjects.re
In order to encapsulate the data fetching and management we introduct the concept of a Source which will provide data necessary for the app to display. Potentially this will grow into its own package/library providing the oscoin domain to consumers - like our own mvp app.
* introduce project source
* consume promised based API in projects page
=> Introduce Source for projects

app/README.md, app/package.json
* add test commands to package.json
* document test runner and watch
=> Add test command and docs

app/src/atoms/AtomButton.re
Switch to pointer cursor and fix button states that I broke in the last PR.
=> Fix button styling

app/__tests__/Router_test.re, app/src/App.re, app/src/Router.re, app/src/Router.rei, app/src/Source.re, app/src/Source.rei, app/src/molecules/MoleculePersonCard.re, app/src/molecules/MoleculeProjectCard.re, app/src/pages/PageProject.re, app/src/pages/PageRegisterProject.re, app/src/store/AppStore.re, app/src/store/StoreProject.re, app/src/store/StoreSession.re, app/src/store/ThunkProject.re, app/src/store/ThunkProjects.re, app/src/store/ThunkSession.re
Connects the lose ends by properly routing all important info through the system and store it locally. This means we can now create an account and register a project with it right after and the newly created account is part of the initial member set.
=> Wire project to store

.buildkite/pipeline.yaml, app/.gitignore, app/bsconfig.json, app/graphql_schema.json, app/package.json, app/src/App.re, app/src/pages/PageProject.re, app/src/pages/PageProjects.re, app/src/pages/PageRegisterProject.re, app/yarn.lock
Alternative GraphQL integration with hooks API.
=> Implement GraphQL interactions with hooks

app/src/Topbar.re, app/src/atoms/AtomButton.re, app/src/atoms/AtomLink.re, app/src/molecules/MoleculeModal.re, app/src/pages/PageProjects.re, app/src/particles/ParticleColor.re
Will collect any outstanding visual fixes which don't fit into the other pull requests here.
=> Various visual improvements

app/src/molecules/MoleculeModal.re
This was a regression from #27.
=> Show modal on top of header

app/.gitignore, app/README.md, app/native/main.js, app/package.json, app/yarn.lock
Spits out a `.dmg` via a single command: `yarn dist`.
=> Add and configure electron-builder

.buildkite/run.sh
We had some old yarn cache locations laying around on some of the build agents. Ran this PR on all of the agents for cleanup.
=> Fix build on all build agents

app/README.md, app/package.json, proxy/Cargo.toml, proxy/README.md, proxy/src/main.rs
=> Rename mvp -> radicle-upstream

proxy/README.md
Minor PR to include testing instructions in the README, and to detail invoking the in-memory client.
=> update readme with instructions regarding tests and the in-memory client

README.md
This PR adds a top-level readme with basic information for new committers.
=> Add top-level readme

proxy/src/main.rs, proxy/src/schema/mod.rs
Leftover from merge PR madness.
=> Remove leftover error mod reference

.buildkite/Dockerfile, .buildkite/pipeline.yaml, .buildkite/run.sh, app/cypress/integration/source_browsing.spec.js
=> Move clippy into docker container

.buildkite/pipeline.yaml, .buildkite/run.sh, proxy/src/schema/error.rs
* link target cache instead of copy twice
* run `cargo fmt` to check formatting
* run `cargo check` as well
* switch to shared master cache: https://github.com/oscoin/ci#shared-master-cache
* time all commands
=> Improve CI build times

app/cypress/integration/navigation.spec.js, app/cypress/integration/project_creation.spec.js, app/package.json, app/src/App.svelte, app/src/DesignSystem/Button.svelte, app/src/DesignSystem/DirectoryInput.svelte, app/src/DesignSystem/Input.svelte, app/src/DesignSystem/Text/SmallBold.svelte, app/src/DesignSystem/Text/index.js, app/src/config.js, app/src/hash.js, app/src/pages/CreateProject.svelte, app/src/pages/DesignSystem.svelte, app/src/pages/Projects.svelte, app/yarn.lock
Handle the following edge cases:
- new project + new repo:
- new project + existing repo:
Talk with @julien about error feedback improvements (show it ~~on the right-hand side?~~ below).
=> Improve project creation validations

.gitmodules, app/cypress/integration/navigation.spec.js, proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/schema/error.rs, proxy/src/schema/git.rs, proxy/src/schema/mod.rs
Some changes from our upstream `radicle-surf` dependency. Adjusting to the new APIs and correct tests.
=> Adjust to latest surf changes

proxy/src/schema/mod.rs
Addresses the case where the path selected by the user is already a repository. This is a common case we want to support so users can import their exisiting codebases.
Depends on #82
=> Implement project registration for exisiting repos

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/schema/error.rs, proxy/src/schema/git.rs, proxy/src/schema/mod.rs
Keep up with the librad development to prepare for proper code browsing
integration. We need to align surf versions to avoid compile
inconsistencies. Maybe worth to explore reexport of surf in librad.
=> Bump librad

app/src/components/ProjectTopbar.svelte, app/src/pages/Project.svelte
This makes it more obvious which parameters the component requires
and is consistent with the rest of the codebase.
=> Make Topbar arguments explicit

app/native/main.js
The bundled version (`yarn dist`) wasn't working.
=> Update proxy flag

proxy/src/schema/mod.rs
=> FIx project creation test assertions

app/schema.graphql, proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/main.rs, proxy/src/schema/error.rs, proxy/src/schema/mod.rs, proxy/src/schema/registry.rs
Add mutation for project registration to enable integration in the UI. First part of #81.
=> Project registration endpoint

proxy/.rustfmt.toml, proxy/src/schema/error.rs
=> fmt: Enable match_block_trailing_comma

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/main.rs
Stop-gap solution until we support proper configuration of the network used.
=> Set up Registry client against devnet

proxy/src/schema/mod.rs, proxy/src/schema/registry.rs
=> Add a temporary endpoint for Registry projects

proxy/src/error.rs
=> Correct limits in bytes not characters

app/.eslintrc.json, app/cypress/.eslintrc.json, app/cypress/plugins/index.js, app/package.json, app/scripts/release.js, app/yarn.lock
Implement eslint part of https://github.com/radicle-dev/radicle-upstream/issues/141
- Using `eslint/recommended` as base
- Add cypress configuration int the cypress folder
- Adding a few consensual rules that are already compatible with the codebase
- Remove a strange `raise` statement that was highlighted by eslint
=> Basic eslint configuration

app/.prettierrc, app/package.json
Implement prettier part of https://github.com/radicle-dev/radicle-upstream/issues/141
- add default prettier configuration with svelte plugin (already in package.json)
- apply prettier to svelte files
=> Prettier configuration

app/src/App.svelte, app/src/lib/hotkeys.js
=> Extract hotkey logic into a separate file

app/src/Screens/RegisterProject.svelte, app/src/Screens/RegisterProject/ConfirmTransactionStep.svelte, app/src/Screens/RegisterProject/PickNameStep.svelte
There were a couple of regressions introduced in https://github.com/radicle-dev/radicle-upstream/pull/154 due to lacking tests on out end.
This PR fixes these regressions.
=> Fix project registration UI

proxy/src/error.rs, proxy/src/graphql/api.rs, proxy/src/graphql/error.rs, proxy/src/graphql/project.rs, proxy/src/graphql/schema.rs, proxy/src/lib.rs, proxy/src/main.rs, proxy/src/registry.rs, proxy/tests/common/mod.rs, proxy/tests/graphql_mutation.rs, proxy/tests/graphql_query.rs
=> Implement Basic User Identity mocks

CHANGELOG.md, package.json
=> chore(release): 0.0.5

proxy/src/avatar.rs, proxy/src/lib.rs
For now, we start with a short emoji whitelist. Eventually it will make sense to either add more emojis here, or use emoji ranges.
Closes #181
=> Implement basic avatar generation

proxy/src/main.rs
=> fix: swap proxy flags to respect emulator

cypress/integration/source_browsing.spec.js, proxy/tests/graphql_query.rs
`git-platinum` got updated yesterday, this PR adjusts the tests accordingly.
=> chore: update to latest git-platinum

.buildkite/run.sh, proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/graphql/schema.rs, proxy/src/registry.rs
- Bump radicle-registry-client to latest master
- Update OrgId and ProjectName ::from_string to ::try_from
- Add 'fee' field to transactions
**Note**: Submitting transactions with insufficient funds to pay the indicated fee will result in failed transactions. 
@rudolfs I think I have covered the changes as far as I should go. Note that I have also integrated the latest changes by @xla on `OrgId` and `ProjectName`, now built with `try_from` instead of `from_string`.
Edit: Still have a lot of things to fix here that `cargo build` wasn't reporting.
=> Integrate tx fee

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/error.rs, proxy/src/graphql/error.rs, proxy/src/registry.rs
Catches up with the changes in registry inputs and how they are validated.
Closes #233
=> feat(proxy): convert registry validation errors correctly

DEVELOPMENT.md
@juliendonck just bumped into this while setting up Upstream on his laptop.
=> docs: add a paragraph about external dependencies

.buildkite/Dockerfile, .buildkite/pipeline.yaml, .buildkite/run.sh, package.json, yarn.lock
This has been raised by the Github autmoation and all dependencies have been bumped with `yarn upgrade`.
=> chore(ui): update major depdencies

cypress/support/commands.js, proxy/src/graphql/schema.rs, proxy/src/project.rs, proxy/tests/graphql_mutation.rs, proxy/tests/graphql_query.rs, ui/Screen/RegisterProject.svelte, ui/Screen/UserRegistration.svelte
=> feat(proxy): extend project with org/user relation

proxy/src/avatar.rs, proxy/src/lib.rs, proxy/src/registry.rs
=> chore(proxy): address clippy errors

CHANGELOG.md, ui/App.svelte, ui/DesignSystem/Component/IdentityAvatar.svelte, ui/DesignSystem/Component/ProjectList.svelte, ui/DesignSystem/Component/SourceBrowser/Folder.svelte, ui/DesignSystem/Primitive/Button.svelte, ui/DesignSystem/Primitive/Flex.svelte, ui/Screen/Identity/IdentityCreationSuccess.svelte, ui/Screen/IdentityCreation.svelte, ui/Screen/Profile.svelte, ui/Screen/Project/Breadcrumb.svelte
Partially resolves: https://github.com/radicle-dev/radicle-upstream/issues/175.
- redo empty profile project page (restyle to match current design) 
- fix: use shareable entity identifier for profile ... dropdown copy-to-clipboard
- fix: unregistered project avatar heading
=> Misc basic user identity I visual fixes

proxy/src/avatar.rs, proxy/src/graphql/schema.rs, proxy/tests/graphql_query.rs, ui/Screen/UserRegistration/PickHandleStep.svelte
=> feat(proxy): make avatar generation id based

proxy/src/http.rs, proxy/src/http/org.rs, proxy/src/registry.rs
Implements the get and register org endpoints in the rest api and connects them to the registry as part of #277
=> feat(proxy): org API endpoints

ui/Screen/Identity/IdentityCreationSuccess.svelte, ui/Screen/IdentityCreation.svelte
=> fix(ui): timely session fetch

package.json
=> fix(ui): remove graphiql from start script

ui/DesignSystem/Primitive/Input/Dropdown.svelte, ui/DesignSystem/Primitive/Input/Text.svelte, ui/Screen/CreateProject.svelte, ui/Screen/RegisterProject/PickNameStep.svelte, ui/Screen/UserRegistration/PickHandleStep.svelte
Updated the forms & drop downs to match the design system.
=> fix: style forms to match new design system

package.json, ui/DesignSystem/Component/AdditionalActionsDropdown.svelte, ui/DesignSystem/Primitive/Button.svelte, ui/Screen/DesignSystemGuide.svelte, ui/Screen/Identity/IdentityCreationForm.svelte, ui/Screen/Org/FundMenu.svelte, ui/Screen/Org/MembersMenu.svelte, ui/Screen/Org/ProjectsMenu.svelte, ui/Screen/Profile/ProjectsMenu.svelte, ui/Screen/Profile/SettingsMenu.svelte, ui/Screen/Profile/WalletMenu.svelte, ui/Screen/Project/IssuesMenu.svelte, ui/Screen/Project/RevisionsMenu.svelte, ui/Screen/Project/SourceMenu.svelte
- remove small button size and makes all of them 40px height
- fix all hover & active states
- restyles small overflow button in top bar to match height
=> fix: update buttons to match new design system

ui/DesignSystem/Component/TrackToggle.svelte
Updated the tracking button to have hover/active/tracking states.
Closes #260
=> feat(ui): implement tracking button

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/error.rs, proxy/src/http.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/session.rs, proxy/src/http/transaction.rs, proxy/src/http/user.rs, proxy/src/identity.rs, proxy/src/lib.rs, proxy/src/project.rs, proxy/src/registry.rs, proxy/src/session.rs, ui/src/project.ts, ui/src/user.ts
Exposed the ability to fetch registered projects to check for existence. It currently is exposed for orgs, as the user part is waiting for radicle-dev/radicle-registry#389.
=> feat: fetch registered project

ui/DesignSystem/Primitive/Button.svelte
- Fixing a padding error I introduced in last merge
- removing duplicate padding rule
=> chore(ui): fix button

ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte, ui/Screen/Project/CloneButton.svelte, ui/Screen/Project/Source.svelte
=> feat(ui): implement 'Clone' button

ui/DesignSystem/Component/SourceBrowser/CommitTeaser.svelte, ui/DesignSystem/Component/SourceBrowser/FileDiff.svelte, ui/DesignSystem/Component/SourceBrowser/FileSource.svelte, ui/DesignSystem/Component/SourceBrowser/Readme.svelte, ui/Screen/Project/CloneButton.svelte, ui/Screen/Project/Commit.svelte, ui/Screen/Project/Source.svelte
*old*
*new*
*old*
*new*
*old*
*new*
=> style(ui): project page facelift

proxy/src/http/user.rs, proxy/src/registry.rs, ui/src/user.ts
Corrects a copy-pasta oversight in the user.
=> fix: correct attestion field name in user

proxy/src/http.rs, proxy/src/http/identity.rs, proxy/src/http/session.rs, proxy/src/registry.rs, proxy/src/session.rs, ui/App.svelte, ui/Screen/Profile.svelte, ui/Screen/Profile/Projects.svelte, ui/Screen/Project.svelte, ui/Screen/ProjectRegistration.svelte, ui/Screen/TransactionDetails.svelte, ui/Screen/UserRegistration.svelte, ui/src/org.ts, ui/src/session.ts
=> feat: expose current user orgs list in session

cypress/integration/add_member_to_org.spec.js, cypress/integration/org_registration.spec.js, ui/DesignSystem/Primitive/Input/Text.svelte, ui/Screen/Org/MemberRegistration.svelte, ui/Screen/OrgRegistration.svelte, ui/src/user.ts
=> feat(ui): fix up input avatars for org & add-member-to-org registration flows

package.json
Trying out the "official" solution: https://github.com/electron-userland/electron-builder/issues/2732.
Closes #112
=> fix: bundle missing library libhogweed

cypress/integration/org_registration.spec.js, cypress/integration/user_registration.spec.js, cypress/support/commands.js, proxy/src/http.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/session.rs, proxy/src/http/transaction.rs, proxy/src/http/user.rs, proxy/src/main.rs, proxy/src/registry.rs, proxy/src/registry/transaction.rs, proxy/src/session.rs, ui/App.svelte, ui/src/api.ts, ui/src/session.ts, ui/src/transaction.ts
=> feat(proxy): settings endpoints

cypress/integration/identity_creation.spec.js, ui/DesignSystem/Primitive/Avatar.svelte, ui/DesignSystem/Primitive/Icon/Badge.svelte
=> test(ui): improve identity creation specs

cypress/integration/org_registration.spec.js, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/user.rs, proxy/src/registry.rs, proxy/src/registry/transaction.rs
=> refactor(proxy): check applied transaction result

cypress/integration/user_registration.spec.js
Spec to make sure we check for user handle existence.
=> test(ui): re-enable existing user validation spec

ui/DesignSystem/Component/SourceBrowser/Readme.svelte, ui/Screen/Project.svelte, ui/Screen/Project/Source.svelte
- update the readme to use the markdown component
- full width project page
=> style(ui): project page readme

ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
Tiny fix that prevents an ugly error
=> fix(ui): check for project name length before registration

ui/DesignSystem/Component/SupportButton.svelte, ui/DesignSystem/Component/index.js, ui/DesignSystem/Primitive/Input/Text.svelte, ui/Screen/DesignSystemGuide.svelte, ui/Screen/Profile/Projects.svelte, ui/Screen/Project/SourceMenu.svelte
=> style(ui): support button styling

native/main.js
=> fix: proxy lifecycle on macOS

cypress/integration/project_creation.spec.js, cypress/integration/project_source_browsing.spec.js, cypress/support/commands.js, package.json, yarn.lock
Grab-bag of spec improvements:
- fix flaky specs
- use `pick` shorthand consistently
=> refactor(ui): improve cypress spec reliability

ui/Screen/ProjectCreation.svelte
=> Fix project creation modal margins

DEVELOPMENT.md
Some parts were very out of date.
=> docs: update developer documentation

ui/DesignSystem/Component/SourceBrowser/Readme.svelte, ui/src/source.ts
=> Fix plain README being rendered in HTML

cypress/integration/project_creation.spec.js
=> Fix flaky spec

cypress/integration/org_member_addition.spec.js, cypress/support/commands.js, proxy/src/http/control.rs, proxy/src/registry.rs, proxy/src/registry/transaction.rs, ui/DesignSystem/Component/HorizontalMenu.svelte, ui/DesignSystem/Component/HorizontalMenu/MenuItem.svelte, ui/Screen/Org/MemberRegistration.svelte, ui/Screen/Org/Members.svelte, ui/src/__mocks__/api.ts, ui/src/org.test.ts, ui/src/org.ts
Implements actual member registration and replaces the org member list mock. It also adds a new control endpoint to add additional users so that adding members can be tested in cypress.
Related to #349
=> Register member endpoint integration

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/registry.rs
=> chore(proxy): bump registry crate

.buildkite/clippy.sh, .buildkite/pipeline.yaml, .buildkite/run.sh, proxy/src/avatar.rs, proxy/src/coco.rs, proxy/src/http.rs, proxy/src/registry/transaction.rs
* Separated out the clippy and fmt commands so that they can run in a separate CI step. That allows them to run in parallel.
* Added a doc check.
* Fixed some links that were breaking the docs.
=> chore(ci): improve proxy steps

cypress/integration/routing.spec.js, cypress/integration/settings_specs.js, ui/Hotkeys.svelte, ui/Screen/Org.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/495.
=> fix(ui): fix org navigation

cypress/integration/identity_creation.spec.js, cypress/support/commands.js, proxy/src/http/identity.rs, proxy/src/http/source.rs, proxy/src/identity.rs, ui/DesignSystem/Component/Sidebar.svelte, ui/Screen/DesignSystemGuide.svelte, ui/Screen/IdentityCreation/Form.svelte, ui/Screen/IdentityCreation/Success.svelte, ui/Screen/Profile.svelte, ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte, ui/Screen/UserRegistration/PickHandleStep.svelte, ui/src/identity.ts, ui/src/transaction.ts
=> feat(ui): removes display name and avatar url

public/global.css, ui/DesignSystem/Component/BigHeader.svelte, ui/DesignSystem/Component/List.svelte, ui/Screen/Project/Issue.svelte, ui/Screen/Project/Issues.svelte, ui/Screen/Project/Source.svelte, ui/Screen/Settings.svelte
- converted the global spacing variables to use rem
- added a global padding variable
- Use that padding variable consistently in existing screen
- Update the Project source page to have more consistent padding.
=> chore(ui): unify layout variables

cypress/integration/project_registration.spec.js, proxy/src/http.rs, proxy/src/http/identity.rs, proxy/src/http/session.rs, proxy/src/session.rs, ui/Screen/Org.svelte, ui/Screen/Org/Onboard.svelte, ui/Screen/Org/Projects.svelte, ui/Screen/Org/ProjectsMenu.svelte, ui/Screen/Profile/Projects.svelte, ui/Screen/Project.svelte
This should cover all current use cases of `session.permissions.registerProject` as mentioned in #371
=> feat: apply project registration permission

ui/DesignSystem/Component/Transaction/Center.svelte
=> fix(ui): transaction center should hide when clicking outside

ui/DesignSystem/Component/Notification.svelte, ui/DesignSystem/Component/NotificationFaucet.svelte
fixes issue #486 
Also added Flip animation -> when closing a notification, the ones stacked on top slide down.
=> chore(ui): update Notifications to stack properly

public/colors.css, ui/DesignSystem/Component/AdditionalActionsDropdown.svelte, ui/DesignSystem/Component/Sidebar.svelte, ui/DesignSystem/Component/Sidebar/AddOrgButton.svelte
- Fix sidebar gradient in dark mode: close #514 
- change cursor to not-allowed on hover of add org button -> closes #516
=> chore(ui): Round of ui fixes

proxy/src/http.rs, proxy/src/http/avatar.rs
=> chore(proxy): crush build times

ui/App/TransactionCenter.svelte, ui/DesignSystem/Component/Transaction/Center.svelte
=> style(ui): add transaction center animations

ui/Screen/Settings.svelte
=> chore(ui): add legal section to settings

ui/DesignSystem/Component/EmptyState.svelte, ui/DesignSystem/Primitive/Button.svelte, ui/Screen/Org/Projects.svelte
=> chore(ui): transparent button background

ui/DesignSystem/Primitive/Markdown.svelte
=> style(ui): Improve markdown styling

package.json, ui/DesignSystem/Component/HorizontalMenu/MenuItem.svelte, ui/Screen/Project/Source.svelte, yarn.lock
=> refactor(ui): get rid of weird router hacks

proxy/src/http.rs, proxy/src/http/control.rs, proxy/src/http/error.rs, proxy/src/http/project.rs
=> feat(proxy): authorized endpoints

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/coco.rs, proxy/src/coco/source.rs, proxy/src/http/control.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/source.rs, proxy/src/project.rs
I decided to create a PR against yours to highlight the changes I was considering making. We can go over it on a call if that would help :)
=> Update Stats PR

native/main.js
Auto-hides the annoying menu bar. Tested on Linux only.
=> feat(ui): remove application menu-bar

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/coco/source.rs, proxy/src/http.rs, proxy/src/http/identity.rs, proxy/src/http/session.rs, proxy/src/http/source.rs, proxy/src/session.rs, ui/DesignSystem/Component/SourceBrowser/FileSource.svelte, ui/src/source.ts
Closes #461 
This implements syntax highlighting for source code, in the backend. It handles light/dark mode correctly.
=> feat: syntax highlighting

public/elevation.css, ui/Screen/Project/CloneButton.svelte
Using the [SmoothShadow Figma plugin](https://www.figma.com/community/plugin/788830704169694737/SmoothShadow) I redid the box-shadows to be more smooth.
=> refactor(ui): smoother box shadows

ui/Screen/Project/CloneButton.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/491 https://github.com/radicle-dev/radicle-upstream/issues/557.
=> fix(ui): fix clone button link

ui/DesignSystem/Component/Header/Large.svelte
=> refactor(ui): remove @ from profile header

ui/DesignSystem/Component/TrackToggle.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/645.
=> ui(style): remove peer count from track button

ui/DesignSystem/Primitive/Button.svelte, ui/DesignSystem/Primitive/Input/Directory.svelte, ui/Screen/Project/CheckoutButton.svelte, ui/Screen/Project/Source.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/604.
=> feat(ui): prepare project checkout visuals

ui/DesignSystem/Component/HorizontalMenu/MenuItem.svelte
Made the non selected nav items bold, to match the Figma designs.
=> Fix navgation font weight

ui/DesignSystem/Component/Dropdown.svelte, ui/DesignSystem/Component/Dropdown/Option.svelte, ui/DesignSystem/Component/List.svelte, ui/DesignSystem/Component/RadioOption.svelte, ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte, ui/DesignSystem/Component/SupportButton.svelte, ui/DesignSystem/Component/Transaction/Center.svelte, ui/DesignSystem/Primitive/Button.svelte, ui/DesignSystem/Primitive/Input/Text.svelte, ui/DesignSystem/Primitive/Input/Textarea.svelte, ui/Screen/Project/CheckoutButton.svelte, ui/Screen/UserRegistration/PickHandleStep.svelte
Simple PR that just makes all borders in overlays and forms to 1px and fixes the dropdown selection background colors.
Closes #647 Closes #652
=> refactor(ui): consistent border colors and border widths

proxy/src/http/org.rs, proxy/src/http/user.rs, proxy/src/registry.rs
=> feat(proxy): expose the account id for user and org

proxy/src/coco/source.rs, proxy/src/http/source.rs, ui/src/source.ts
=> fix(ui): show correct commit branch

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/registry.rs, proxy/src/registry/transaction.rs
Integration for https://github.com/radicle-dev/radicle-registry/issues/587
It will be useful to validate, in the UI, if an account exists on chain.
=> feat(proxy): Integrate registry account_exists check

cypress/integration/project_source_browsing.spec.js, cypress/support/commands.js, proxy/src/coco/control.rs, proxy/src/coco/source.rs, proxy/src/http/control.rs, proxy/src/http/org.rs, proxy/src/http/project.rs, proxy/src/http/source.rs, ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte, ui/DesignSystem/Primitive/Icon/Branch.svelte, ui/DesignSystem/Primitive/Icon/Commit.svelte
Adds tests covering different peer selection in repository selector.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/289.
=> test(ui): add repository selector integration tests

cypress/integration/project_creation.spec.js, ui/Screen/ProjectCreation.svelte
=> fix(ui): project registration button permissions

cypress/integration/project_source_browsing.spec.js, ui/Screen/Project/Commit.svelte, ui/Screen/Project/Commits.svelte, ui/Screen/Project/Source.svelte
Turns out the test was not flaky, but the `navigate_on_ready` function had a race condition.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/689.
=> fix(ui): race condition in commit navigation

ui/Screen/Profile/Wallet.svelte
Shows the account id exposed by the session on the profile wallet screen.
Closes #684
=> feat(ui): show the actual identity accountId

DEVELOPMENT.md
It's already documented in step no. 5.
=> docs: remove duplicate line

proxy/Cargo.lock, proxy/Cargo.toml, proxy/src/coco/control.rs
Only the latest & greatest will do for https://github.com/radicle-dev/radicle-upstream/issues/601.
=> chore(proxy): bump radicle-link

ui/Screen/Org/Fund.svelte, ui/Screen/Profile/Wallet.svelte, ui/src/account.ts
=> feat(ui): Show actual free balance on wallet screens

.buildkite/run.sh
These are the shorter and quicker test, ultimately we want to break them out.
=> refactor(ci): run checks and lints first

cypress/integration/project_source_browsing.spec.js, ui/DesignSystem/Component/AdditionalActionsDropdown.svelte, ui/DesignSystem/Component/SourceBrowser/FileSource.svelte, ui/DesignSystem/Primitive/Icon/Spinner.svelte, ui/DesignSystem/Primitive/Input/Textarea.svelte, ui/Screen/Profile/Projects.svelte, ui/Screen/Settings.svelte
- fixes spinner not spinning -> closes #733 
- adds binary content placeholder -> closes #327 
- fix settings seed input -> closes #746 
- fix tooltip on greyed out dropdown item -> closes #744
=> chore(ui): bug fixing

public/typography.css, ui/DesignSystem/Component/Notification.svelte, ui/DesignSystem/Component/ProjectCard.svelte, ui/DesignSystem/Component/Urn.svelte
- fix notification vertical alignment
- fix for projectCard description that didn't overflow properly
- add line height to header classes
- fix Urn styles so that the strings have the right colors
=> fix(ui): clean up

ui/DesignSystem/Component/AdditionalActionsDropdown.svelte, ui/DesignSystem/Component/Copyable.svelte, ui/DesignSystem/Component/Header/Large.svelte, ui/DesignSystem/Component/Transaction.svelte, ui/DesignSystem/Component/Urn.svelte, ui/DesignSystem/Component/Wallet/Receive.svelte, ui/Screen/DesignSystemGuide.svelte, ui/Screen/Discovery/Project.svelte, ui/Screen/Project/Source.svelte
Adds a optional notification to `<Copyable />` and adds those where we use `<Urn />`
closes #751
=> feat(ui): add notification when copying urn

public/typography.css, ui/Screen/DesignSystemGuide.svelte
Just some tiny cleanup of the styles
=> fix(style): typography tweaks

proxy/api/src/http/project.rs, proxy/api/src/project.rs, ui/DesignSystem/Component/Badge.svelte, ui/DesignSystem/Component/ProjectCard.svelte, ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte, ui/DesignSystem/Component/index.js, ui/Screen/Profile/Projects.svelte, ui/Screen/Project/Source.svelte, ui/src/__mocks__/api.ts, ui/src/badge.ts, ui/src/project.ts
This adds the maintainer badge to maintainers in the revision selector and the projects page.
=> feat: maintainer badge

proxy/api/src/main.rs, proxy/coco/src/announce.rs
Since HashSet is the natural way of making sure announcements are unique
we use them in the functions.
=> Use HashSet

proxy/Cargo.lock, proxy/api/Cargo.toml, proxy/api/src/http.rs, proxy/api/src/http/avatar.rs, proxy/api/src/http/error.rs, proxy/api/src/http/identity.rs, proxy/api/src/http/project.rs, proxy/api/src/http/session.rs
=> refactor(proxy): drop warp documentation

proxy/Cargo.lock, proxy/api/src/main.rs, proxy/api/src/session.rs, proxy/api/src/session/announcements.rs, proxy/api/src/session/settings.rs, proxy/coco/Cargo.toml, proxy/coco/src/announcement.rs, proxy/coco/src/error.rs
Make the caching of announcements a session concern.
Closes #857
=> refactor(proxy): move caching out of coco crate

proxy/api/src/project.rs
=> chore(proxy): remove unnecessary HashMap

cypress/integration/project_creation.spec.js, ui/DesignSystem/Primitive/Input/Directory.svelte, ui/DesignSystem/Primitive/Input/Text.svelte, ui/Modal/ProjectCreation.svelte, ui/src/__mocks__/api.ts, ui/src/project.test.ts, ui/src/project.ts, ui/src/source.ts
=> refactor(ui): new project modal validations

native/ipc.js, native/main.js, ui/Screen/Settings.svelte
As specified in: https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=4147%3A7518.
=> feat(ui): show app version

QA.md
Follow-ups for: https://github.com/radicle-dev/radicle-upstream/pull/922.
=> docs: add additional explanations to QA checklist

QA.md, ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/933.
=> chore(ui): hide tags in production builds

cypress/integration/project_creation.spec.js, proxy/api/src/http/error.rs, proxy/coco/src/error.rs, proxy/coco/src/source.rs, ui/src/project.ts
Closes: https://github.com/radicle-dev/radicle-upstream/issues/614.
=> fix(ui): handle repositories with no branches gracefully

QA.md
Refs: https://github.com/radicle-dev/radicle-upstream/issues/912.
=> chore(docs): improve remote helper hint check docs

proxy/Cargo.lock, proxy/api/src/context.rs, proxy/api/src/error.rs, proxy/api/src/http/control.rs, proxy/api/src/http/error.rs, proxy/api/src/http/project.rs, proxy/api/src/main.rs, proxy/coco/Cargo.toml, proxy/coco/src/error.rs, proxy/coco/src/keystore.rs, proxy/coco/src/lib.rs, proxy/coco/src/peer/announcement.rs, proxy/coco/src/project.rs, proxy/coco/src/project/checkout.rs, proxy/coco/src/source.rs, proxy/coco/src/state.rs, proxy/coco/tests/common.rs
=> feat(proxy): configure include file during checkout

cypress/integration/onboarding.spec.js, cypress/integration/project_creation.spec.js, ui/src/onboarding.ts, ui/src/project.ts, ui/src/validation.ts
=> fix(ui): improve identity and project name validation

proxy/coco/src/request/waiting_room.rs
The delta should only be a concern for `Requested` states rather than `Created` or `Found` states. This is because `Requested` states can live long and need to be retried. Whereas `Created` and `Found` states are once off and should always be returned immediately.
=> fix(proxy): move delta to config

ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
=> fix(ui): truncate revision selector content

ui/DesignSystem/Primitive/Input/Text.svelte, ui/Modal/SearchModal.svelte
=> fix(ui): show search input hint on empty input

cypress/integration/project_source_browsing.spec.js, proxy/api/src/http/project.rs
We added some new files for upcoming test cases.
=> chore: bump git-platinum

ui/DesignSystem/Component/ConnectionStatusIndicator.svelte, ui/DesignSystem/Component/Sidebar.svelte, ui/src/localPeer.ts
=> refactor(ui): move local peer status to store

package.json, ui/DesignSystem/Component/List.svelte, ui/DesignSystem/Component/Remote.svelte, ui/DesignSystem/Component/WithContext.svelte, ui/Screen/Profile/Tracking.svelte, ui/src/onboarding.ts, ui/src/overlay.ts, ui/src/project.ts, ui/src/source.ts, ui/src/validation.ts
Make the build fail on eslint warnings and fix existing eslint warnings.
Refs #696
=> chore(ci): fail build on eslint warnings

proxy/coco/src/request/waiting_room.rs
=> fix(proxy): fix waiting room logic for next query

proxy/Cargo.lock, proxy/api/Cargo.toml, proxy/coco/Cargo.toml
=> Bump radicle-surf to v0.5.0

native/main.js
We forgot to remove this in https://github.com/radicle-dev/radicle-upstream/pull/944.
=> chore(ui): remove footgun leftovers

ui/Screen/Profile.svelte
Regression introduced in #1104 - thanks @rudolfs for the spot.
=> fix(ui): revive avatar in profile

ui/src/profile.ts
Regression from #1105 - thanks @rudolfs for the :eyes:
=> fix(ui): correct check for listening

proxy/api/src/http/session.rs, proxy/api/src/session/settings.rs, ui/Screen/DesignSystemGuide.svelte, ui/src/session.test.ts
=> chore(proxy): update default seed PeerId

ui/DesignSystem/Primitive/Input/Text.svelte, ui/Modal/Search.svelte
=> style(ui): style search box

public/global.css, ui/DesignSystem/Component/KeyHint.svelte, ui/DesignSystem/Primitive/Button.svelte
=> style(ui): improve legibility

ui/DesignSystem/Component/ConnectionStatusIndicator.svelte
=> fix(ui): pluralize peer count correctly

ui/DesignSystem/Component/Copyable.svelte, ui/Screen/Onboarding/Success.svelte, ui/Screen/Settings.svelte
- added peerID to settings
- fix copy in onboarding
=> feat(ui): add peerId to settings

.buildkite/run.sh, yarn.lock
This should have been done in: https://github.com/radicle-dev/radicle-upstream/pull/1121.
=> chore(ui): run yarn to refresh yarn.lock

proxy/api/src/http/error.rs
Use `thiserror` for routing error messages
=> refactor(proxy): use thiserror for routing error messages

ui/DesignSystem/Component/FollowToggle.svelte, ui/DesignSystem/Primitive/Button.svelte, ui/Modal/ManagePeers/Peer.svelte, ui/Modal/ManagePeers/PeerFollowRequest.svelte, ui/Screen/DesignSystemGuide.svelte, ui/Screen/Profile/Following.svelte, ui/Screen/Project.svelte
DRY up the component and adjust styles to match designs.
Closes: #1157.
- Demo:
=> style(ui): refactor FollowToggle component

package.json
=> fix(ci): don’t stall ci builds when tests fail

QA.md, cypress/integration/settings_specs.js, proxy/api/src/http/session.rs, proxy/api/src/session.rs, ui/Screen/Settings.svelte, ui/src/session.ts
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1192.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1188.
=> chore(ui): remove "clear session" button from settings

native/main.ts, package.json, rollup.electron.js, yarn.lock
To make `native/main` easier to work with we convert it to TypeScript
=> chore(ui): convert `native/main` to TypeScript

proxy/coco/src/project/create/validation.rs
And don't set it on an existing project
=> fix(proxy): only set upstream branch on new project

cypress/integration/project/peer_management.spec.ts, ui/Modal/ManagePeers.svelte, ui/Modal/ManagePeers/Peer.svelte, ui/Modal/ManagePeers/PeerFollowRequest.svelte
=> fix(ui): remove project name from manage remote modal

ui/src/error.ts
As part of #1187 we show notifications for all unhandled exceptions.
=> feat(ui): log unhandled exceptions

ui/DesignSystem/Component/Header/Large.svelte, ui/DesignSystem/Component/PeerId.svelte, ui/DesignSystem/Component/index.ts, ui/DesignSystem/Primitive/Icon/Computer.svelte, ui/DesignSystem/Primitive/Icon/index.ts, ui/Screen/Onboarding/Success.svelte, ui/Screen/Settings.svelte
- changed in header
- changed in settings
- changed in onboarding
closes #1259
=> style(ui): add 💻 icon to peerId

cypress/integration/project/follow.spec.ts, cypress/support/commands.ts, ui/Modal/Search.svelte, ui/Screen/Profile/Following.svelte
We add a test for following and unfollowing a project.
I’m not sure whether this allows us to close #1262. Maybe I’m missing some test cases.
=> chore(ui): add basic tests for project following

ui/DesignSystem/Component/List.svelte, ui/Screen/Profile/Following.svelte
=> fix(ui): specify List keys

proxy/api/src/http/error.rs, proxy/api/src/http/project.rs, proxy/coco/src/project/create/validation.rs
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1249.
=> feat(proxy): push all branches when creating a project

proxy/Cargo.lock, proxy/coco/Cargo.toml
=> chore(proxy): bump surf dep

proxy/coco/src/peer/announcement.rs
=> fix(proxy): fix announcemnets

ui/Screen/Settings.svelte
=> chore(ui): fix setting bottom padding

scripts/reset-state.sh
Related to the change we did in: https://github.com/radicle-dev/radicle-upstream/pull/1303.
=> chore: update reset script

ui/Modal/ManagePeers.svelte, ui/Modal/Search.svelte, ui/Screen/Settings.svelte
=> fix(ui): remove paste shortcut

proxy/Cargo.lock, proxy/coco/Cargo.toml
Closes #1309 
***
Also switches to crate version of surf.
=> chore(proxy): bump deps

CHANGELOG.md, package.json
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1312.
=> chore(release): 0.1.0

ui/Screen/Bsod.svelte, ui/Screen/Settings.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1338.
=> fix(ui): fix external support links

proxy/api/src/main.rs
=> chore(proxy): filter log lines from `quinn` create

native/main.ts
=> fix(ui): remove logging on opening external links

QA.md
=> fix(docs): document that AppImage needs to be made executable

ui/Screen/Project/Source/CheckoutButton.svelte
=> fix(ui): align checkout modal with button

proxy/Cargo.lock
=> fix(proxy): update to radicle-surf v0.5.3

cypress/integration/project/follow.spec.ts, ui/Modal/Search.svelte
=> fix(ui): trim whitespace from search input

ui/DesignSystem/Component/RemoteHelperHint.svelte, ui/Screen/Onboarding/Success.svelte
The location of the guide got changed in [radicle-docs#35](https://github.com/radicle-dev/radicle-docs/pull/35)
Closes #1380
=> fix(ui): Update doc link

proxy/Cargo.lock, proxy/coco/Cargo.toml
=> chore: update radicle link

ui/Screen/Bsod.svelte
=> chore(ui): correct support link on BSOD

cypress/integration/settings.spec.ts, proxy/api/src/session/settings.rs, public/colors.css, ui/Theme.svelte, ui/src/__mocks__/api.ts, ui/src/settings.ts
Adjusted colors. Closes #1430 
~~This doesn't make dark theme default~~ now it does
=> chore(ui): correct colors with spec

ui/Hotkeys.svelte
Closes #1417 
Any opened modal or the design system guide will be closed if another one is opened via shortcuts.
=> fix(ui): open only one modal at a time

DEVELOPMENT.md
Fixup for the PR that we rushed in during the release.
Closes: #1410
=> docs: link to repositories that have to be updated upon release

package.json, yarn.lock
=> Add ethers-cli dependency

scripts/reset-state.sh
The radicle directory has now moved to radicle-link.
=> fix(proxy): update reset script

ui/DesignSystem/Component/ConnectionStatusIndicator.svelte, ui/DesignSystem/Component/EmptyState.svelte, ui/DesignSystem/Component/SidebarLayout.svelte, ui/Screen/Settings.svelte
=> improvements(ui): Low hanging 🍓 improvements

proxy/coco/src/peer/subroutines.rs, proxy/coco/tests/gossip.rs
This is stacked on top of tyn for review pleasure of one @FintanH 
=> tracking memes: Announce after clone

proxy/api/src/context.rs, proxy/api/src/http/identity.rs, proxy/api/src/http/project.rs, proxy/api/src/http/project/request.rs, proxy/api/src/http/session.rs, proxy/api/src/http/source.rs
=> chore: spawn peer run explicitly in tests

cypress/plugins/nodeManager/plugin.ts
=> refactor(tests): remove unused code

.buildkite/run.sh, rollup.electron.js, tsconfig.json
We fix the bundling of the electron main process file and it to the tests.
=> fix(build): fix bundling of electron main files

proxy/api/src/error.rs, proxy/api/src/http.rs, proxy/api/src/http/error.rs, proxy/api/src/service.rs, proxy/coco/src/source.rs
Finishes https://github.com/radicle-dev/radicle-upstream/pull/1685#discussion_r598609463
=> Fix errors not following the lowercase convention

.buildkite/run.sh
Instead of having to clear caches manually on the build agent we do this as part of the build script.
This code was adapted from the [registry][].
[registry]: https://github.com/radicle-dev/radicle-registry/blob/00436dc9b2fad0ad96c2e562f76873d0aa21a2c0/ci/run#L27-L36
=> fix(ci): automatically clean cache when it is almost full

package.json
We fix the `test:integration:debug` script. A regression introduced in #1679.
=> fix(build): fix test:integration:debug script

ui/src/path.ts
Remove unused code in `ui/src/paths`
=> refactor(ui): remove unused code in `ui/src/paths`

ui/DesignSystem/Component/BranchBox.svelte, ui/DesignSystem/Component/CompareBranches.svelte, ui/DesignSystem/Component/Copyable.svelte, ui/DesignSystem/Component/Header/Back.svelte, ui/DesignSystem/Component/List.svelte, ui/DesignSystem/Component/SegmentedControl.svelte, ui/DesignSystem/Component/index.ts, ui/DesignSystem/Primitive/Button.svelte, ui/Screen/DesignSystemGuide.svelte
This is a collection of design improvements and additions that are backported from the merge request work.
* Add `BranchBox` and `CompareBranches` components
* More specific selectors in the `Header/Back` component. This avoids changing the `fill` property of other SVGs
* Export `copy` from the `Copyable` component so it can be accessed from the outside.
* Drop `overflow: hidden` from the `List` component. This allows popups in the List component to flow outside. This requires us to set the border radius for the list items.
* Add a border to `SegmentedControl`.
* Make border color of transparent button transparent.
=> feat(ui): design improvements from merge request work

Cargo.lock, proxy/coco/Cargo.toml
To keep up with the latest network improvements.
=> chore(proxy): update link dependencies

native/proxy-process-manager.ts
We try to fix flaky tests (#1409) on MacOS by waiting for the output streams of the managed process to end before we return. This should ensure that all the buffered IO has been accounted for.
=> fix(ui): wait for process streams to end

cypress/integration/project/follow.spec.ts, cypress/integration/search.spec.ts, ui/Modal/Search.svelte, ui/src/urn.ts
Fixes https://github.com/radicle-dev/radicle-upstream/issues/1771.
=> fix(ui): clear search input after every search

public/typography.css, ui/DesignSystem/Component/SegmentedControl.svelte, ui/DesignSystem/Component/SourceBrowser/FileView.svelte, ui/DesignSystem/Component/SourceBrowser/FileView/Root.svelte, ui/DesignSystem/Component/Wallet/Panel.svelte, ui/Screen/DesignSystemGuide.svelte, ui/Screen/Profile/Following.svelte, ui/Screen/Project/Source/Code.svelte
=> style(ui): UI issue fixes

native/index.ts, native/nativeCustomProtocolHandler.test.ts, native/nativeCustomProtocolHandler.ts
This fixes deep-links not opening after unlocking the app.
Fixes https://github.com/radicle-dev/radicle-upstream/issues/1773.
=> fix(ui): fix deep-links on macOS

ui/Screen/Bsod.svelte
=> style(ui): fix BSOD support button

cypress/integration/project/creation.spec.ts, proxy/api/src/http/source.rs, ui/src/source.ts
=> fix(proxy): properly decode repo paths on project creation

ui/src/localPeer.ts
We validate the event payloads from the proxy so that they match the types we provide. This also requires us to rename the `peer` field of `ProjectUpdated` to `provider`.
=> fix(ui): validate event payload and fix fields

cypress/integration/networking.spec.ts
Workaround for:
https://buildkite.com/monadic/radicle-upstream/builds/8715#96021d44-1ecb-467d-967a-58697604c01c
https://buildkite.com/monadic/radicle-upstream/builds/8715#1354db83-ff50-4454-9832-be83f46b6397
Fixes: https://github.com/radicle-dev/radicle-upstream/issues/1744.
=> chore(ci): add workaround for flaky test

Cargo.lock, proxy/api/Cargo.toml, proxy/api/src/bin/git-remote-rad.rs, proxy/coco/Cargo.toml, proxy/coco/src/config.rs, proxy/coco/src/peer.rs, proxy/coco/src/peer/announcement.rs, proxy/coco/src/peer/run_state.rs, proxy/coco/src/state.rs, proxy/coco/src/state/error.rs
Pulls in critical network improvements.
=> chore(proxy): Update to latest link

QA.md
We remove inconsequential and automated tests from the QA script.
=> fix(dev): slim down release QA script

package.json, ui/Screen/Project.svelte, ui/src/bacon.ts, ui/src/localPeer.ts, yarn.lock
A proof of concept that shows how a stream primitive from BaconJS can simplify the event logic.
=> Use baconjs for event handling

ui/DesignSystem/Component/PeerSelector.svelte, ui/DesignSystem/Component/PeerSelector/Peer.svelte, ui/Modal/ManagePeers.svelte, ui/Modal/ManagePeers/Peer.svelte, ui/src/project.ts, ui/src/proxy/project.ts, ui/src/screen/project.ts
Add project peers endpoint to proxy client.
=> refactor(ui): add project peers endpoint to proxy client

ui/src/theGraphApi.ts
* Use `fetchPolicy` default option
* Throw an error instead of returning an invalid endpoint URI. Throwing the error also results in the UI showing it.
* Fix type annotation from tuple (`[Org]`) to array (`Org[]`)
=> improvements to the Graph module

Cargo.lock, cypress/integration/project/patches.spec.ts, cypress/support/commands.ts, cypress/support/nodeManager.ts, proxy/api/Cargo.toml, proxy/api/src/http/project.rs, proxy/api/src/lib.rs, proxy/api/src/patch.rs, proxy/api/src/project.rs, ui/DesignSystem/Component/CompareBranches.svelte, ui/DesignSystem/Component/EmptyState.svelte, ui/Screen/NetworkDiagnostics.svelte, ui/Screen/NetworkDiagnostics/ConnectedPeers.svelte, ui/Screen/NetworkDiagnostics/WaitingRoom.svelte, ui/Screen/Project/BackButton.svelte, ui/Screen/Project/Source.svelte, ui/Screen/Project/Source/AcceptPatchButton.svelte, ui/Screen/Project/Source/CheckoutButton.svelte, ui/Screen/Project/Source/CheckoutPatchButton.svelte, ui/Screen/Project/Source/Patch.svelte, ui/Screen/Project/Source/PatchButton.svelte, ui/Screen/Project/Source/PatchCard.svelte, ui/Screen/Project/Source/PatchList.svelte, ui/Screen/Project/Source/PatchLoaded.svelte, ui/src/project/patch.ts, ui/src/proxy/project.ts, ui/src/router.ts, ui/src/screen/project/source.ts, ui/src/source.ts
Update #1876 with latest master. This means updating patches to use the new router. The diff for this is useless because it also contains all the new patches code.
=> Integrate patches with router

ui/DesignSystem/Component/Wallet/WrongNetwork.svelte
=> style(ui): fix margin top on wrong-network-window

ui/DesignSystem/Component/Modal.svelte, ui/Modal/Funding/Onboarding.svelte, ui/Modal/NewProject.svelte, ui/Modal/Transaction.svelte, ui/Modal/Wallet/QRCode.svelte
=> refactor(ui): align all modals

ui/DesignSystem/Component/Modal.svelte
=> style(ui): center text on modals

CONTRIBUTING.md, DEVELOPMENT.md
A couple of improvment to the contribution and development guides
=> feat(dev): improve contribution guide

ui/DesignSystem/Component/Copyable.svelte, ui/DesignSystem/Component/Dropdown.svelte, ui/DesignSystem/Component/RadicleId.svelte, ui/DesignSystem/Component/StyledCopyable.svelte
We backport some standalone changes to components from #1813.
=> Backport some component changes from orgs branch

ui/Screen/Bsod.svelte, ui/src/style.ts
Backport small changes from orgs to make that [pr](https://github.com/radicle-dev/radicle-upstream/pull/1813) smaller.
=> refactor(ui): fix smaller issues

Cargo.lock, proxy/api/Cargo.toml, proxy/api/src/project.rs
The updated link announces user updates.
:tada:#2000!:tada:
=> chore(deps): update radicle-link

ui/DesignSystem/Component/Wallet/WrongNetwork.svelte, ui/Screen/Wallet.svelte
In preparation for [orgs](https://github.com/radicle-dev/radicle-upstream/pull/1813/).
=> chore(ui): improve wallet mismatch wording

ui/src/org.ts, ui/src/org/safe.ts
We extract gnosis safe specific code into it’s own module. Part of #2025
=> refactor: extract gnosis safe specific code

ui/src/wallet.ts
Thanks to @pedrouid we have a dedicated Walletconnect bridge now. 🙇 
Closes https://github.com/radicle-dev/radicle-upstream/issues/2052.
=> fix: use dedicated walletconnect bridge

ui/Modal/Org/AnchorProject.svelte, ui/src/org.ts, ui/src/org/contract.ts, ui/src/org/safe.ts, ui/src/org/theGraphApi.ts
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2025.
=> refactor: clean up orgs data layer

ui/src/org.ts
Forgot to do this for org creation as well.
=> fix: improve org creation notification

ui/Modal/ManagePeers.svelte, ui/Screen/Settings.svelte, ui/Screen/Wallet/Pool/Outgoing/Support.svelte
=> Copy: Fix text in settings

ui/DesignSystem/ProjectAnchorPopover.svelte, ui/Screen/Org.svelte, ui/Screen/Org/Projects.svelte, ui/Screen/Org/UnresolvedAnchorList.svelte, ui/Screen/Profile/Following.svelte, ui/src/org.ts, ui/src/router/definition.ts
=> improvement: differentiate pending anchors in orgs

ui/DesignSystem/Avatar.svelte
Small visual update to org avatars
=> style(ui): update org avatar border radius to be more round

ui/App.svelte, ui/DesignSystem/ProjectAnchorPopover.svelte, ui/DesignSystem/RadioOption.svelte, ui/DesignSystem/Sidebar/OrgList.svelte, ui/Modal/Org/AnchorProject.svelte, ui/Modal/Org/Create.svelte, ui/Modal/Transaction.svelte, ui/Screen/Org.svelte, ui/Screen/Org/OrgHeader.svelte, ui/Screen/Org/Projects.svelte, ui/Screen/Org/ProjectsMenu.svelte, ui/Screen/Settings.svelte, ui/Screen/SingleSigOrg.svelte, ui/src/ethereum/index.ts, ui/src/org.ts, ui/src/org/contract.ts, ui/src/org/safe.ts, ui/src/org/theGraphApi.ts, ui/src/project.ts, ui/src/router/definition.ts, ui/src/transaction.ts
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2084.
=> feat: implement single-sig orgs

ui/DesignSystem/RadioOption.svelte
Fixes https://github.com/radicle-dev/radicle-upstream/issues/2086
=> fix: enable option transition only when not active

DEVELOPMENT.md
=> fix: explain that app needs to be restarted after reset

Cargo.lock, Cargo.toml, proxy/api/Cargo.toml, proxy/api/src/config.rs, proxy/api/src/context.rs, proxy/api/src/http.rs, proxy/api/src/http/identity.rs, proxy/api/src/identity.rs, proxy/api/src/process.rs
Depends on https://github.com/radicle-dev/radicle-link/pull/709
Required changing the get_user calls to get_local.
Signed-off-by: Fintan Halpenny <fintan.halpenny@gmail.com>
=> proxy(chore): update librad to include Person changes

docs/wallet-connect-testing.md
Add instructions for manually testing WalletConnect.
=> test: add instructions for manually testing WalletConnect

ui/Modal/Org/Create.svelte
=> Fix typo in Org creation modal

ui/src/wallet.ts
This is a pre-requisite for us to switch to their event based API.
=> refactor: switch to websocket based Infura API

ui/Screen/Onboarding/EnterPassphrase.svelte
We work around https://github.com/sveltejs/language-tools/issues/961 to satisfy the type checker.
=> fix: work around svelte2tsx bug for type checking

DEVELOPMENT.md, README.md
We describe how to run the app from source against real user data. This should help users that want to build and run the app from source.
We add this to the development doc and the readme to make it more promentnt. We also move this section to the top of the file to make it more prominent.
=> docs: describe how to run app against real data

ui/src/ethereum/walletConnect.ts
| Before | After |
|-------|-------|
| ![IMG_9661](https://user-images.githubusercontent.com/158411/128205098-9a96e3f8-4cbd-4bf8-a291-0e96ed9e825d.PNG) | ![IMG_9662](https://user-images.githubusercontent.com/158411/128223530-af3ed926-fea7-445e-9302-350b524e1afb.png) |
=> fix: show icon and website when connecting via walletconnect

ui/DesignSystem/TextInput.svelte, ui/Screen/DesignSystemGuide.svelte
This will be needed by the ENS registration. Note that we made a small adjustment to the code from #2191.
=> feat: add `suffix` property to text input

DEVELOPMENT.md, scripts/release.ts
=> update release process description to new bucket location

ui/src/org/ensResolver.ts
Just like the change in #2203 we don’t use a stale wallet value.
=> fix: don’t use stale wallet in resolver

ui/src/ethereum/walletConnectSigner.ts, ui/src/org.ts, ui/src/org/ensRegistrar.ts, ui/src/wallet.ts
More simplifications and cleanup
=> ENS registration cleanup

ui/DesignSystem/Wallet/Panel.svelte, ui/Screen/Wallet.svelte, ui/src/funding/pool.ts, ui/src/wallet.ts, ui/src/wallet/daiToken.ts, ui/src/wallet/radToken.ts
Required by https://github.com/radicle-dev/radicle-upstream/pull/2191.
Closes https://github.com/radicle-dev/radicle-upstream/issues/2222.
=> Show RAD token balance on wallet screen

DEVELOPMENT.md, cypress/support/ipc-stub.ts, cypress/support/nodeManager.ts, native/index.ts, native/preload.d.ts, native/preload.js, ui/DesignSystem/SourceBrowser/RevisionSelector.svelte, ui/DesignSystem/Wallet/Panel.svelte, ui/Hotkeys.svelte, ui/Modal/Shortcuts.svelte, ui/Screen/Wallet.svelte, ui/src/api.ts, ui/src/config.ts, ui/src/ethereum/index.ts, ui/src/localPeer.ts, ui/src/proxy/index.ts
We unify the mechanism to configure the UI. This makes it extendable if we want to add more configuration parameters.
=> refactor: unify UI configuration

cypress/tsconfig.json, ui/DesignSystem/Avatar.svelte, ui/DesignSystem/ProjectAnchorPopover.svelte, ui/Screen/Org/route.ts, ui/src/org.ts, ui/src/org/theGraphApi.ts, ui/src/project.ts
=> Show ENS metadata in pending anchor popover

ui/DesignSystem/Avatar.svelte
=> refactor: type Avatar props consistently

cypress/tsconfig.json, tsconfig.json
=> chore: targed ES2020

ui/Screen/Org/MembersMenu.svelte, ui/Screen/Org/Projects.svelte
We don't use the word "organization" when talking about our "org" feature.
=> chore: use "org" consistently

cypress/integration/project/creation.spec.ts, ui/Modal/NewProject.svelte
Buttons got moved out of the container that was targeted by `data-cy="create-project"` which made specs fail.
=> fix: fix regression from Modal update

ui/Screen/Lock.svelte
Ended up being a single line change 😅 
Fixes #2233
=> Show passphrase button always visible on lock screen

ui/src/org.ts
Poll orgs once every 5 minutes. When org creation is in progress poll every 15 seconds.
Closes https://github.com/radicle-dev/radicle-upstream/issues/2171.
=> fix: reduce The Graph API request amount

ui/src/org/theGraphApi.ts
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2170.
=> chore: use The Graph mainnet API endpoint

cypress/integration/attestation.spec.ts, cypress/support/commands.ts, ui/DesignSystem/Wallet/Transactions/TxListItem.svelte, ui/Modal/Transaction.svelte
=> dev: add tests for transaction modal

ui/src/org.ts
We stopped polling the org sidebar list frequently in 3e3c553dadcfa5db6b7afb44edbe196312b2ce57, which as a side-effect made wallet switching seem to also update the sidebar. Now that we update the sidebar once in 5 minutes we have to listen to wallet updates to update the sidebar org list.
=> fix: reload orgs on wallet switch

ui/src/org.ts
I fixed my editor, shouldn't happen again:
https://github.com/rudolfs/dotfiles/commit/84a970a0fbb98df819bc6da9e37b9168340592cc#diff-8637eb1743381fff871c19ea557fb7d738660759d84f683e134d7ce56d15055dR8.
=> fix: fix prettier formatting

docs/infrastructure.md
=> chore: document the infrastructure that we own

cypress/support/commands.ts
For each test we use the same path to store data instead of a new patch for every run of the same test. This means that we overwrite data from previous runs. In practice I haven’t found it useful to have data from previous runs. On the contrary: If there are artifacts from multiple runs it is difficult to find those of the current run.
=> dev: use predictable path for test data

ui/App/OrgScreen/ConfigureEns/Intro.svelte
Closes https://github.com/radicle-dev/radicle-upstream/issues/2326.
=> fix: update link to docs on how to obtain RAD token

ui/DesignSystem/Dropdown.svelte, ui/DesignSystem/Dropdown/Option.svelte
We remove unused bits from the component to reduce its complexity.
Refs: https://github.com/radicle-dev/radicle-upstream/issues/1877.
=> refactor: simplify Dropdown component

ui/App/DesignSystemGuideModal.svelte
Refs: https://github.com/radicle-dev/radicle-upstream/issues/1877.
=> chore: improve TextInput examples in DesignSystem

ui/App/DesignSystemGuideModal.svelte, ui/App/ShortcutsModal.svelte, ui/DesignSystem/KeyHint.svelte, ui/DesignSystem/PasswordInput.svelte, ui/DesignSystem/TextInput.svelte
Refs: https://github.com/radicle-dev/radicle-upstream/issues/1877.
=> refactor: decouple KeyHint component from Upstream code

ui/src/attestation/contract.ts
We want to reduce the amount of requests we make to Infura.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2108.
=> fix: cache claimed identities for one minute

ui/App/LoadingScreen.svelte, ui/App/OnboardingModal/EnterName.svelte, ui/App/OrgScreen/MembersMenu.svelte, ui/App/ProjectScreen/RemoteHelperHint.svelte, ui/App/ProjectScreen/Source/CheckoutButton.svelte, ui/App/Sidebar/ConnectionStatusIndicator/Offline.svelte, ui/App/Theme.svelte, ui/App/WalletScreen/Pool.svelte, ui/App/WalletScreen/Pool/Outgoing.svelte, ui/DesignSystem/Checkbox.svelte
This way we catch errors at compile time via `svelte-check`.
=> fix: make sure all svelte files have the typescript lang tag

ui/App/OrgScreen/Projects.svelte
When the quorum of members have signed a transaction on Gnosis Safe, this transaction still needs to be executed by one of the members manually before it gets submitted to the blockchain. In this case show a different message to the user so they know what needs to be done.
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2092.
=> fix: improve pending anchor message

ui/App/SettingsScreen.svelte
Closes https://github.com/radicle-dev/radicle-upstream/issues/1938.
=> chore: update support channel

ui/App/OrgScreen/OrgHeader.svelte, ui/App/ProjectScreen.svelte, ui/App/ProjectScreen/RemoteHelperHint.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/1321.
=> style: make copy-to-clipboard notification consistent

ui/App/OrgScreen/AnchorProjectModal.svelte, ui/App/ProjectScreen/PeerSelector.svelte
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2095.
https://user-images.githubusercontent.com/158411/132876811-ebc61d67-013b-4f51-9c1a-04dd35f5f51b.mov
=> style: add button animation to PeerSelector in anchor modal

cypress/integration/attestation.spec.ts, ui/App/OrgScreen.svelte, ui/App/SingleSigOrgScreen.svelte, ui/App/WalletScreen.svelte, ui/App/WalletScreen/ConnectWallet.svelte, ui/App/WalletScreen/LinkAddress.svelte, ui/App/WalletScreen/LinkAddressModal.svelte, ui/App/WalletScreen/LinkAddressModal/TransactionButton.svelte
Closes: #2110
Refs: https://github.com/radicle-dev/radicle-upstream/pull/2357#issuecomment-916304256
=> chore: improve wording related to the orgs feature

ui/App/WalletScreen/ConnectWallet.svelte
Closes https://github.com/radicle-dev/radicle-upstream/issues/2373.
=> chore: improve wording on wallet page

.github/workflows/build.yaml
Also upload distribution artifacts on master builds
=> chore: run github actions on every PR

ui/App/SettingsScreen.svelte, ui/App/Theme.svelte
=> Make it work

public/colors.css, ui/App/DesignSystemGuideModal.svelte, ui/App/SettingsScreen.svelte, ui/App/Theme.svelte
Partially addresses #1803 
You can choose between Blue / Pink / Orange but not add a custom HEX yet, will be addressed in a subsequent PR
=> Add primary font color to settings

ui/App/ProfileScreen/Following.svelte, ui/App/ProjectScreen.svelte, ui/App/ProjectScreen/ManagePeers/Peer.svelte, ui/App/ProjectScreen/ManagePeers/PeerFollowRequest.svelte, ui/App/ProjectScreen/ManagePeersModal.svelte, ui/App/ProjectScreen/Source/Code.svelte, ui/src/project.ts, ui/src/project/patch.ts, ui/src/screen/project.ts, ui/src/source.ts
This type alias didn't really give us more type safety and required more imports.
=> refactor: remove Urn type alias

ui/App/ProjectScreen/RemoteHelperHint.svelte
Because it threw me off initially.
=> refactor: improve helper hint store readability

ui/src/remote.ts
Instead of using locally declared type aliases for we use the proper
types from `svelte/store`.
=> refactor: use svelte types in remote store

proxy/api/src/http/error.rs
=> fix: respond with 404 if project is not found

ui/App/NetworkScreen.svelte, ui/App/ProfileScreen.svelte, ui/App/ProfileScreen/ProjectCardSquare.svelte
=> Add hover states to profile cards

ui/App/DesignSystemGuideModal.svelte, ui/DesignSystem/Tooltip.svelte
This reverts commit 20136cf890bfb32bc6eafe320e28dd4a3ceccfcb.
=> Revert "fix: relative positioning for tooltips"

Cargo.lock, proxy/api/Cargo.toml, proxy/api/src/context.rs, proxy/api/src/error.rs, proxy/api/src/http/error.rs, proxy/api/src/http/identity.rs, proxy/api/src/identity.rs, proxy/api/src/process.rs
We use the `rad-identities` crate to get information about a person
identity.
This is the first step in #2432.
=> feat: use rad-identities to get person information

ui/DesignSystem/Loading.svelte
=> chore: resolve svelte-check warning

ui/App/ProfileScreen.svelte, ui/App/ScreenLayout.svelte, ui/App/Sidebar.svelte
This is a set of improvements to simplify the `ScreenLayout` component as preparation to tackle #2492.
=> ScreenLayout improvements

ui/DesignSystem/ThreeDotsMenu.svelte
Remove unused functionality to reduce dependencies.
Refs https://github.com/radicle-dev/radicle-upstream/issues/1877.
=> refactor: simplify ThreeDotsMenu component

Cargo.lock, Cargo.toml, upstream-seed/Cargo.toml, upstream-seed/README.md, upstream-seed/src/cli.rs, upstream-seed/src/lib.rs, upstream-seed/src/main.rs, upstream-seed/src/peer.rs
=> add `upstream-seed` crate

proxy-client/index.ts, proxy/api/src/http/diagnostics.rs, ui/App/DiagnosticsScreen.svelte, ui/App/DiagnosticsScreen/Connections.svelte
Closes https://github.com/radicle-dev/radicle-upstream/issues/2547.
=> feat: add peer membership to diagnostics screen

proxy/api/src/process.rs
Replace `RunError` with `anyhow::Error` to make the code simpler.
=> replace `RunError` with `anyhow::Error`

upstream-seed/Cargo.toml, upstream-seed/src/lib.rs, upstream-seed/src/peer.rs
=> shutdown upstream seed gracefully

docs/infrastructure.md
Mention the `seed-node` instance.
=> docs: document seed-node instance

upstream-seed/src/lib.rs, upstream-seed/src/peer.rs
The seed replicates forks of the configured projects from all connected peers. It does so by trying to fetch the initial fork whenever a new peer connects.
This mechanism subsumes the `track_projects` task which queried providers periodically via gossip.
Fixes #2569.
Follow-up
=> seed: replicate projects from all providing peers

ui/App/OrgScreen.svelte, ui/App/SingleSigOrgScreen.svelte
=> aligned sidebar width to profile page

upstream-seed/src/peer.rs
To avoid confusion we don’t return and log an error when fetching an identity from a peer fails. Since we’re trying to fetch an identity from every remote peer there’s no guarantee that the remote provides the identity.
=> seed: don’t log error when remote peer doesn’t provide identity

ui/App/ProjectScreen/Source/Code.svelte
Eliminate redundant elements and style attributes to make the styling of `Code` much simpler.
=> simplify CSS styling for `Code` component

.github/workflows/dist.yaml, ci/dist.sh, upstream-seed/README.md
=> publish upstream seed binaries on `main` builds

proxy/api/src/context.rs, proxy/api/src/http/notification.rs, proxy/api/src/process.rs
Three commit that simplify `Context`. See commit messages for details.
=> proxy: simplify context

cypress/plugins/nodeManager/plugin.ts
=> tests: retry when proxy has not reloaded yet

docs/infrastructure.md, infra/seed-node/README.md, infra/seed-node/google-cloud-ops-agent-config.yaml, infra/seed-node/setup.sh, infra/seed-node/update-upstream-seed.sh, infra/seed-node/upstream-seed.env, infra/seed-node/upstream-seed.service, scripts/license-header.ts, upstream-seed/src/cli.rs, upstream-seed/src/lib.rs
Add documentation and scripts to explain the provisioning of a stable hosted `upstream-seed`.
Fixes #2620.
=> provision stable upstream seed

ui/App/OrgScreen.svelte, ui/App/OrgScreen/ConfigureEns/LinkOrgToName.svelte, ui/App/OrgScreen/MembersMenu.svelte, ui/App/OrgScreen/Projects.svelte, ui/src/org.ts, ui/src/org/safe.ts
Refs https://github.com/gnosis/safe-react/issues/970.
=> fix: use new URL layout for Gnosis Safe deep links

ui/App/NetworkScreen.svelte
Simplify the seed input validation so that it doesn’t use the deprecated `ui/src/validation` module. This also removes the `Promise.resolve()` hack that was necessary.
=> simplify seed input validation and remove hack

upstream-seed/src/peer.rs
Add more information to the peer logs and make them more readable by relying on `Display` instances for values certain values.
=> seed: more readable and useful logging

.github/workflows/dist.yaml, ci/dist.sh
Upload the artifacts in the `dist` job so that the build is faster.
=> build: upload artifacts in dist job

proxy/api/src/process.rs, upstream-seed/src/lib.rs
Make the proxy logs more readable by improving the formatting. Add logging fields to a statement in the seed to provide some context. Also extract logging tasks into separate functions.
=> make logs more readable

.gitignore, Vagrantfile, docs/infrastructure.md, p2p-tests/lib/p2p.ts
So we can get rid of the dev vm on gcp.
=> test: make p2p network tests work on Intel macOS hosts

cypress/integration/networking.spec.ts, ui/App/NetworkScreen.svelte
Fixes a regression introduced in https://github.com/radicle-dev/radicle-upstream/pull/2658.
=> fix: clear seed input after adding seed

upstream-seed/README.md
Add a “Getting Started” section to the readme that provides more details how to use the seed.
Also update some outdated points in the “Features” section.
=> seed: add “getting started” to readme

p2p-tests/lib/p2p.ts
We force an immediate shutdown of the proxy and the seed instances when a test finishes. Otherwise, a new test might be running already why the shutdown of one of the processes is still in progress.
Hopefully, this makes some of the tests more stable.
=> tests: force immediate shutdown of proxy and seed

ui/src/org/safe.ts
Use `retryOnError` instead of custom retry logic. Also show an error when fetching the safe finally fails.
=> use `retryOnError` instead of custom retry logic

upstream-seed/src/peer.rs
Refs https://github.com/radicle-dev/radicle-upstream/issues/2713.
=> fix: announcements not reliable on seed

docs/user-stories/accepting-contributions-workflow.md
Refs https://github.com/radicle-dev/radicle-upstream/issues/2712.
=> docs: add "accepting contributions workflow" doc

scripts/devnet.ts
When the devnet script receives Ctrl+C or SIGTERM it does not exit immediately anymore instead. Instead it forwards the signal to the child process (radicle-proxy, upstream-seed, upstream) and waits for the process to exit.
=> devnet script waits for the child process before exiting

native/index.ts, native/windowManager.ts
We improve code quality in `native/index.ts`
* Extract `WindowManager` to its own module to reduce module size
* Move code running in module scope into the `main` function.
* use `execa` instead of handcrafted function
=> modularize electron main process code
